// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the AttributeCategory class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the AttributeCategory class.")]
  public enum AttributeCategoryId : byte
  {

    /// <summary>Fitting capabilities of a ship</summary>
    [Description("Fitting")]
    [LongDescription("Fitting capabilities of a ship")]
    Fitting = 1,

    /// <summary>Shield attributes of ships</summary>
    [Description("Shield")]
    [LongDescription("Shield attributes of ships")]
    Shield = 2,

    /// <summary>Armor attributes of ships</summary>
    [Description("Armor")]
    [LongDescription("Armor attributes of ships")]
    Armor = 3,

    /// <summary>Structure attributes of ships</summary>
    [Description("Structure")]
    [LongDescription("Structure attributes of ships")]
    Structure = 4,

    /// <summary>Capacitor attributes for ships</summary>
    [Description("Capacitor")]
    [LongDescription("Capacitor attributes for ships")]
    Capacitor = 5,

    /// <summary>Targeting Attributes for ships</summary>
    [Description("Targeting")]
    [LongDescription("Targeting Attributes for ships")]
    Targeting = 6,

    /// <summary>Misc. attributes</summary>
    [Description("Miscellaneous")]
    [LongDescription("Misc. attributes")]
    Miscellaneous = 7,

    /// <summary>Skill requirements</summary>
    [Description("Required Skills")]
    [LongDescription("Skill requirements")]
    RequiredSkills = 8,

    /// <summary>Attributes already checked and not going into a category</summary>
    [Description("NULL")]
    [LongDescription("Attributes already checked and not going into a category")]
    Null = 9,

    /// <summary>All you need to know about drones</summary>
    [Description("Drones")]
    [LongDescription("All you need to know about drones")]
    Drones = 10,

    /// <summary>Attribs for the AI configuration</summary>
    [Description("AI")]
    [LongDescription("Attribs for the AI configuration")]
    Ai = 12,
  }
}
