// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve {


  /// <summary>Contains the ID values associated with the AttributeCategory class.</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Eve.Meta", "1.76.447.40603")]
  [System.ComponentModel.DescriptionAttribute("Contains the ID values associated with the AttributeCategory class.")]
  public enum AttributeCategoryId : byte {

    /// <summary>Fitting capabilities of a ship</summary>
    
    [System.ComponentModel.DescriptionAttribute("Fitting capabilities of a ship")]
    Fitting = 1,

    /// <summary>Shield attributes of ships</summary>
    
    [System.ComponentModel.DescriptionAttribute("Shield attributes of ships")]
    Shield = 2,

    /// <summary>Armor attributes of ships</summary>
    
    [System.ComponentModel.DescriptionAttribute("Armor attributes of ships")]
    Armor = 3,

    /// <summary>Structure attributes of ships</summary>
    
    [System.ComponentModel.DescriptionAttribute("Structure attributes of ships")]
    Structure = 4,

    /// <summary>Capacitor attributes for ships</summary>
    
    [System.ComponentModel.DescriptionAttribute("Capacitor attributes for ships")]
    Capacitor = 5,

    /// <summary>Targeting Attributes for ships</summary>
    
    [System.ComponentModel.DescriptionAttribute("Targeting Attributes for ships")]
    Targeting = 6,

    /// <summary>Misc. attributes</summary>
    
    [System.ComponentModel.DescriptionAttribute("Misc. attributes")]
    Miscellaneous = 7,

    /// <summary>Skill requirements</summary>
    
    [System.ComponentModel.DescriptionAttribute("Skill requirements")]
    RequiredSkills = 8,

    /// <summary>Attributes already checked and not going into a category</summary>
    
    [System.ComponentModel.DescriptionAttribute("Attributes already checked and not going into a category")]
    Null = 9,

    /// <summary>All you need to know about drones</summary>
    
    [System.ComponentModel.DescriptionAttribute("All you need to know about drones")]
    Drones = 10,

    /// <summary>Attribs for the AI configuration</summary>
    
    [System.ComponentModel.DescriptionAttribute("Attribs for the AI configuration")]
    Ai = 12,
  }
}
