// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve {


  /// <summary>Contains the ID values associated with the Category class.</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Eve.Meta", "1.76.447.42430")]
  [System.ComponentModel.DescriptionAttribute("Contains the ID values associated with the Category class.")]
  public enum CategoryId : int {

    
    System = 0,

    
    Owner = 1,

    
    Celestial = 2,

    
    Station = 3,

    
    Material = 4,

    
    Accessories = 5,

    
    Ship = 6,

    
    Module = 7,

    
    Charge = 8,

    
    Blueprint = 9,

    
    Trading = 10,

    
    Entity = 11,

    /// <summary>Character creation bonuses.  Like innate skills but genetic rather than learned.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Character creation bonuses.  Like innate skills but genetic rather than learned.")]
    Bonus = 14,

    /// <summary>Where all the skills go under.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Where all the skills go under.")]
    Skill = 16,

    
    Commodity = 17,

    /// <summary>Player owned and controlled drones.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Player owned and controlled drones.")]
    Drone = 18,

    /// <summary>Implant</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implant")]
    Implant = 20,

    
    Deployable = 22,

    /// <summary>Player owned structure related objects</summary>
    
    [System.ComponentModel.DescriptionAttribute("Player owned structure related objects")]
    Structure = 23,

    
    Reaction = 24,

    
    Asteroid = 25,

    /// <summary>Worldspaces and related stuff</summary>
    
    [System.ComponentModel.DescriptionAttribute("Worldspaces and related stuff")]
    WorldSpace = 26,

    /// <summary>Abstract grouping, global types and groups for the UI, such as Ranks, Ribbons and Medals.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Abstract grouping, global types and groups for the UI, such as Ranks, Ribbons and" +
        " Medals.")]
    Abstract = 29,

    /// <summary>1. clothing, especially outerwear; garments; attire; raiment.
    ///2. anything that decorates or covers.
    ///3. superficial appearance; aspect; guise. </summary>
    
    [System.ComponentModel.DescriptionAttribute("1. clothing, especially outerwear; garments; attire; raiment.\r\n2. anything that d" +
        "ecorates or covers.\r\n3. superficial appearance; aspect; guise. ")]
    Apparel = 30,

    /// <summary>Subsystems for tech 3 ships</summary>
    
    [System.ComponentModel.DescriptionAttribute("Subsystems for tech 3 ships")]
    Subsystem = 32,

    
    AncientRelics = 34,

    
    Decryptors = 35,

    
    InfrastructureUpgrades = 39,

    
    SovereigntyStructures = 40,

    /// <summary>Stuff for planetary interaction</summary>
    
    [System.ComponentModel.DescriptionAttribute("Stuff for planetary interaction")]
    PlanetaryInteraction = 41,

    /// <summary>These are Items that can be extracted from a planet. </summary>
    
    [System.ComponentModel.DescriptionAttribute("These are Items that can be extracted from a planet. ")]
    PlanetaryResources = 42,

    
    PlanetaryCommodities = 43,

    /// <summary>Anchorable/Onlinable objects that operate similar to POS/SOV structures, but do not link to towers or sovereignty. Each class of orbital defines its own valid anchoring locations via Python code.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Anchorable/Onlinable objects that operate similar to POS/SOV structures, but do n" +
        "ot link to towers or sovereignty. Each class of orbital defines its own valid an" +
        "choring locations via Python code.")]
    Orbitals = 46,

    /// <summary>Placeables are things you can put into rooms. </summary>
    
    [System.ComponentModel.DescriptionAttribute("Placeables are things you can put into rooms. ")]
    Placeables = 49,

    
    Effects = 53,

    
    Lights = 54,

    
    Cells = 59,

    
    Catma = 350001,
  }
}
