// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve {


  /// <summary>Contains the ID values associated with the Category class.</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Eve.Meta", "1.76.447.42430")]
  [System.ComponentModel.DescriptionAttribute("Contains the ID values associated with the Category class.")]
  public enum CategoryId : int {

    [FreeNet.Globalization.LocalizedLabelAttribute("#System", "Eve.CategoryId_System")]
    System = 0,

    [FreeNet.Globalization.LocalizedLabelAttribute("Owner", "Eve.CategoryId_Owner")]
    Owner = 1,

    [FreeNet.Globalization.LocalizedLabelAttribute("Celestial", "Eve.CategoryId_Celestial")]
    Celestial = 2,

    [FreeNet.Globalization.LocalizedLabelAttribute("Station", "Eve.CategoryId_Station")]
    Station = 3,

    [FreeNet.Globalization.LocalizedLabelAttribute("Material", "Eve.CategoryId_Material")]
    Material = 4,

    [FreeNet.Globalization.LocalizedLabelAttribute("Accessories", "Eve.CategoryId_Accessories")]
    Accessories = 5,

    [FreeNet.Globalization.LocalizedLabelAttribute("Ship", "Eve.CategoryId_Ship")]
    Ship = 6,

    [FreeNet.Globalization.LocalizedLabelAttribute("Module", "Eve.CategoryId_Module")]
    Module = 7,

    [FreeNet.Globalization.LocalizedLabelAttribute("Charge", "Eve.CategoryId_Charge")]
    Charge = 8,

    [FreeNet.Globalization.LocalizedLabelAttribute("Blueprint", "Eve.CategoryId_Blueprint")]
    Blueprint = 9,

    [FreeNet.Globalization.LocalizedLabelAttribute("Trading", "Eve.CategoryId_Trading")]
    Trading = 10,

    [FreeNet.Globalization.LocalizedLabelAttribute("Entity", "Eve.CategoryId_Entity")]
    Entity = 11,

    /// <summary>Character creation bonuses.  Like innate skills but genetic rather than learned.</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Bonus", "Eve.CategoryId_Bonus")]
    [System.ComponentModel.DescriptionAttribute("Character creation bonuses.  Like innate skills but genetic rather than learned.")]
    Bonus = 14,

    /// <summary>Where all the skills go under.</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Skill", "Eve.CategoryId_Skill")]
    [System.ComponentModel.DescriptionAttribute("Where all the skills go under.")]
    Skill = 16,

    [FreeNet.Globalization.LocalizedLabelAttribute("Commodity", "Eve.CategoryId_Commodity")]
    Commodity = 17,

    /// <summary>Player owned and controlled drones.</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Drone", "Eve.CategoryId_Drone")]
    [System.ComponentModel.DescriptionAttribute("Player owned and controlled drones.")]
    Drone = 18,

    /// <summary>Implant</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Implant", "Eve.CategoryId_Implant")]
    [System.ComponentModel.DescriptionAttribute("Implant")]
    Implant = 20,

    [FreeNet.Globalization.LocalizedLabelAttribute("Deployable", "Eve.CategoryId_Deployable")]
    Deployable = 22,

    /// <summary>Player owned structure related objects</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Structure", "Eve.CategoryId_Structure")]
    [System.ComponentModel.DescriptionAttribute("Player owned structure related objects")]
    Structure = 23,

    [FreeNet.Globalization.LocalizedLabelAttribute("Reaction", "Eve.CategoryId_Reaction")]
    Reaction = 24,

    [FreeNet.Globalization.LocalizedLabelAttribute("Asteroid", "Eve.CategoryId_Asteroid")]
    Asteroid = 25,

    /// <summary>Worldspaces and related stuff</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("WorldSpace", "Eve.CategoryId_WorldSpace")]
    [System.ComponentModel.DescriptionAttribute("Worldspaces and related stuff")]
    WorldSpace = 26,

    /// <summary>Abstract grouping, global types and groups for the UI, such as Ranks, Ribbons and Medals.</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Abstract", "Eve.CategoryId_Abstract")]
    [System.ComponentModel.DescriptionAttribute("Abstract grouping, global types and groups for the UI, such as Ranks, Ribbons and" +
        " Medals.")]
    Abstract = 29,

    /// <summary>1. clothing, especially outerwear; garments; attire; raiment.
    ///2. anything that decorates or covers.
    ///3. superficial appearance; aspect; guise. </summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Apparel", "Eve.CategoryId_Apparel")]
    [System.ComponentModel.DescriptionAttribute("1. clothing, especially outerwear; garments; attire; raiment.\r\n2. anything that d" +
        "ecorates or covers.\r\n3. superficial appearance; aspect; guise. ")]
    Apparel = 30,

    /// <summary>Subsystems for tech 3 ships</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Subsystem", "Eve.CategoryId_Subsystem")]
    [System.ComponentModel.DescriptionAttribute("Subsystems for tech 3 ships")]
    Subsystem = 32,

    [FreeNet.Globalization.LocalizedLabelAttribute("Ancient Relics", "Eve.CategoryId_AncientRelics")]
    AncientRelics = 34,

    [FreeNet.Globalization.LocalizedLabelAttribute("Decryptors", "Eve.CategoryId_Decryptors")]
    Decryptors = 35,

    [FreeNet.Globalization.LocalizedLabelAttribute("Infrastructure Upgrades", "Eve.CategoryId_InfrastructureUpgrades")]
    InfrastructureUpgrades = 39,

    [FreeNet.Globalization.LocalizedLabelAttribute("Sovereignty Structures", "Eve.CategoryId_SovereigntyStructures")]
    SovereigntyStructures = 40,

    /// <summary>Stuff for planetary interaction</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Planetary Interaction", "Eve.CategoryId_PlanetaryInteraction")]
    [System.ComponentModel.DescriptionAttribute("Stuff for planetary interaction")]
    PlanetaryInteraction = 41,

    /// <summary>These are Items that can be extracted from a planet. </summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Planetary Resources", "Eve.CategoryId_PlanetaryResources")]
    [System.ComponentModel.DescriptionAttribute("These are Items that can be extracted from a planet. ")]
    PlanetaryResources = 42,

    [FreeNet.Globalization.LocalizedLabelAttribute("Planetary Commodities", "Eve.CategoryId_PlanetaryCommodities")]
    PlanetaryCommodities = 43,

    /// <summary>Anchorable/Onlinable objects that operate similar to POS/SOV structures, but do not link to towers or sovereignty. Each class of orbital defines its own valid anchoring locations via Python code.</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Orbitals", "Eve.CategoryId_Orbitals")]
    [System.ComponentModel.DescriptionAttribute("Anchorable/Onlinable objects that operate similar to POS/SOV structures, but do n" +
        "ot link to towers or sovereignty. Each class of orbital defines its own valid an" +
        "choring locations via Python code.")]
    Orbitals = 46,

    /// <summary>Placeables are things you can put into rooms. </summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("Placeables", "Eve.CategoryId_Placeables")]
    [System.ComponentModel.DescriptionAttribute("Placeables are things you can put into rooms. ")]
    Placeables = 49,

    [FreeNet.Globalization.LocalizedLabelAttribute("Effects", "Eve.CategoryId_Effects")]
    Effects = 53,

    [FreeNet.Globalization.LocalizedLabelAttribute("Lights", "Eve.CategoryId_Lights")]
    Lights = 54,

    [FreeNet.Globalization.LocalizedLabelAttribute("Cells", "Eve.CategoryId_Cells")]
    Cells = 59,

    [FreeNet.Globalization.LocalizedLabelAttribute("Catma", "Eve.CategoryId_Catma")]
    Catma = 350001,
  }
}
