// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the Category class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the Category class.")]
  public enum CategoryId : int
  {

    /// <summary>#System</summary>
    [Description("#System")]
    System = 0,

    /// <summary>Owner</summary>
    [Description("Owner")]
    Owner = 1,

    /// <summary>Celestial</summary>
    [Description("Celestial")]
    Celestial = 2,

    /// <summary>Station</summary>
    [Description("Station")]
    Station = 3,

    /// <summary>Material</summary>
    [Description("Material")]
    Material = 4,

    /// <summary>Accessories</summary>
    [Description("Accessories")]
    Accessories = 5,

    /// <summary>Ship</summary>
    [Description("Ship")]
    Ship = 6,

    /// <summary>Module</summary>
    [Description("Module")]
    Module = 7,

    /// <summary>Charge</summary>
    [Description("Charge")]
    Charge = 8,

    /// <summary>Blueprint</summary>
    [Description("Blueprint")]
    Blueprint = 9,

    /// <summary>Trading</summary>
    [Description("Trading")]
    Trading = 10,

    /// <summary>Entity</summary>
    [Description("Entity")]
    Entity = 11,

    /// <summary>Character creation bonuses.  Like innate skills but genetic rather than learned.</summary>
    [Description("Bonus")]
    [LongDescription("Character creation bonuses.  Like innate skills but genetic rather than learned.")]
    Bonus = 14,

    /// <summary>Where all the skills go under.</summary>
    [Description("Skill")]
    [LongDescription("Where all the skills go under.")]
    Skill = 16,

    /// <summary>Commodity</summary>
    [Description("Commodity")]
    Commodity = 17,

    /// <summary>Player owned and controlled drones.</summary>
    [Description("Drone")]
    [LongDescription("Player owned and controlled drones.")]
    Drone = 18,

    /// <summary>Implant</summary>
    [Description("Implant")]
    [LongDescription("Implant")]
    Implant = 20,

    /// <summary>Deployable</summary>
    [Description("Deployable")]
    Deployable = 22,

    /// <summary>Player owned structure related objects</summary>
    [Description("Structure")]
    [LongDescription("Player owned structure related objects")]
    Structure = 23,

    /// <summary>Reaction</summary>
    [Description("Reaction")]
    Reaction = 24,

    /// <summary>Asteroid</summary>
    [Description("Asteroid")]
    Asteroid = 25,

    /// <summary>Worldspaces and related stuff</summary>
    [Description("WorldSpace")]
    [LongDescription("Worldspaces and related stuff")]
    WorldSpace = 26,

    /// <summary>Abstract grouping, global types and groups for the UI, such as Ranks, Ribbons and Medals.</summary>
    [Description("Abstract")]
    [LongDescription("Abstract grouping, global types and groups for the UI, such as Ranks, Ribbons and" +
        " Medals.")]
    Abstract = 29,

    /// <summary>1. clothing, especially outerwear; garments; attire; raiment.
    ///2. anything that decorates or covers.
    ///3. superficial appearance; aspect; guise. </summary>
    [Description("Apparel")]
    [LongDescription("1. clothing, especially outerwear; garments; attire; raiment.\r\n2. anything that d" +
        "ecorates or covers.\r\n3. superficial appearance; aspect; guise. ")]
    Apparel = 30,

    /// <summary>Subsystems for tech 3 ships</summary>
    [Description("Subsystem")]
    [LongDescription("Subsystems for tech 3 ships")]
    Subsystem = 32,

    /// <summary>Ancient Relics</summary>
    [Description("Ancient Relics")]
    AncientRelics = 34,

    /// <summary>Decryptors</summary>
    [Description("Decryptors")]
    Decryptors = 35,

    /// <summary>Infrastructure Upgrades</summary>
    [Description("Infrastructure Upgrades")]
    InfrastructureUpgrades = 39,

    /// <summary>Sovereignty Structures</summary>
    [Description("Sovereignty Structures")]
    SovereigntyStructures = 40,

    /// <summary>Stuff for planetary interaction</summary>
    [Description("Planetary Interaction")]
    [LongDescription("Stuff for planetary interaction")]
    PlanetaryInteraction = 41,

    /// <summary>These are Items that can be extracted from a planet. </summary>
    [Description("Planetary Resources")]
    [LongDescription("These are Items that can be extracted from a planet. ")]
    PlanetaryResources = 42,

    /// <summary>Planetary Commodities</summary>
    [Description("Planetary Commodities")]
    PlanetaryCommodities = 43,

    /// <summary>Anchorable/Onlinable objects that operate similar to POS/SOV structures, but do not link to towers or sovereignty. Each class of orbital defines its own valid anchoring locations via Python code.</summary>
    [Description("Orbitals")]
    [LongDescription("Anchorable/Onlinable objects that operate similar to POS/SOV structures, but do n" +
        "ot link to towers or sovereignty. Each class of orbital defines its own valid an" +
        "choring locations via Python code.")]
    Orbitals = 46,

    /// <summary>Placeables are things you can put into rooms. </summary>
    [Description("Placeables")]
    [LongDescription("Placeables are things you can put into rooms. ")]
    Placeables = 49,

    /// <summary>Effects</summary>
    [Description("Effects")]
    Effects = 53,

    /// <summary>Lights</summary>
    [Description("Lights")]
    Lights = 54,

    /// <summary>Cells</summary>
    [Description("Cells")]
    Cells = 59,

    /// <summary>Special Edition Assets</summary>
    [Description("Special Edition Assets")]
    [LongDescription("Special Edition Assets")]
    SpecialEditionAssets = 63,

    /// <summary>Infantry</summary>
    [Description("Infantry")]
    Infantry = 350001,
  }
}
