// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve {
  using System.CodeDom.Compiler;
  using System.ComponentModel;


  /// <summary>Contains the ID values associated with the EffectType class.</summary>
  [GeneratedCode("Eve", "1.76.447.36430")]
  [Description("Contains the ID values associated with the EffectType class.")]
  public enum EffectId : short {

    /// <summary>shieldBoosting</summary>
    
    ShieldBoosting = 4,

    /// <summary>speedBoost</summary>
    
    SpeedBoost = 7,

    /// <summary>Launches a missile</summary>
    [Description("Launches a missile")]
    
    MissileLaunching = 9,

    /// <summary>Combat</summary>
    [Description("Combat")]
    
    TargetAttack = 10,

    /// <summary>Requires a low power slot.</summary>
    [Description("Requires a low power slot.")]
    
    LoPower = 11,

    /// <summary>Requires a high power slot.</summary>
    [Description("Requires a high power slot.")]
    
    HiPower = 12,

    /// <summary>Requires a medium power slot.</summary>
    [Description("Requires a medium power slot.")]
    
    MedPower = 13,

    /// <summary>this is the online effect</summary>
    [Description("this is the online effect")]
    
    Online = 16,

    /// <summary>mining of ore</summary>
    [Description("mining of ore")]
    
    Mining = 17,

    /// <summary>Boosts the shield of the target ship by draining the doers ships shield.</summary>
    [Description("Boosts the shield of the target ship by draining the doers ships shield.")]
    
    ShieldTransfer = 18,

    /// <summary>Increases maximum shield capacity.</summary>
    [Description("Increases maximum shield capacity.")]
    
    ShieldCapacityBonusOnline = 21,

    /// <summary>Enhances the maximum speed of the ship.</summary>
    [Description("Enhances the maximum speed of the ship.")]
    
    MaxVelocityBonus = 22,

    /// <summary>capacitorCapacityBonus</summary>
    
    CapacitorCapacityBonus = 25,

    /// <summary>structureRepair</summary>
    
    StructureRepair = 26,

    /// <summary>Repair damage to the ships armor.</summary>
    [Description("Repair damage to the ships armor.")]
    
    ArmorRepair = 27,

    /// <summary>modifyTargetSpeed</summary>
    
    ModifyTargetSpeed = 29,

    /// <summary>energyTransfer</summary>
    
    EnergyTransfer = 31,

    /// <summary>Steals power from the target.</summary>
    [Description("Steals power from the target.")]
    
    EnergyVampire = 32,

    /// <summary>projectileFired</summary>
    
    ProjectileFired = 34,

    /// <summary>Drains power from the target.</summary>
    [Description("Drains power from the target.")]
    
    EnergyDestabilization = 36,

    /// <summary>Triggering of an EMP wave being broadcast into space.</summary>
    [Description("Triggering of an EMP wave being broadcast into space.")]
    
    EmpWave = 38,

    /// <summary>Attempts to prevent the target from warping.</summary>
    [Description("Attempts to prevent the target from warping.")]
    
    WarpScramble = 39,

    /// <summary>launcherFitted</summary>
    
    LauncherFitted = 40,

    /// <summary>This is just a test. Ehmm. If your'e reading this in an error message, your ship probably doesn't have any turret slot left.</summary>
    [Description("This is just a test. Ehmm. If your\'e reading this in an error message, your ship " +
        "probably doesn\'t have any turret slot left.")]
    
    TurretFitted = 42,

    /// <summary>Scans the energy status, cargo and hardware of a given ship.</summary>
    [Description("Scans the energy status, cargo and hardware of a given ship.")]
    
    ShipScan = 46,

    /// <summary>Scan the cargo of a targeted ship.</summary>
    [Description("Scan the cargo of a targeted ship.")]
    
    CargoScan = 47,

    /// <summary>Consumes power booster charges to increase the available power in the capacitor.</summary>
    [Description("Consumes power booster charges to increase the available power in the capacitor.")]
    
    PowerBooster = 48,

    /// <summary>modifyShieldRechargeRate</summary>
    
    ModifyShieldRechargeRate = 50,

    /// <summary>modifyPowerRechargeRate</summary>
    
    ModifyPowerRechargeRate = 51,

    /// <summary>ecmBurst</summary>
    
    EcmBurst = 53,

    /// <summary>Targets an object without letting it know.</summary>
    [Description("Targets an object without letting it know.")]
    
    TargetPassively = 54,

    /// <summary>Target all hostile ships within range (if electronics can handle it).</summary>
    [Description("Target all hostile ships within range (if electronics can handle it).")]
    
    TargetHostiles = 55,

    /// <summary>powerOutputMultiply</summary>
    
    PowerOutputMultiply = 56,

    /// <summary>shieldCapacityMultiply</summary>
    
    ShieldCapacityMultiply = 57,

    /// <summary>capacitorCapacityMultiply</summary>
    
    CapacitorCapacityMultiply = 58,

    /// <summary>cargoCapacityMultiply</summary>
    
    CargoCapacityMultiply = 59,

    /// <summary>structureHPMultiply</summary>
    
    StructureHpMultiply = 60,

    /// <summary>agilityBonus</summary>
    
    AgilityBonus = 61,

    /// <summary>maxPassengersBonus</summary>
    
    MaxPassengersBonus = 62,

    /// <summary>armorHPMultiply</summary>
    
    ArmorHpMultiply = 63,

    /// <summary>Mining of ore.</summary>
    [Description("Mining of ore.")]
    
    MiningLaser = 67,

    /// <summary>Scale the agility of a ship.</summary>
    [Description("Scale the agility of a ship.")]
    
    AgilityMultiply = 70,

    /// <summary>repairCostMultiply</summary>
    
    RepairCostMultiply = 73,

    /// <summary>Scanning an asteroid to determine any helpful information.</summary>
    [Description("Scanning an asteroid to determine any helpful information.")]
    
    SurveyScan = 81,

    /// <summary>Modify the maximum number of members a character is capable of managing in a corporation.</summary>
    [Description("Modify the maximum number of members a character is capable of managing in a corp" +
        "oration.")]
    
    CorporationMemberLimitBonus = 82,

    /// <summary>Scales amount of CPU used by module(s).</summary>
    [Description("Scales amount of CPU used by module(s).")]
    
    CpuUsageMultiply = 87,

    /// <summary>Scales the mining duration of a mining laser module.</summary>
    [Description("Scales the mining duration of a mining laser module.")]
    
    MiningDurationMultiply = 88,

    /// <summary>Scale the projectile weapon firing speed.</summary>
    [Description("Scale the projectile weapon firing speed.")]
    
    ProjectileWeaponSpeedMultiply = 89,

    /// <summary>Scales the damage done by all fitted energy weapons.</summary>
    [Description("Scales the damage done by all fitted energy weapons.")]
    
    EnergyWeaponDamageMultiply = 91,

    /// <summary>Scales the damage done by all fitted projectile weapons.</summary>
    [Description("Scales the damage done by all fitted projectile weapons.")]
    
    ProjectileWeaponDamageMultiply = 92,

    /// <summary>Scales the damage done by all fitted hybrid weapons.</summary>
    [Description("Scales the damage done by all fitted hybrid weapons.")]
    
    HybridWeaponDamageMultiply = 93,

    /// <summary>Scales the rate of fire of all fitted energy weapons.</summary>
    [Description("Scales the rate of fire of all fitted energy weapons.")]
    
    EnergyWeaponSpeedMultiply = 95,

    /// <summary>Scales the rate of fire of all fitted hybrid weapons.</summary>
    [Description("Scales the rate of fire of all fitted hybrid weapons.")]
    
    HybridWeaponSpeedMultiply = 96,

    /// <summary>Scale the accuracy of all fitted turret weapons.</summary>
    [Description("Scale the accuracy of all fitted turret weapons.")]
    
    TurretWeaponAccuracyMultiply = 97,

    /// <summary>Scales the accuracy of all fitted hybrid weapons.</summary>
    [Description("Scales the accuracy of all fitted hybrid weapons.")]
    
    HybridWeaponAccuracyMultiply = 100,

    /// <summary>The ammunition loaded into this item defines its operation.</summary>
    [Description("The ammunition loaded into this item defines its operation.")]
    
    UseMissiles = 101,

    /// <summary>Drops a mine in space.</summary>
    [Description("Drops a mine in space.")]
    
    MineLaying = 102,

    /// <summary>Drops a defender missile in space to go do its thing.</summary>
    [Description("Drops a defender missile in space to go do its thing.")]
    
    DefenderMissileLaunching = 103,

    /// <summary>Launches an FOF missile.  Auto targets at someone hostile to you.</summary>
    [Description("Launches an FOF missile.  Auto targets at someone hostile to you.")]
    
    FofMissileLaunching = 104,

    /// <summary>shieldResonanceMultiplyOnline</summary>
    
    ShieldResonanceMultiplyOnline = 105,

    /// <summary>Scales the amount mined by all fitted mining lasers.</summary>
    [Description("Scales the amount mined by all fitted mining lasers.")]
    
    MiningAmountMultiply = 106,

    /// <summary>Increases the damage scaling done to missiles damage for missiles launched by the character.</summary>
    [Description("Increases the damage scaling done to missiles damage for missiles launched by the" +
        " character.")]
    
    CharacterMissileDamageMultiply = 107,

    /// <summary>Scales the capacitor need for all the fitted turret weapons.</summary>
    [Description("Scales the capacitor need for all the fitted turret weapons.")]
    
    TurretWeaponCapacitorNeedMultiply = 109,

    /// <summary>Modifies the aptitude the character has for researching blueprints by a given percentage.</summary>
    [Description("Modifies the aptitude the character has for researching blueprints by a given per" +
        "centage.")]
    
    CharacterBlueprintResearchTimeBonus = 110,

    /// <summary>Modifies the aptitude the character has for manufacturing from blueprints by a given percentage.</summary>
    [Description("Modifies the aptitude the character has for manufacturing from blueprints by a gi" +
        "ven percentage.")]
    
    CharacterBlueprintManufactureTimeBonus = 111,

    /// <summary>Modifies the speed at which skills with charisma as their primary attribute are trained.</summary>
    [Description("Modifies the speed at which skills with charisma as their primary attribute are t" +
        "rained.")]
    
    CharacterCharismaSkillTrainingTimeBonus = 112,

    /// <summary>Modifies the speed at which skills with intelligence as their primary attribute are trained.</summary>
    [Description("Modifies the speed at which skills with intelligence as their primary attribute a" +
        "re trained.")]
    
    CharacterIntelligenceSkillTrainingTimeBonus = 113,

    /// <summary>Modifies the speed at which skills with memory as their primary attribute are trained.</summary>
    [Description("Modifies the speed at which skills with memory as their primary attribute are tra" +
        "ined.")]
    
    CharacterMemorySkillTrainingTimeBonus = 114,

    /// <summary>Modifies the speed at which skills with perception as their primary attribute are trained.</summary>
    [Description("Modifies the speed at which skills with perception as their primary attribute are" +
        " trained.")]
    
    CharacterPerceptionSkillTrainingTimeBonus = 115,

    /// <summary>Modifies the speed at which skills with willpower as their primary attribute are trained.</summary>
    [Description("Modifies the speed at which skills with willpower as their primary attribute are " +
        "trained.")]
    
    CharacterWillpowerSkillTrainingTimeBonus = 116,
  }
}
