// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the Flag class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the Flag class.")]
  public enum FlagId : short
  {

    /// <summary>None</summary>
    [Description("None")]
    [LongDescription("None")]
    None = 0,

    /// <summary>Wallet</summary>
    [Description("Wallet")]
    [LongDescription("Wallet")]
    Wallet = 1,

    /// <summary>Factory</summary>
    [Description("Factory")]
    [LongDescription("Factory")]
    Factory = 2,

    /// <summary>Wardrobe</summary>
    [Description("Wardrobe")]
    [LongDescription("Wardrobe")]
    Wardrobe = 3,

    /// <summary>Hangar</summary>
    [Description("Hangar")]
    [LongDescription("Hangar")]
    Hangar = 4,

    /// <summary>Cargo</summary>
    [Description("Cargo")]
    [LongDescription("Cargo")]
    Cargo = 5,

    /// <summary>Briefcase</summary>
    [Description("Briefcase")]
    [LongDescription("Briefcase")]
    Briefcase = 6,

    /// <summary>Skill</summary>
    [Description("Skill")]
    [LongDescription("Skill")]
    Skill = 7,

    /// <summary>Reward</summary>
    [Description("Reward")]
    [LongDescription("Reward")]
    Reward = 8,

    /// <summary>Character in station connected</summary>
    [Description("Connected")]
    [LongDescription("Character in station connected")]
    Connected = 9,

    /// <summary>Character in station offline</summary>
    [Description("Disconnected")]
    [LongDescription("Character in station offline")]
    Disconnected = 10,

    /// <summary>Low power slot 1</summary>
    [Description("LoSlot0")]
    [LongDescription("Low power slot 1")]
    LoSlot0 = 11,

    /// <summary>Low power slot 2</summary>
    [Description("LoSlot1")]
    [LongDescription("Low power slot 2")]
    LoSlot1 = 12,

    /// <summary>Low power slot 3</summary>
    [Description("LoSlot2")]
    [LongDescription("Low power slot 3")]
    LoSlot2 = 13,

    /// <summary>Low power slot 4</summary>
    [Description("LoSlot3")]
    [LongDescription("Low power slot 4")]
    LoSlot3 = 14,

    /// <summary>Low power slot 5</summary>
    [Description("LoSlot4")]
    [LongDescription("Low power slot 5")]
    LoSlot4 = 15,

    /// <summary>Low power slot 6</summary>
    [Description("LoSlot5")]
    [LongDescription("Low power slot 6")]
    LoSlot5 = 16,

    /// <summary>Low power slot 7</summary>
    [Description("LoSlot6")]
    [LongDescription("Low power slot 7")]
    LoSlot6 = 17,

    /// <summary>Low power slot 8</summary>
    [Description("LoSlot7")]
    [LongDescription("Low power slot 8")]
    LoSlot7 = 18,

    /// <summary>Medium power slot 1</summary>
    [Description("MedSlot0")]
    [LongDescription("Medium power slot 1")]
    MedSlot0 = 19,

    /// <summary>Medium power slot 2</summary>
    [Description("MedSlot1")]
    [LongDescription("Medium power slot 2")]
    MedSlot1 = 20,

    /// <summary>Medium power slot 3</summary>
    [Description("MedSlot2")]
    [LongDescription("Medium power slot 3")]
    MedSlot2 = 21,

    /// <summary>Medium power slot 4</summary>
    [Description("MedSlot3")]
    [LongDescription("Medium power slot 4")]
    MedSlot3 = 22,

    /// <summary>Medium power slot 5</summary>
    [Description("MedSlot4")]
    [LongDescription("Medium power slot 5")]
    MedSlot4 = 23,

    /// <summary>Medium power slot 6</summary>
    [Description("MedSlot5")]
    [LongDescription("Medium power slot 6")]
    MedSlot5 = 24,

    /// <summary>Medium power slot 7</summary>
    [Description("MedSlot6")]
    [LongDescription("Medium power slot 7")]
    MedSlot6 = 25,

    /// <summary>Medium power slot 8</summary>
    [Description("MedSlot7")]
    [LongDescription("Medium power slot 8")]
    MedSlot7 = 26,

    /// <summary>High power slot 1</summary>
    [Description("HiSlot0")]
    [LongDescription("High power slot 1")]
    HiSlot0 = 27,

    /// <summary>High power slot 2</summary>
    [Description("HiSlot1")]
    [LongDescription("High power slot 2")]
    HiSlot1 = 28,

    /// <summary>High power slot 3</summary>
    [Description("HiSlot2")]
    [LongDescription("High power slot 3")]
    HiSlot2 = 29,

    /// <summary>High power slot 4</summary>
    [Description("HiSlot3")]
    [LongDescription("High power slot 4")]
    HiSlot3 = 30,

    /// <summary>High power slot 5</summary>
    [Description("HiSlot4")]
    [LongDescription("High power slot 5")]
    HiSlot4 = 31,

    /// <summary>High power slot 6</summary>
    [Description("HiSlot5")]
    [LongDescription("High power slot 6")]
    HiSlot5 = 32,

    /// <summary>High power slot 7</summary>
    [Description("HiSlot6")]
    [LongDescription("High power slot 7")]
    HiSlot6 = 33,

    /// <summary>High power slot 8</summary>
    [Description("HiSlot7")]
    [LongDescription("High power slot 8")]
    HiSlot7 = 34,

    /// <summary>Fixed Slot</summary>
    [Description("Fixed Slot")]
    [LongDescription("Fixed Slot")]
    FixedSlot = 35,

    /// <summary>Promenade Slot 1</summary>
    [Description("PromenadeSlot1")]
    [LongDescription("Promenade Slot 1")]
    PromenadeSlot1 = 40,

    /// <summary>Promenade Slot 2</summary>
    [Description("PromenadeSlot2")]
    [LongDescription("Promenade Slot 2")]
    PromenadeSlot2 = 41,

    /// <summary>Promenade Slot 3</summary>
    [Description("PromenadeSlot3")]
    [LongDescription("Promenade Slot 3")]
    PromenadeSlot3 = 42,

    /// <summary>Promenade Slot 4</summary>
    [Description("PromenadeSlot4")]
    [LongDescription("Promenade Slot 4")]
    PromenadeSlot4 = 43,

    /// <summary>Promenade Slot 5</summary>
    [Description("PromenadeSlot5")]
    [LongDescription("Promenade Slot 5")]
    PromenadeSlot5 = 44,

    /// <summary>Promenade Slot 6</summary>
    [Description("PromenadeSlot6")]
    [LongDescription("Promenade Slot 6")]
    PromenadeSlot6 = 45,

    /// <summary>Promenade Slot 7</summary>
    [Description("PromenadeSlot7")]
    [LongDescription("Promenade Slot 7")]
    PromenadeSlot7 = 46,

    /// <summary>Promenade Slot 8</summary>
    [Description("PromenadeSlot8")]
    [LongDescription("Promenade Slot 8")]
    PromenadeSlot8 = 47,

    /// <summary>Promenade Slot 9</summary>
    [Description("PromenadeSlot9")]
    [LongDescription("Promenade Slot 9")]
    PromenadeSlot9 = 48,

    /// <summary>Promenade Slot 10</summary>
    [Description("PromenadeSlot10")]
    [LongDescription("Promenade Slot 10")]
    PromenadeSlot10 = 49,

    /// <summary>Promenade Slot 11</summary>
    [Description("PromenadeSlot11")]
    [LongDescription("Promenade Slot 11")]
    PromenadeSlot11 = 50,

    /// <summary>Promenade Slot 12</summary>
    [Description("PromenadeSlot12")]
    [LongDescription("Promenade Slot 12")]
    PromenadeSlot12 = 51,

    /// <summary>Promenade Slot 13</summary>
    [Description("PromenadeSlot13")]
    [LongDescription("Promenade Slot 13")]
    PromenadeSlot13 = 52,

    /// <summary>Promenade Slot 14</summary>
    [Description("PromenadeSlot14")]
    [LongDescription("Promenade Slot 14")]
    PromenadeSlot14 = 53,

    /// <summary>Promenade Slot 15</summary>
    [Description("PromenadeSlot15")]
    [LongDescription("Promenade Slot 15")]
    PromenadeSlot15 = 54,

    /// <summary>Promenade Slot 16</summary>
    [Description("PromenadeSlot16")]
    [LongDescription("Promenade Slot 16")]
    PromenadeSlot16 = 55,

    /// <summary>Capsule</summary>
    [Description("Capsule")]
    [LongDescription("Capsule")]
    Capsule = 56,

    /// <summary>Pilot</summary>
    [Description("Pilot")]
    [LongDescription("Pilot")]
    Pilot = 57,

    /// <summary>Passenger</summary>
    [Description("Passenger")]
    [LongDescription("Passenger")]
    Passenger = 58,

    /// <summary>Boarding gate</summary>
    [Description("Boarding Gate")]
    [LongDescription("Boarding gate")]
    BoardingGate = 59,

    /// <summary>Crew</summary>
    [Description("Crew")]
    [LongDescription("Crew")]
    Crew = 60,

    /// <summary>Skill in training</summary>
    [Description("Skill In Training")]
    [LongDescription("Skill in training")]
    SkillInTraining = 61,

    /// <summary>Corporation Market Deliveries / Returns</summary>
    [Description("CorpMarket")]
    [LongDescription("Corporation Market Deliveries / Returns")]
    CorpMarket = 62,

    /// <summary>Locked item, can not be moved unless unlocked</summary>
    [Description("Locked")]
    [LongDescription("Locked item, can not be moved unless unlocked")]
    Locked = 63,

    /// <summary>Unlocked item, can be moved</summary>
    [Description("Unlocked")]
    [LongDescription("Unlocked item, can be moved")]
    Unlocked = 64,

    /// <summary>Office slot 1</summary>
    [Description("Office Slot 1")]
    [LongDescription("Office slot 1")]
    OfficeSlot1 = 70,

    /// <summary>Office slot 2</summary>
    [Description("Office Slot 2")]
    [LongDescription("Office slot 2")]
    OfficeSlot2 = 71,

    /// <summary>Office slot 3</summary>
    [Description("Office Slot 3")]
    [LongDescription("Office slot 3")]
    OfficeSlot3 = 72,

    /// <summary>Office slot 4</summary>
    [Description("Office Slot 4")]
    [LongDescription("Office slot 4")]
    OfficeSlot4 = 73,

    /// <summary>Office slot 5</summary>
    [Description("Office Slot 5")]
    [LongDescription("Office slot 5")]
    OfficeSlot5 = 74,

    /// <summary>Office slot 6</summary>
    [Description("Office Slot 6")]
    [LongDescription("Office slot 6")]
    OfficeSlot6 = 75,

    /// <summary>Office slot 7</summary>
    [Description("Office Slot 7")]
    [LongDescription("Office slot 7")]
    OfficeSlot7 = 76,

    /// <summary>Office slot 8</summary>
    [Description("Office Slot 8")]
    [LongDescription("Office slot 8")]
    OfficeSlot8 = 77,

    /// <summary>Office slot 9</summary>
    [Description("Office Slot 9")]
    [LongDescription("Office slot 9")]
    OfficeSlot9 = 78,

    /// <summary>Office slot 10</summary>
    [Description("Office Slot 10")]
    [LongDescription("Office slot 10")]
    OfficeSlot10 = 79,

    /// <summary>Office slot 11</summary>
    [Description("Office Slot 11")]
    [LongDescription("Office slot 11")]
    OfficeSlot11 = 80,

    /// <summary>Office slot 12</summary>
    [Description("Office Slot 12")]
    [LongDescription("Office slot 12")]
    OfficeSlot12 = 81,

    /// <summary>Office slot 13</summary>
    [Description("Office Slot 13")]
    [LongDescription("Office slot 13")]
    OfficeSlot13 = 82,

    /// <summary>Office slot 14</summary>
    [Description("Office Slot 14")]
    [LongDescription("Office slot 14")]
    OfficeSlot14 = 83,

    /// <summary>Office slot 15</summary>
    [Description("Office Slot 15")]
    [LongDescription("Office slot 15")]
    OfficeSlot15 = 84,

    /// <summary>Office slot 16</summary>
    [Description("Office Slot 16")]
    [LongDescription("Office slot 16")]
    OfficeSlot16 = 85,

    /// <summary>Bonus</summary>
    [Description("Bonus")]
    [LongDescription("Bonus")]
    Bonus = 86,

    /// <summary>Drone Bay</summary>
    [Description("DroneBay")]
    [LongDescription("Drone Bay")]
    DroneBay = 87,

    /// <summary>Booster</summary>
    [Description("Booster")]
    [LongDescription("Booster")]
    Booster = 88,

    /// <summary>Implant</summary>
    [Description("Implant")]
    [LongDescription("Implant")]
    Implant = 89,

    /// <summary>Ship Hangar</summary>
    [Description("ShipHangar")]
    [LongDescription("Ship Hangar")]
    ShipHangar = 90,

    /// <summary>Ship Offline</summary>
    [Description("ShipOffline")]
    [LongDescription("Ship Offline")]
    ShipOffline = 91,

    /// <summary>Rig power slot 1</summary>
    [Description("RigSlot0")]
    [LongDescription("Rig power slot 1")]
    RigSlot0 = 92,

    /// <summary>Rig power slot 2</summary>
    [Description("RigSlot1")]
    [LongDescription("Rig power slot 2")]
    RigSlot1 = 93,

    /// <summary>Rig power slot 3</summary>
    [Description("RigSlot2")]
    [LongDescription("Rig power slot 3")]
    RigSlot2 = 94,

    /// <summary>Rig power slot 4</summary>
    [Description("RigSlot3")]
    [LongDescription("Rig power slot 4")]
    RigSlot3 = 95,

    /// <summary>Rig power slot 5</summary>
    [Description("RigSlot4")]
    [LongDescription("Rig power slot 5")]
    RigSlot4 = 96,

    /// <summary>Rig power slot 6</summary>
    [Description("RigSlot5")]
    [LongDescription("Rig power slot 6")]
    RigSlot5 = 97,

    /// <summary>Rig power slot 7</summary>
    [Description("RigSlot6")]
    [LongDescription("Rig power slot 7")]
    RigSlot6 = 98,

    /// <summary>Rig power slot 8</summary>
    [Description("RigSlot7")]
    [LongDescription("Rig power slot 8")]
    RigSlot7 = 99,

    /// <summary>Factory Background Operation</summary>
    [Description("Factory Operation")]
    [LongDescription("Factory Background Operation")]
    FactoryOperation = 100,

    /// <summary>Corp Security Access Group 2</summary>
    [Description("CorpSAG2")]
    [LongDescription("Corp Security Access Group 2")]
    CorpSag2 = 116,

    /// <summary>Corp Security Access Group 3</summary>
    [Description("CorpSAG3")]
    [LongDescription("Corp Security Access Group 3")]
    CorpSag3 = 117,

    /// <summary>Corp Security Access Group 4</summary>
    [Description("CorpSAG4")]
    [LongDescription("Corp Security Access Group 4")]
    CorpSag4 = 118,

    /// <summary>Corp Security Access Group 5</summary>
    [Description("CorpSAG5")]
    [LongDescription("Corp Security Access Group 5")]
    CorpSag5 = 119,

    /// <summary>Corp Security Access Group 6</summary>
    [Description("CorpSAG6")]
    [LongDescription("Corp Security Access Group 6")]
    CorpSag6 = 120,

    /// <summary>Corp Security Access Group 7</summary>
    [Description("CorpSAG7")]
    [LongDescription("Corp Security Access Group 7")]
    CorpSag7 = 121,

    /// <summary>Secondary Storage</summary>
    [Description("SecondaryStorage")]
    [LongDescription("Secondary Storage")]
    SecondaryStorage = 122,

    /// <summary>Captains Quarters</summary>
    [Description("CaptainsQuarters")]
    [LongDescription("Captains Quarters")]
    CaptainsQuarters = 123,

    /// <summary>Wis Promenade</summary>
    [Description("Wis Promenade")]
    [LongDescription("Wis Promenade")]
    WisPromenade = 124,

    /// <summary>Sub system slot 0</summary>
    [Description("SubSystem0")]
    [LongDescription("Sub system slot 0")]
    SubSystem0 = 125,

    /// <summary>Sub system slot 1</summary>
    [Description("SubSystem1")]
    [LongDescription("Sub system slot 1")]
    SubSystem1 = 126,

    /// <summary>Sub system slot 2</summary>
    [Description("SubSystem2")]
    [LongDescription("Sub system slot 2")]
    SubSystem2 = 127,

    /// <summary>Sub system slot 3</summary>
    [Description("SubSystem3")]
    [LongDescription("Sub system slot 3")]
    SubSystem3 = 128,

    /// <summary>Sub system slot 4</summary>
    [Description("SubSystem4")]
    [LongDescription("Sub system slot 4")]
    SubSystem4 = 129,

    /// <summary>Sub system slot 5</summary>
    [Description("SubSystem5")]
    [LongDescription("Sub system slot 5")]
    SubSystem5 = 130,

    /// <summary>Sub system slot 6</summary>
    [Description("SubSystem6")]
    [LongDescription("Sub system slot 6")]
    SubSystem6 = 131,

    /// <summary>Sub system slot 7</summary>
    [Description("SubSystem7")]
    [LongDescription("Sub system slot 7")]
    SubSystem7 = 132,

    /// <summary>Specialized Fuel Bay</summary>
    [Description("SpecializedFuelBay")]
    [LongDescription("Specialized Fuel Bay")]
    SpecializedFuelBay = 133,

    /// <summary>Specialized Ore Hold</summary>
    [Description("SpecializedOreHold")]
    [LongDescription("Specialized Ore Hold")]
    SpecializedOreHold = 134,

    /// <summary>Specialized Gas Hold</summary>
    [Description("SpecializedGasHold")]
    [LongDescription("Specialized Gas Hold")]
    SpecializedGasHold = 135,

    /// <summary>Specialized Mineral Hold</summary>
    [Description("SpecializedMineralHold")]
    [LongDescription("Specialized Mineral Hold")]
    SpecializedMineralHold = 136,

    /// <summary>Specialized Salvage Hold</summary>
    [Description("SpecializedSalvageHold")]
    [LongDescription("Specialized Salvage Hold")]
    SpecializedSalvageHold = 137,

    /// <summary>Specialized Ship Hold</summary>
    [Description("SpecializedShipHold")]
    [LongDescription("Specialized Ship Hold")]
    SpecializedShipHold = 138,

    /// <summary>Specialized Small Ship Hold</summary>
    [Description("SpecializedSmallShipHold")]
    [LongDescription("Specialized Small Ship Hold")]
    SpecializedSmallShipHold = 139,

    /// <summary>Specialized Medium Ship Hold</summary>
    [Description("SpecializedMediumShipHold")]
    [LongDescription("Specialized Medium Ship Hold")]
    SpecializedMediumShipHold = 140,

    /// <summary>Specialized Large Ship Hold</summary>
    [Description("SpecializedLargeShipHold")]
    [LongDescription("Specialized Large Ship Hold")]
    SpecializedLargeShipHold = 141,

    /// <summary>Specialized Industrial Ship Hold</summary>
    [Description("SpecializedIndustrialShipHold")]
    [LongDescription("Specialized Industrial Ship Hold")]
    SpecializedIndustrialShipHold = 142,

    /// <summary>Specialized Ammo Hold</summary>
    [Description("SpecializedAmmoHold")]
    [LongDescription("Specialized Ammo Hold")]
    SpecializedAmmoHold = 143,

    /// <summary>StructureActive</summary>
    [Description("StructureActive")]
    [LongDescription("StructureActive")]
    StructureActive = 144,

    /// <summary>StructureInactive</summary>
    [Description("StructureInactive")]
    [LongDescription("StructureInactive")]
    StructureInactive = 145,

    /// <summary>This item was put into a junkyard through reprocession.</summary>
    [Description("JunkyardReprocessed")]
    [LongDescription("This item was put into a junkyard through reprocession.")]
    JunkyardReprocessed = 146,

    /// <summary>This item was put into a junkyard through being trashed by its owner.</summary>
    [Description("JunkyardTrashed")]
    [LongDescription("This item was put into a junkyard through being trashed by its owner.")]
    JunkyardTrashed = 147,

    /// <summary>Specialized Command Center Hold</summary>
    [Description("SpecializedCommandCenterHold")]
    [LongDescription("Specialized Command Center Hold")]
    SpecializedCommandCenterHold = 148,

    /// <summary>Specialized Planetary Commodities Hold</summary>
    [Description("SpecializedPlanetaryCommoditiesHold")]
    [LongDescription("Specialized Planetary Commodities Hold")]
    SpecializedPlanetaryCommoditiesHold = 149,

    /// <summary>Planet Surface</summary>
    [Description("PlanetSurface")]
    [LongDescription("Planet Surface")]
    PlanetSurface = 150,

    /// <summary>Specialized Material Bay</summary>
    [Description("SpecializedMaterialBay")]
    [LongDescription("Specialized Material Bay")]
    SpecializedMaterialBay = 151,

    /// <summary>Dust Character Databank</summary>
    [Description("DustCharacterDatabank")]
    [LongDescription("Dust Character Databank")]
    DustCharacterDatabank = 152,

    /// <summary>Dust Character Battle</summary>
    [Description("DustCharacterBattle")]
    [LongDescription("Dust Character Battle")]
    DustCharacterBattle = 153,

    /// <summary>Quafe Bay</summary>
    [Description("QuafeBay")]
    [LongDescription("Quafe Bay")]
    QuafeBay = 154,

    /// <summary>Fleet Hangar</summary>
    [Description("FleetHangar")]
    [LongDescription("Fleet Hangar")]
    FleetHangar = 155,
  }
}
