// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve {


  /// <summary>Contains the ID values associated with the Group class.</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Eve.Meta", "1.76.447.42681")]
  [System.ComponentModel.DescriptionAttribute("Contains the ID values associated with the Group class.")]
  public enum GroupId : int {

    
    System = 0,

    
    Character = 1,

    
    Corporation = 2,

    
    Region = 3,

    
    Constellation = 4,

    
    SolarSystem = 5,

    
    Sun = 6,

    
    Planet = 7,

    
    Moon = 8,

    
    AsteroidBelt = 9,

    
    Stargate = 10,

    
    AsteroidOld = 11,

    
    CargoContainer = 12,

    
    Ring = 13,

    /// <summary>Corpse of human. Can be sold for clone production.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Corpse of human. Can be sold for clone production.")]
    Biomass = 14,

    
    Station = 15,

    
    StationServices = 16,

    
    Money = 17,

    
    Mineral = 18,

    
    Faction = 19,

    /// <summary>Drug</summary>
    
    [System.ComponentModel.DescriptionAttribute("Drug")]
    Drug = 20,

    
    Clone = 23,

    
    Voucher = 24,

    
    Frigate = 25,

    
    Cruiser = 26,

    
    Battleship = 27,

    
    Industrial = 28,

    
    Capsule = 29,

    /// <summary>The collective name for these behemoths is Titans, the largest spacefaring vessels ever constructed. The sheer cost in resources, manpower and time, as well as the necessary technological knowledge, makes construction of a Titan-class vessel a venture only empires can usually fathom. Some of these mammoth vessels have taken decades to assemble. Many are over a century old themselves, and the three mammoth Jovian motherships, the first Titans, have origins pre-dating modern space travel. They are</summary>
    
    [System.ComponentModel.DescriptionAttribute(@"The collective name for these behemoths is Titans, the largest spacefaring vessels ever constructed. The sheer cost in resources, manpower and time, as well as the necessary technological knowledge, makes construction of a Titan-class vessel a venture only empires can usually fathom. Some of these mammoth vessels have taken decades to assemble. Many are over a century old themselves, and the three mammoth Jovian motherships, the first Titans, have origins pre-dating modern space travel. They are")]
    Titan = 30,

    
    Shuttle = 31,

    
    Alliance = 32,

    
    ShieldExtender = 38,

    
    ShieldRecharger = 39,

    
    ShieldBooster = 40,

    
    ShieldTransporter = 41,

    
    CapacitorRecharger = 43,

    
    PropulsionModule = 46,

    
    CargoScanner = 47,

    
    ShipScanner = 48,

    
    SurveyScanner = 49,

    
    WarpScrambler = 52,

    
    EnergyWeapon = 53,

    /// <summary>Mining Laser</summary>
    
    [System.ComponentModel.DescriptionAttribute("Mining Laser")]
    MiningLaser = 54,

    
    ProjectileWeapon = 55,

    
    MissileLauncher = 56,

    /// <summary>These module usually act on the power and/or capacitor requirements of modules.</summary>
    
    [System.ComponentModel.DescriptionAttribute("These module usually act on the power and/or capacitor requirements of modules.")]
    ShieldPowerRelay = 57,

    /// <summary>Uses gyroscopes and inertial dampeners to reduce recoil and stabilize the weapon while firing</summary>
    
    [System.ComponentModel.DescriptionAttribute("Uses gyroscopes and inertial dampeners to reduce recoil and stabilize the weapon " +
        "while firing")]
    Gyrostabilizer = 59,

    /// <summary>Reinforcement are modules that increase the "armorHP" of some module group or specific module type. It typically only defines a passive effect.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Reinforcement are modules that increase the \"armorHP\" of some module group or spe" +
        "cific module type. It typically only defines a passive effect.")]
    DamageControl = 60,

    /// <summary>Supplement the ships built-in power battery and provides defense against enemy energy leech and energy neutralizer effects.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Supplement the ships built-in power battery and provides defense against enemy en" +
        "ergy leech and energy neutralizer effects.")]
    CapacitorBattery = 61,

    
    ArmorRepairUnit = 62,

    
    HullRepairUnit = 63,

    /// <summary>Reduces max speed of a target ship.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Reduces max speed of a target ship.")]
    StasisWeb = 65,

    /// <summary>Transfers some of our energy to the target ships.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Transfers some of our energy to the target ships.")]
    EnergyTransferArray = 67,

    
    EnergyVampire = 68,

    /// <summary>Target ship loses power.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Target ship loses power.")]
    EnergyDestabilizer = 71,

    /// <summary>Smart Bomb</summary>
    
    [System.ComponentModel.DescriptionAttribute("Smart Bomb")]
    SmartBomb = 72,

    /// <summary>Hybrid</summary>
    
    [System.ComponentModel.DescriptionAttribute("Hybrid")]
    HybridWeapon = 74,

    /// <summary>In times of danger and need, being able to boost your power supply can save your skin.  Don't leave home without one of these.  And don't forget to feed it.</summary>
    
    [System.ComponentModel.DescriptionAttribute("In times of danger and need, being able to boost your power supply can save your " +
        "skin.  Don\'t leave home without one of these.  And don\'t forget to feed it.")]
    CapacitorBooster = 76,

    /// <summary>Increases the resistance of the shield to damages of specified types.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Increases the resistance of the shield to damages of specified types.")]
    ShieldHardener = 77,

    
    ReinforcedBulkhead = 78,

    /// <summary>Clears all targets on all ships(excluding self) wihin range.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Clears all targets on all ships(excluding self) wihin range.")]
    EcmBurst = 80,

    /// <summary>Targets ship quietly (as in does not alert other ship to the fact rhat its been targeted).</summary>
    
    [System.ComponentModel.DescriptionAttribute("Targets ship quietly (as in does not alert other ship to the fact rhat its been t" +
        "argeted).")]
    PassiveTargetingSystem = 82,

    /// <summary>Projectile Ammo</summary>
    
    [System.ComponentModel.DescriptionAttribute("Projectile Ammo")]
    ProjectileAmmo = 83,

    
    Missile = 84,

    
    HybridCharge = 85,

    /// <summary>the frequency of Laser weapon</summary>
    
    [System.ComponentModel.DescriptionAttribute("the frequency of Laser weapon")]
    FrequencyCrystal = 86,

    /// <summary>Capacitor Booster Charge</summary>
    
    [System.ComponentModel.DescriptionAttribute("Capacitor Booster Charge")]
    CapacitorBoosterCharge = 87,

    
    LightDefenderMissile = 88,

    /// <summary>Torrpedo</summary>
    
    [System.ComponentModel.DescriptionAttribute("Torrpedo")]
    Torpedo = 89,

    /// <summary>Remote triggered. Have no internal Thrust or Guidance. Are dropped at 80% of ship current speed</summary>
    
    [System.ComponentModel.DescriptionAttribute("Remote triggered. Have no internal Thrust or Guidance. Are dropped at 80% of ship" +
        " current speed")]
    Bomb = 90,

    
    Mine = 92,

    
    Trading = 94,

    
    TradeSession = 95,

    /// <summary>Targets all hostile ships within range.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Targets all hostile ships within range.")]
    AutomatedTargetingSystem = 96,

    /// <summary>ProximityDrone</summary>
    
    [System.ComponentModel.DescriptionAttribute("ProximityDrone")]
    ProximityDrone = 97,

    
    ArmorCoating = 98,

    /// <summary>Protecting the weak and upholding the law, these shining examples of fabrication maintain the peace.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Protecting the weak and upholding the law, these shining examples of fabrication " +
        "maintain the peace.")]
    SentryGun = 99,

    
    CombatDrone = 100,

    /// <summary>Mines.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Mines.")]
    MiningDrone = 101,

    
    CloneBlueprint = 104,

    
    FrigateBlueprint = 105,

    
    CruiserBlueprint = 106,

    
    BattleshipBlueprint = 107,

    
    IndustrialBlueprint = 108,

    
    CapsuleBlueprint = 109,

    
    TitanBlueprint = 110,

    
    ShuttleBlueprint = 111,

    
    ShieldExtenderBlueprint = 118,

    
    ShieldRechargerBlueprint = 119,

    
    ShieldBoosterBlueprint = 120,

    
    ShieldTransporterBlueprint = 121,

    
    CapacitorRechargerBlueprint = 123,

    
    PropulsionModuleBlueprint = 126,

    
    CargoScannerBlueprint = 127,

    
    ShipScannerBlueprint = 128,

    
    SurveyScannerBlueprint = 129,

    
    EcmBlueprint = 130,

    
    EccmBlueprint = 131,

    
    WarpScramblerBlueprint = 132,

    
    EnergyWeaponBlueprint = 133,

    
    MiningLaserBlueprint = 134,

    
    ProjectileWeaponBlueprint = 135,

    
    MissileLauncherBlueprint = 136,

    
    PowerManagerBlueprint = 137,

    
    FastLoaderBlueprint = 139,

    
    DamageControlBlueprint = 140,

    
    CapacitorBatteryBlueprint = 141,

    
    ArmorRepairUnitBlueprint = 142,

    
    HullRepairUnitBlueprint = 143,

    
    StasisWebBlueprint = 145,

    
    EnergyTransferArrayBlueprint = 147,

    
    EnergyVampireBlueprint = 148,

    
    EnergyDestabilizerBlueprint = 151,

    
    SmartBombBlueprint = 152,

    
    HybridWeaponBlueprint = 154,

    
    CapacitorBoosterBlueprint = 156,

    
    ShieldHardenerBlueprint = 157,

    
    HullModsBlueprint = 158,

    
    EcmBurstBlueprint = 160,

    
    PassiveTargetingSystemBlueprint = 161,

    
    AutomatedTargetingSystemBlueprint = 162,

    
    ArmorCoatingBlueprint = 163,

    
    ProjectileAmmoBlueprint = 165,

    
    MissileBlueprint = 166,

    
    HybridChargeBlueprint = 167,

    
    FrequencyCrystalBlueprint = 168,

    
    CapacitorBoosterChargeBlueprint = 169,

    
    DefenderMissileBlueprint = 170,

    
    BombBlueprint = 172,

    
    MineBlueprint = 174,

    
    ProximityDroneBlueprint = 175,

    
    CombatDroneBlueprint = 176,

    
    MiningDroneBlueprint = 177,

    
    DrugBlueprint = 178,

    /// <summary>Defends all within its observation range who get attacked.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Defends all within its observation range who get attacked.")]
    ProtectiveSentryGun = 180,

    /// <summary>Ho hum.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Ho hum.")]
    PoliceDrone = 182,

    
    PirateDrone = 185,

    /// <summary>Shipwrecks and stuff like that</summary>
    
    [System.ComponentModel.DescriptionAttribute("Shipwrecks and stuff like that")]
    Wreck = 186,

    /// <summary>Bonuses for the given bloodlines.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Bonuses for the given bloodlines.")]
    BloodlineBonus = 190,

    /// <summary>Physical Benefit</summary>
    
    [System.ComponentModel.DescriptionAttribute("Physical Benefit")]
    PhysicalBenefit = 191,

    /// <summary>Physical Handicap.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Physical Handicap.")]
    PhysicalHandicap = 192,

    /// <summary>Phobia handicap</summary>
    
    [System.ComponentModel.DescriptionAttribute("Phobia handicap")]
    PhobiaHandicap = 193,

    /// <summary>Social handicap.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Social handicap.")]
    SocialHandicap = 194,

    /// <summary>Bonuses for having various Amarr educations.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Bonuses for having various Amarr educations.")]
    AmarrEducation = 195,

    /// <summary>Bonuses for having various Caldari educations.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Bonuses for having various Caldari educations.")]
    CaldariEducation = 196,

    /// <summary>Bonuses for having a variety of Gallente educations.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Bonuses for having a variety of Gallente educations.")]
    GallenteEducation = 197,

    /// <summary>A variety of bonuses for having a Minmatar education.</summary>
    
    [System.ComponentModel.DescriptionAttribute("A variety of bonuses for having a Minmatar education.")]
    MinmatarEducation = 198,

    /// <summary>Bonus for taking a career or some sh1t.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Bonus for taking a career or some sh1t.")]
    CareerBonus = 199,

    /// <summary>Electronic Countermeasure</summary>
    
    [System.ComponentModel.DescriptionAttribute("Electronic Countermeasure")]
    Ecm = 201,

    
    Eccm = 202,

    /// <summary>An upgrade to the electronics capacilities of the ship 1.</summary>
    
    [System.ComponentModel.DescriptionAttribute("An upgrade to the electronics capacilities of the ship 1.")]
    SensorBackupArray = 203,

    
    HeatSink = 205,

    /// <summary>Electronic Warfare System 2</summary>
    
    [System.ComponentModel.DescriptionAttribute("Electronic Warfare System 2")]
    RemoteSensorDamper = 208,

    /// <summary>Tracking Link</summary>
    
    [System.ComponentModel.DescriptionAttribute("Tracking Link")]
    TrackingLink = 209,

    
    SignalAmplifier = 210,

    
    TrackingEnhancer = 211,

    /// <summary>Boosts the Range, Speed and Max targets of electronics module</summary>
    
    [System.ComponentModel.DescriptionAttribute("Boosts the Range, Speed and Max targets of electronics module")]
    SensorBooster = 212,

    /// <summary>On command adjust the effectiveness of the sensor functions of the electronics of the users ship.</summary>
    
    [System.ComponentModel.DescriptionAttribute("On command adjust the effectiveness of the sensor functions of the electronics of" +
        " the users ship.")]
    TrackingComputer = 213,

    
    HeatSinkBlueprint = 218,

    
    SensorBoosterBlueprint = 223,

    
    TrackingComputerBlueprint = 224,

    /// <summary>For limited distribution.  Speed up testing.</summary>
    
    [System.ComponentModel.DescriptionAttribute("For limited distribution.  Speed up testing.")]
    CheatModuleGroup = 225,

    
    LargeCollidableObject = 226,

    
    Cloud = 227,

    /// <summary>These are the rookie frigates, read: n00be ships yo!</summary>
    
    [System.ComponentModel.DescriptionAttribute("These are the rookie frigates, read: n00be ships yo!")]
    RookieShip = 237,

    
    Gunnery = 255,

    
    MissileLauncherOperation = 256,

    
    SpaceshipCommand = 257,

    
    Leadership = 258,

    
    CorporationManagement = 266,

    
    ObsoleteBooks = 267,

    
    Industry = 268,

    
    Mechanics = 269,

    
    Science = 270,

    
    Engineering = 271,

    
    Electronics = 272,

    
    Drones = 273,

    
    Trade = 274,

    
    Navigation = 275,

    
    Social = 278,

    
    LcoDrone = 279,

    
    General = 280,

    
    Frozen = 281,

    
    Radioactive = 282,

    
    Livestock = 283,

    
    Biohazard = 284,

    
    CpuEnhancer = 285,

    
    TutorialDrone = 286,

    /// <summary>These drones can be found by wrecks, mineral deposits and various other hang-outs for junk metal gone bad.</summary>
    
    [System.ComponentModel.DescriptionAttribute("These drones can be found by wrecks, mineral deposits and various other hang-outs" +
        " for junk metal gone bad.")]
    RogueDrone = 287,

    
    FactionDrone = 288,

    /// <summary>ECCM Projector </summary>
    
    [System.ComponentModel.DescriptionAttribute("ECCM Projector ")]
    ProjectedEccm = 289,

    /// <summary>Electronic Warfare System 2</summary>
    
    [System.ComponentModel.DescriptionAttribute("Electronic Warfare System 2")]
    RemoteSensorBooster = 290,

    
    TrackingDisruptor = 291,

    
    ShieldAmplifier = 295,

    
    ShieldAmplifierBlueprint = 296,

    
    Convoy = 297,

    
    ConvoyDrone = 298,

    /// <summary>Repair drones reapair the structure and armor of ships</summary>
    
    [System.ComponentModel.DescriptionAttribute("Repair drones reapair the structure and armor of ships")]
    RepairDrone = 299,

    
    Cyberimplant = 300,

    
    ConcordDrone = 301,

    
    MagneticFieldStabilizer = 302,

    
    Booster = 303,

    
    DnaMutator = 304,

    
    Comet = 305,

    
    SpawnContainer = 306,

    
    ConstructionPlatform = 307,

    
    CountermeasureLauncher = 308,

    
    Autopilot = 309,

    /// <summary>This is a group for Beacons. Beacons are fixed global objects with no functionality</summary>
    
    [System.ComponentModel.DescriptionAttribute("This is a group for Beacons. Beacons are fixed global objects with no functionali" +
        "ty")]
    Beacon = 310,

    
    RefiningArray = 311,

    
    PlanetaryCloud = 312,

    /// <summary>This group contains commodities that are drugs or 'boosters'.</summary>
    
    [System.ComponentModel.DescriptionAttribute("This group contains commodities that are drugs or \'boosters\'.")]
    Drugs = 313,

    /// <summary>Miscellaneos special mission items that should not be on the market and not available from random missions.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Miscellaneos special mission items that should not be on the market and not avail" +
        "able from random missions.")]
    Miscellaneous = 314,

    
    WarpCoreStabilizer = 315,

    
    GangCoordinator = 316,

    
    ComputerInterfaceNode = 317,

    /// <summary>Landmarks are used on the map for locations that are not physical objects neccesarily, such as important areas and regions, political borders and so on.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Landmarks are used on the map for locations that are not physical objects neccesa" +
        "rily, such as important areas and regions, political borders and so on.")]
    Landmark = 318,

    
    LargeCollidableStructure = 319,

    
    ShieldDisruptor = 321,

    
    Billboard = 323,

    /// <summary>Da Leet Frigates 
    ///</summary>
    
    [System.ComponentModel.DescriptionAttribute("Da Leet Frigates \r\n")]
    AssaultShip = 324,

    
    ArmorRepairProjector = 325,

    
    ArmorPlatingEnergized = 326,

    
    ArmorHardener = 328,

    
    ArmorReinforcer = 329,

    
    CloakingDevice = 330,

    /// <summary>Tools used in manufacturing and Research</summary>
    
    [System.ComponentModel.DescriptionAttribute("Tools used in manufacturing and Research")]
    Tool = 332,

    
    Datacores = 333,

    /// <summary>components for use i item construction</summary>
    
    [System.ComponentModel.DescriptionAttribute("components for use i item construction")]
    ConstructionComponents = 334,

    
    TemporaryCloud = 335,

    
    MobileSentryGun = 336,

    
    MissionDrone = 337,

    
    ShieldBoostAmplifier = 338,

    
    AuxiliaryPowerCore = 339,

    
    SecureCargoContainer = 340,

    
    SignatureScrambling = 341,

    
    AntiWarpScramblerBlueprint = 342,

    
    TrackingDisruptorBlueprint = 343,

    
    TrackingEnhancerBlueprint = 344,

    
    TrackingLinkBlueprint = 345,

    
    CoProcessorBlueprint = 346,

    
    SignalAmplifierBlueprint = 347,

    
    ArmorHardenerBlueprint = 348,

    
    ArmorReinforcerBlueprint = 349,

    
    ArmorRepairProjectorBlueprint = 350,

    
    AuxiliaryPowerCoreBlueprint = 352,

    
    QaModule = 353,

    /// <summary>Group for mineral compounds and alloys that can be refined into valuable minerals.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Group for mineral compounds and alloys that can be refined into valuable minerals" +
        ".")]
    Refinables = 355,

    
    ToolBlueprint = 356,

    
    DroneBayExpander = 357,

    
    HeavyAssaultShip = 358,

    
    ShieldBoostAmplifierBlueprint = 360,

    /// <summary>Self powered warp disruptors.  Do not require a control tower.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Self powered warp disruptors.  Do not require a control tower.")]
    MobileWarpDisruptor = 361,

    
    ShipMaintenanceArray = 363,

    
    MobileStorage = 364,

    
    ControlTower = 365,

    
    WarpGate = 366,

    
    BallisticControlSystem = 367,

    /// <summary>Prevents warping into the radius it covers.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Prevents warping into the radius it covers.")]
    GlobalWarpDisruptor = 368,

    
    ShipLogs = 369,

    /// <summary>Items such as Dog Tags that NPC pirates drop.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Items such as Dog Tags that NPC pirates drop.")]
    CriminalTags = 370,

    
    MobileWarpDisruptorBlueprint = 371,

    
    AdvancedAutocannonAmmo = 372,

    
    AdvancedRailgunCharge = 373,

    
    AdvancedBeamLaserCrystal = 374,

    
    AdvancedPulseLaserCrystal = 375,

    
    AdvancedArtilleryAmmo = 376,

    
    AdvancedBlasterCharge = 377,

    
    CruiseControl = 378,

    
    TargetPainter = 379,

    
    TransportShip = 380,

    
    EliteBattleship = 381,

    /// <summary>Shipping Crate</summary>
    
    [System.ComponentModel.DescriptionAttribute("Shipping Crate")]
    ShippingCrates = 382,

    /// <summary>Sentry guns inside scenarios, usually owned by pirate factions, that can be destroyed by players.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sentry guns inside scenarios, usually owned by pirate factions, that can be destr" +
        "oyed by players.")]
    DestructibleSentryGun = 383,

    /// <summary>Light Missile Charges</summary>
    
    [System.ComponentModel.DescriptionAttribute("Light Missile Charges")]
    LightMissile = 384,

    /// <summary>Heavy Missile Charges</summary>
    
    [System.ComponentModel.DescriptionAttribute("Heavy Missile Charges")]
    HeavyMissile = 385,

    
    CruiseMissile = 386,

    
    Rocket = 387,

    
    FoFLightMissile = 394,

    
    FoFHeavyMissile = 395,

    
    FoFCruiseMissile = 396,

    /// <summary>Deployable Assembly Array</summary>
    
    [System.ComponentModel.DescriptionAttribute("Deployable Assembly Array")]
    AssemblyArray = 397,

    
    BallisticControlSystemBlueprint = 400,

    
    CloakingDeviceBlueprint = 401,

    /// <summary>Used to store or provide resources of a specific type.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Used to store or provide resources of a specific type.")]
    Silo = 404,

    /// <summary>Broadcast a signal in all directions within a limited range that cause all the cloaked objects within it to decloak.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Broadcast a signal in all directions within a limited range that cause all the cl" +
        "oaked objects within it to decloak.")]
    AntiCloakingPulse = 405,

    /// <summary>Modules that boost the Damage of Smartbombs</summary>
    
    [System.ComponentModel.DescriptionAttribute("Modules that boost the Damage of Smartbombs")]
    SmartbombSupercharger = 406,

    
    DroneControlUnit = 407,

    
    DroneControlUnitBlueprint = 408,

    /// <summary>The insignia drops are implemented to replace the "bounty" feature for Empire mission drones, such as Navy ships.  Insignias are traded in to agents for money (will be implemented in Shiva).</summary>
    
    [System.ComponentModel.DescriptionAttribute("The insignia drops are implemented to replace the \"bounty\" feature for Empire mis" +
        "sion drones, such as Navy ships.  Insignias are traded in to agents for money (w" +
        "ill be implemented in Shiva).")]
    EmpireInsigniaDrops = 409,

    
    AntiCloakingPulseBlueprint = 410,

    /// <summary>A spherical barrier, maybe placed around something.</summary>
    
    [System.ComponentModel.DescriptionAttribute("A spherical barrier, maybe placed around something.")]
    ForceField = 411,

    
    MobileLaboratory = 413,

    
    MobilePowerCore = 414,

    
    MoonMining = 416,

    
    MobileMissileSentry = 417,

    
    MobileShieldGenerator = 418,

    
    Battlecruiser = 419,

    
    Destroyer = 420,

    /// <summary>Gas Isotopes harvested from gas clouds.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Gas Isotopes harvested from gas clouds.")]
    GasIsotopes = 422,

    
    IceProduct = 423,

    
    OrbitalAssaultUnit = 425,

    
    MobileProjectileSentry = 426,

    /// <summary>Stuff Harvested directly from Moons</summary>
    
    [System.ComponentModel.DescriptionAttribute("Stuff Harvested directly from Moons")]
    MoonMaterials = 427,

    /// <summary>Stuff made from moon materials in a reactor</summary>
    
    [System.ComponentModel.DescriptionAttribute("Stuff made from moon materials in a reactor")]
    IntermediateMaterials = 428,

    
    Composite = 429,

    
    MobileLaserSentry = 430,

    
    DeadspaceOverseer = 435,

    
    SimpleReaction = 436,

    
    MobileReactor = 438,

    /// <summary>Group for mobile racial ECM.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Group for mobile racial ECM.")]
    ElectronicWarfareBattery = 439,

    /// <summary>Deployable Sensor Dampener</summary>
    
    [System.ComponentModel.DescriptionAttribute("Deployable Sensor Dampener")]
    SensorDampeningBattery = 440,

    /// <summary>Deployable Stasis Webber</summary>
    
    [System.ComponentModel.DescriptionAttribute("Deployable Stasis Webber")]
    StasisWebificationBattery = 441,

    /// <summary>Deployable warp jammers.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Deployable warp jammers.")]
    WarpScramblingBattery = 443,

    /// <summary>Increases control tower shield resistances</summary>
    
    [System.ComponentModel.DescriptionAttribute("Increases control tower shield resistances")]
    ShieldHardeningArray = 444,

    /// <summary>Projects a shield around structures outside the range of a control tower.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Projects a shield around structures outside the range of a control tower.")]
    ForceFieldArray = 445,

    
    CustomsOfficial = 446,

    
    ConstructionComponentBlueprints = 447,

    
    AuditLogSecureContainer = 448,

    
    MobileHybridSentry = 449,

    
    Arkonor = 450,

    
    Bistot = 451,

    
    Crokite = 452,

    
    DarkOchre = 453,

    
    Hedbergite = 454,

    
    Hemorphite = 455,

    
    Jaspet = 456,

    
    Kernite = 457,

    
    Plagioclase = 458,

    
    Pyroxeres = 459,

    
    Scordite = 460,

    
    Spodumain = 461,

    
    Veldspar = 462,

    /// <summary>Mining Barges</summary>
    
    [System.ComponentModel.DescriptionAttribute("Mining Barges")]
    MiningBarge = 463,

    
    StripMiner = 464,

    
    Ice = 465,

    
    Gneiss = 467,

    
    Mercoxit = 468,

    
    Omber = 469,

    
    UnanchoringDrone = 470,

    /// <summary>A Corp Hangar in space.</summary>
    
    [System.ComponentModel.DescriptionAttribute("A Corp Hangar in space.")]
    CorporateHangarArray = 471,

    
    SystemScanner = 472,

    /// <summary>Increases Optimal Range and Tracking Speed of all Turret Sentries</summary>
    
    [System.ComponentModel.DescriptionAttribute("Increases Optimal Range and Tracking Speed of all Turret Sentries")]
    TrackingArray = 473,

    /// <summary>Contains keys, passcards, cyphers and other objects required to open locked acceleration gates in deadspace complexes.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Contains keys, passcards, cyphers and other objects required to open locked accel" +
        "eration gates in deadspace complexes.")]
    AccelerationGateKeys = 474,

    
    Microwarpdrive = 475,

    
    CitadelTorpedo = 476,

    
    MiningBargeBlueprint = 477,

    
    SystemScannerBlueprint = 478,

    
    ScannerProbe = 479,

    
    StealthEmitterArray = 480,

    
    ScanProbeLauncher = 481,

    
    MiningCrystal = 482,

    
    FrequencyMiningLaser = 483,

    
    ComplexReactions = 484,

    
    Dreadnought = 485,

    
    ScanProbeBlueprint = 486,

    
    DestroyerBlueprint = 487,

    
    BattlecruiserBlueprint = 489,

    
    StripMinerBlueprint = 490,

    
    SurveyProbe = 492,

    
    OverseerPersonalEffects = 493,

    /// <summary>This structure belongs to the overseer of this deadspace pocket.</summary>
    
    [System.ComponentModel.DescriptionAttribute("This structure belongs to the overseer of this deadspace pocket.")]
    DeadspaceOverseersStructure = 494,

    /// <summary>This sentry is controlled by the overseer of this deadspace pocket.</summary>
    
    [System.ComponentModel.DescriptionAttribute("This sentry is controlled by the overseer of this deadspace pocket.")]
    DeadspaceOverseersSentry = 495,

    /// <summary>This container is tagged as the property of this deadspace pocket's overseer.</summary>
    
    [System.ComponentModel.DescriptionAttribute("This container is tagged as the property of this deadspace pocket\'s overseer.")]
    DeadspaceOverseersBelongings = 496,

    
    Fuel = 497,

    
    Modifications = 498,

    
    NewEwTesting = 499,

    
    Snowballs = 500,

    
    MissileLauncherSnowball = 501,

    /// <summary>Disturbances and other anomalies in the electromagnetic or gravity field</summary>
    
    [System.ComponentModel.DescriptionAttribute("Disturbances and other anomalies in the electromagnetic or gravity field")]
    CosmicSignature = 502,

    
    EliteIndustrialBlueprint = 503,

    
    TargetPainterBlueprint = 504,

    /// <summary>This group is for fake skills used for bonuses.</summary>
    
    [System.ComponentModel.DescriptionAttribute("This group is for fake skills used for bonuses.")]
    FakeSkills = 505,

    
    MissileLauncherCruise = 506,

    
    MissileLauncherRocket = 507,

    
    MissileLauncherTorpedo = 508,

    
    MissileLauncherLight = 509,

    
    MissileLauncherHeavy = 510,

    
    MissileLauncherRapidLight = 511,

    
    MissileLauncherDefender = 512,

    
    Freighter = 513,

    
    EcmStabilizer = 514,

    
    SiegeModule = 515,

    
    SiegeModuleBlueprint = 516,

    /// <summary>Piiiiiigs iiiiiin Spaaaaaaaace.....</summary>
    
    [System.ComponentModel.DescriptionAttribute("Piiiiiigs iiiiiin Spaaaaaaaace.....")]
    AgentsInSpace = 517,

    
    AntiBallisticDefenseSystem = 518,

    
    TerranArtifacts = 519,

    
    StorylineFrigate = 520,

    
    Identification = 521,

    
    StorylineCruiser = 522,

    
    StorylineBattleship = 523,

    
    MissileLauncherCitadel = 524,

    
    FreighterBlueprint = 525,

    
    Commodities = 526,

    
    StorylineMissionFrigate = 527,

    /// <summary>Artifacts of ancient cultures in the world of eve.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Artifacts of ancient cultures in the world of eve.")]
    ArtifactsAndPrototypes = 528,

    /// <summary>Alloys and Special materials used in manufacture of Ancient technology</summary>
    
    [System.ComponentModel.DescriptionAttribute("Alloys and Special materials used in manufacture of Ancient technology")]
    MaterialsAndCompounds = 530,

    
    GangCoordinatorBlueprint = 532,

    
    StorylineMissionCruiser = 533,

    
    StorylineMissionBattleship = 534,

    
    ConstructionPlatformBlueprint = 535,

    
    StationComponents = 536,

    
    DreadnoughtBlueprint = 537,

    
    DataMiners = 538,

    
    CommandShip = 540,

    
    Interdictor = 541,

    
    Exhumer = 543,

    
    CapDrainDrone = 544,

    
    WarpScramblingDrone = 545,

    
    MiningUpgrade = 546,

    
    Carrier = 547,

    
    InterdictionProbe = 548,

    
    FighterDrone = 549,

    
    AsteroidAngelCartelFrigate = 550,

    
    AsteroidAngelCartelCruiser = 551,

    
    AsteroidAngelCartelBattleship = 552,

    
    AsteroidAngelCartelOfficer = 553,

    
    AsteroidAngelCartelHauler = 554,

    
    AsteroidBloodRaidersCruiser = 555,

    
    AsteroidBloodRaidersBattleship = 556,

    
    AsteroidBloodRaidersFrigate = 557,

    
    AsteroidBloodRaidersHauler = 558,

    
    AsteroidBloodRaidersOfficer = 559,

    
    AsteroidGuristasBattleship = 560,

    
    AsteroidGuristasCruiser = 561,

    
    AsteroidGuristasFrigate = 562,

    
    AsteroidGuristasHauler = 563,

    
    AsteroidGuristasOfficer = 564,

    
    AsteroidSanshasNationBattleship = 565,

    
    AsteroidSanshasNationCruiser = 566,

    
    AsteroidSanshasNationFrigate = 567,

    
    AsteroidSanshasNationHauler = 568,

    
    AsteroidSanshasNationOfficer = 569,

    
    AsteroidSerpentisBattleship = 570,

    
    AsteroidSerpentisCruiser = 571,

    
    AsteroidSerpentisFrigate = 572,

    
    AsteroidSerpentisHauler = 573,

    
    AsteroidSerpentisOfficer = 574,

    
    AsteroidAngelCartelDestroyer = 575,

    
    AsteroidAngelCartelBattleCruiser = 576,

    
    AsteroidBloodRaidersDestroyer = 577,

    
    AsteroidBloodRaidersBattleCruiser = 578,

    
    AsteroidGuristasDestroyer = 579,

    
    AsteroidGuristasBattleCruiser = 580,

    
    AsteroidSanshasNationDestroyer = 581,

    
    AsteroidSanshasNationBattleCruiser = 582,

    
    AsteroidSerpentisDestroyer = 583,

    
    AsteroidSerpentisBattleCruiser = 584,

    /// <summary>Modules used to repair damaged hull of friendly vessels</summary>
    
    [System.ComponentModel.DescriptionAttribute("Modules used to repair damaged hull of friendly vessels")]
    RemoteHullRepairer = 585,

    
    DroneModules = 586,

    
    SuperWeapon = 588,

    
    InterdictionSphereLauncher = 589,

    
    JumpPortalGenerator = 590,

    
    DeadspaceAngelCartelBattleCruiser = 593,

    
    DeadspaceAngelCartelBattleship = 594,

    
    DeadspaceAngelCartelCruiser = 595,

    
    DeadspaceAngelCartelDestroyer = 596,

    
    DeadspaceAngelCartelFrigate = 597,

    
    DeadspaceBloodRaidersBattleCruiser = 602,

    
    DeadspaceBloodRaidersBattleship = 603,

    
    DeadspaceBloodRaidersCruiser = 604,

    
    DeadspaceBloodRaidersDestroyer = 605,

    
    DeadspaceBloodRaidersFrigate = 606,

    
    DeadspaceGuristasBattleCruiser = 611,

    
    DeadspaceGuristasBattleship = 612,

    
    DeadspaceGuristasCruiser = 613,

    
    DeadspaceGuristasDestroyer = 614,

    
    DeadspaceGuristasFrigate = 615,

    
    DeadspaceSanshasNationBattleCruiser = 620,

    
    DeadspaceSanshasNationBattleship = 621,

    
    DeadspaceSanshasNationCruiser = 622,

    
    DeadspaceSanshasNationDestroyer = 623,

    
    DeadspaceSanshasNationFrigate = 624,

    
    DeadspaceSerpentisBattleCruiser = 629,

    
    DeadspaceSerpentisBattleship = 630,

    
    DeadspaceSerpentisCruiser = 631,

    
    DeadspaceSerpentisDestroyer = 632,

    
    DeadspaceSerpentisFrigate = 633,

    
    NavigationComputer = 638,

    
    ElectronicWarfareDrone = 639,

    
    LogisticDrone = 640,

    
    StasisWebifyingDrone = 641,

    
    SuperGangEnhancer = 642,

    
    CarrierBlueprint = 643,

    
    DroneNavigationComputer = 644,

    
    DroneDamageModules = 645,

    
    DroneTrackingModules = 646,

    
    DroneControlRangeModule = 647,

    
    AdvancedRocket = 648,

    /// <summary>Freight Containers are commonly used in Freighter-class ships to accomodate their massive cargobays.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Freight Containers are commonly used in Freighter-class ships to accomodate their" +
        " massive cargobays.")]
    FreightContainer = 649,

    
    TractorBeam = 650,

    
    SuperWeaponBlueprint = 651,

    /// <summary>Each 'Starbase Code Cycle' equals 1 hour of operation of a control tower in the sovereign space of the entity that issued the code. If no Starbase Code Cycle is available during a Control Tower consumption cycle, it should be considered as it has no fuel and therefore offlined.</summary>
    
    [System.ComponentModel.DescriptionAttribute(@"Each 'Starbase Code Cycle' equals 1 hour of operation of a control tower in the sovereign space of the entity that issued the code. If no Starbase Code Cycle is available during a Control Tower consumption cycle, it should be considered as it has no fuel and therefore offlined.")]
    Lease = 652,

    
    AdvancedLightMissile = 653,

    
    AdvancedHeavyAssaultMissile = 654,

    
    AdvancedHeavyMissile = 655,

    
    AdvancedCruiseMissile = 656,

    
    AdvancedTorpedo = 657,

    
    CynosuralField = 658,

    /// <summary>Supercarrier</summary>
    
    [System.ComponentModel.DescriptionAttribute("Supercarrier")]
    Supercarrier = 659,

    
    EnergyVampireSlayer = 660,

    
    SimpleBiochemicalReactions = 661,

    
    ComplexBiochemicalReactions = 662,

    
    MercoxitMiningCrystal = 663,

    
    MissionAmarrEmpireFrigate = 665,

    
    MissionAmarrEmpireBattlecruiser = 666,

    
    MissionAmarrEmpireBattleship = 667,

    
    MissionAmarrEmpireCruiser = 668,

    
    MissionAmarrEmpireDestroyer = 669,

    
    MissionAmarrEmpireOther = 670,

    
    MissionCaldariStateFrigate = 671,

    
    MissionCaldariStateBattlecruiser = 672,

    
    MissionCaldariStateCruiser = 673,

    
    MissionCaldariStateBattleship = 674,

    
    MissionCaldariStateOther = 675,

    
    MissionCaldariStateDestroyer = 676,

    
    MissionGallenteFederationFrigate = 677,

    
    MissionGallenteFederationCruiser = 678,

    
    MissionGallenteFederationDestroyer = 679,

    
    MissionGallenteFederationBattleship = 680,

    
    MissionGallenteFederationBattlecruiser = 681,

    
    MissionGallenteFederationOther = 682,

    
    MissionMinmatarRepublicFrigate = 683,

    
    MissionMinmatarRepublicDestroyer = 684,

    
    MissionMinmatarRepublicBattlecruiser = 685,

    
    MissionMinmatarRepublicOther = 686,

    
    MissionKhanidFrigate = 687,

    
    MissionKhanidDestroyer = 688,

    
    MissionKhanidCruiser = 689,

    
    MissionKhanidBattlecruiser = 690,

    
    MissionKhanidBattleship = 691,

    
    MissionKhanidOther = 692,

    
    MissionConcordFrigate = 693,

    
    MissionConcordDestroyer = 694,

    
    MissionConcordCruiser = 695,

    
    MissionConcordBattlecruiser = 696,

    
    MissionConcordBattleship = 697,

    
    MissionConcordOther = 698,

    
    MissionMorduFrigate = 699,

    
    MissionMorduDestroyer = 700,

    
    MissionMorduCruiser = 701,

    
    MissionMorduBattlecruiser = 702,

    
    MissionMorduBattleship = 703,

    
    MissionMorduOther = 704,

    
    MissionMinmatarRepublicCruiser = 705,

    
    MissionMinmatarRepublicBattleship = 706,

    
    JumpPortalArray = 707,

    
    ScannerArray = 709,

    
    LogisticsArray = 710,

    
    HarvestableCloud = 711,

    
    BiochemicalMaterial = 712,

    
    DestructibleAgentsInSpace = 715,

    
    DataInterfaces = 716,

    
    BoosterBlueprints = 718,

    
    Temp = 721,

    
    AdvancedHybridChargeBlueprint = 722,

    
    TractorBeamBlueprint = 723,

    
    ImplantBlueprints = 724,

    
    AdvancedProjectileAmmoBlueprint = 725,

    
    AdvancedFrequencyCrystalBlueprint = 726,

    
    MiningCrystalBlueprint = 727,

    
    DecryptorsAmarr = 728,

    
    DecryptorsMinmatar = 729,

    
    DecryptorsGallente = 730,

    
    DecryptorsCaldari = 731,

    
    DecryptorsSleepers = 732,

    
    DecryptorsYanJung = 733,

    
    DecryptorsTakmahl = 734,

    
    DecryptorsTalocan = 735,

    
    GasCloudHarvester = 737,

    /// <summary>Implants relating to armor. </summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to armor. ")]
    CyberArmor = 738,

    /// <summary>Implants relating to drones</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to drones")]
    CyberDrones = 739,

    /// <summary>Implants relating to electronic warfare</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to electronic warfare")]
    CyberElectronics = 740,

    /// <summary>Implants related to capacitor</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants related to capacitor")]
    CyberEngineering = 741,

    /// <summary>Implants relating to gunnery</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to gunnery")]
    CyberGunnery = 742,

    /// <summary>Implants related to mining, refining and manufacturing.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants related to mining, refining and manufacturing.")]
    CyberIndustry = 743,

    /// <summary>Implants relating to gangs</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to gangs")]
    CyberLeadership = 744,

    /// <summary>Implants relating to character attributes.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to character attributes.")]
    CyberLearning = 745,

    /// <summary>Implants relating to missile launcher operation.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to missile launcher operation.")]
    CyberMissile = 746,

    /// <summary>Implants relating to speed mods. </summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to speed mods. ")]
    CyberNavigation = 747,

    /// <summary>Implants related to research.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants related to research.")]
    CyberScience = 748,

    /// <summary>Implants relating to shields. </summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to shields. ")]
    CyberShields = 749,

    /// <summary>Implants relating to agents.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants relating to agents.")]
    CyberSocial = 750,

    /// <summary>Implants related to trading.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Implants related to trading.")]
    CyberTrade = 751,

    
    EcmEnhancer = 753,

    
    SalvagedMaterials = 754,

    
    AsteroidRogueDroneBattleCruiser = 755,

    
    AsteroidRogueDroneBattleship = 756,

    
    AsteroidRogueDroneCruiser = 757,

    
    AsteroidRogueDroneDestroyer = 758,

    
    AsteroidRogueDroneFrigate = 759,

    
    AsteroidRogueDroneHauler = 760,

    
    AsteroidRogueDroneSwarm = 761,

    
    InertiaStabilizer = 762,

    
    NanofiberInternalStructure = 763,

    
    OverdriveInjectorSystem = 764,

    
    ExpandedCargohold = 765,

    
    PowerDiagnosticSystem = 766,

    
    CapacitorPowerRelay = 767,

    
    CapacitorFluxCoil = 768,

    
    ReactorControlUnit = 769,

    
    ShieldFluxCoil = 770,

    
    MissileLauncherHeavyAssault = 771,

    
    HeavyAssaultMissile = 772,

    
    RigArmor = 773,

    
    RigShield = 774,

    
    RigEnergyWeapon = 775,

    
    RigHybridWeapon = 776,

    
    RigProjectileWeapon = 777,

    
    RigDrones = 778,

    
    RigLauncher = 779,

    
    RigElectronics = 780,

    
    RigEnergyGrid = 781,

    
    RigAstronautic = 782,

    
    CyberXSpecials = 783,

    
    LargeCollidableShip = 784,

    
    RigElectronicsSuperiority = 786,

    
    RigBlueprint = 787,

    
    AsteroidAngelCartelCommanderFrigate = 789,

    
    AsteroidAngelCartelCommanderCruiser = 790,

    
    AsteroidBloodRaidersCommanderCruiser = 791,

    
    AsteroidBloodRaidersCommanderFrigate = 792,

    
    AsteroidAngelCartelCommanderBattleCruiser = 793,

    
    AsteroidAngelCartelCommanderDestroyer = 794,

    
    AsteroidBloodRaidersCommanderBattleCruiser = 795,

    
    AsteroidBloodRaidersCommanderDestroyer = 796,

    
    AsteroidGuristasCommanderBattleCruiser = 797,

    
    AsteroidGuristasCommanderCruiser = 798,

    
    AsteroidGuristasCommanderDestroyer = 799,

    
    AsteroidGuristasCommanderFrigate = 800,

    
    DeadspaceRogueDroneBattleCruiser = 801,

    
    DeadspaceRogueDroneBattleship = 802,

    
    DeadspaceRogueDroneCruiser = 803,

    
    DeadspaceRogueDroneDestroyer = 804,

    
    DeadspaceRogueDroneFrigate = 805,

    
    DeadspaceRogueDroneSwarm = 806,

    
    AsteroidSanshasNationCommanderBattleCruiser = 807,

    
    AsteroidSanshasNationCommanderCruiser = 808,

    
    AsteroidSanshasNationCommanderDestroyer = 809,

    
    AsteroidSanshasNationCommanderFrigate = 810,

    
    AsteroidSerpentisCommanderBattleCruiser = 811,

    
    AsteroidSerpentisCommanderCruiser = 812,

    
    AsteroidSerpentisCommanderDestroyer = 813,

    
    AsteroidSerpentisCommanderFrigate = 814,

    
    CloneVatBay = 815,

    /// <summary>Remnants of the "Mission Drones" and "Faction Drones" groups. Contains NPC's that do not fall under other categories. Holds Battleship sized entities.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Remnants of the \"Mission Drones\" and \"Faction Drones\" groups. Contains NPC\'s that" +
        " do not fall under other categories. Holds Battleship sized entities.")]
    MissionGenericBattleships = 816,

    /// <summary>Remnants of the "Mission Drones" and "Faction Drones" groups. Contains NPC's that do not fall under other categories. Holds Cruiser sized entities.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Remnants of the \"Mission Drones\" and \"Faction Drones\" groups. Contains NPC\'s that" +
        " do not fall under other categories. Holds Cruiser sized entities.")]
    MissionGenericCruisers = 817,

    /// <summary>Remnants of the "Mission Drones" and "Faction Drones" groups. Contains NPC's that do not fall under other categories. Holds Frigate sized NPC's</summary>
    
    [System.ComponentModel.DescriptionAttribute("Remnants of the \"Mission Drones\" and \"Faction Drones\" groups. Contains NPC\'s that" +
        " do not fall under other categories. Holds Frigate sized NPC\'s")]
    MissionGenericFrigates = 818,

    
    DeadspaceOverseerFrigate = 819,

    
    DeadspaceOverseerCruiser = 820,

    
    DeadspaceOverseerBattleship = 821,

    
    MissionThukkerBattlecruiser = 822,

    
    MissionThukkerBattleship = 823,

    
    MissionThukkerCruiser = 824,

    
    MissionThukkerDestroyer = 825,

    
    MissionThukkerFrigate = 826,

    
    MissionThukkerOther = 827,

    /// <summary>Remnants of the "Mission Drones" and "Faction Drones" groups. Contains NPC's that do not fall under other categories. Holds Battle Cruiser sized entities.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Remnants of the \"Mission Drones\" and \"Faction Drones\" groups. Contains NPC\'s that" +
        " do not fall under other categories. Holds Battle Cruiser sized entities.")]
    MissionGenericBattleCruisers = 828,

    /// <summary>Remnants of the "Mission Drones" and "Faction Drones" groups. Contains NPC's that do not fall under other categories. Holds Destroyer sized entities.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Remnants of the \"Mission Drones\" and \"Faction Drones\" groups. Contains NPC\'s that" +
        " do not fall under other categories. Holds Destroyer sized entities.")]
    MissionGenericDestroyers = 829,

    
    CovertOps = 830,

    
    Interceptor = 831,

    
    Logistics = 832,

    
    ForceReconShip = 833,

    
    StealthBomber = 834,

    
    StationUpgradePlatform = 835,

    
    StationImprovementPlatform = 836,

    /// <summary>Deployable Energy Neutralizer</summary>
    
    [System.ComponentModel.DescriptionAttribute("Deployable Energy Neutralizer")]
    EnergyNeutralizingBattery = 837,

    
    CynosuralGeneratorArray = 838,

    
    CynosuralSystemJammer = 839,

    
    StructureRepairArray = 840,

    
    StructuresControlTowerBlueprints = 841,

    
    RemoteEcmBurst = 842,

    
    AsteroidRogueDroneCommanderBattleCruiser = 843,

    
    AsteroidRogueDroneCommanderBattleship = 844,

    
    AsteroidRogueDroneCommanderCruiser = 845,

    
    AsteroidRogueDroneCommanderDestroyer = 846,

    
    AsteroidRogueDroneCommanderFrigate = 847,

    
    AsteroidAngelCartelCommanderBattleship = 848,

    
    AsteroidBloodRaidersCommanderBattleship = 849,

    
    AsteroidGuristasCommanderBattleship = 850,

    
    AsteroidSanshasNationCommanderBattleship = 851,

    
    AsteroidSerpentisCommanderBattleship = 852,

    
    StructuresLaserBatteryBlueprints = 853,

    
    StructuresProjectileBatteryBlueprints = 854,

    
    StructuresHybridBatteryBlueprints = 855,

    
    StructuresEcmJammingArrayBlueprints = 856,

    
    StructuresWarpScramblingBatteryBlueprints = 857,

    
    StructuresStasisWebificationBatteryBlueprints = 858,

    
    StructuresSensorDampeningArrayBlueprints = 859,

    
    StructuresEnergyNeutralizingBatteryBlueprints = 860,

    
    MissionFighterDrone = 861,

    
    MissileLauncherBomb = 862,

    
    BombEcm = 863,

    
    BombEnergy = 864,

    
    MissionAmarrEmpireCarrier = 865,

    
    MissionCaldariStateCarrier = 866,

    
    MissionGallenteFederationCarrier = 867,

    
    MissionMinmatarRepublicCarrier = 868,

    
    RemoteHullRepairerBlueprint = 870,

    
    StructuresMissileBatteryBlueprints = 871,

    
    OutpostImprovements = 872,

    /// <summary>Capital Construction Components</summary>
    
    [System.ComponentModel.DescriptionAttribute("Capital Construction Components")]
    CapitalConstructionComponents = 873,

    
    DestructibleStationServices = 874,

    
    MissionFactionTransports = 875,

    
    OutpostUpgrades = 876,

    
    TargetPaintingBattery = 877,

    /// <summary>Module group for modules that affect cloaking devices</summary>
    
    [System.ComponentModel.DescriptionAttribute("Module group for modules that affect cloaking devices")]
    CloakEnhancements = 878,

    
    SlaveReception = 879,

    
    SleeperComponents = 880,

    
    FreedomPrograms = 881,

    
    EnslavementPrograms = 882,

    
    CapitalIndustrialShip = 883,

    
    TestCompressedOre = 884,

    
    CosmicAnomaly = 885,

    
    RogueDroneComponents = 886,

    
    OreCompressionBlueprints = 888,

    
    OreEnhancementBlueprints = 889,

    
    IceCompressionBlueprints = 890,

    
    StructuresMobileLaboratoryBlueprints = 891,

    
    PlanetSatellites = 892,

    
    ElectronicAttackShip = 893,

    
    HeavyInterdictor = 894,

    
    RigSecurityTransponder = 896,

    
    CovertBeacon = 897,

    
    BlackOps = 898,

    
    WarpDisruptFieldGenerator = 899,

    
    Marauder = 900,

    
    MiningEnhancer = 901,

    
    JumpFreighter = 902,

    
    AncientCompressedIce = 903,

    
    RigMining = 904,

    
    CovertCynosuralFieldGenerator = 905,

    
    CombatReconShip = 906,

    
    TrackingScript = 907,

    
    WarpDisruptionScript = 908,

    
    TrackingDisruptionScript = 909,

    
    SensorBoosterScript = 910,

    
    SensorDampenerScript = 911,

    
    ScriptBlueprint = 912,

    
    AdvancedCapitalConstructionComponents = 913,

    
    AdvancedCapitalConstructionComponentBlueprints = 914,

    
    CapitalConstructionBlueprints = 915,

    
    NaniteRepairPaste = 916,

    
    DataMinerBlueprint = 917,

    
    ScanProbeLauncherBlueprint = 918,

    
    EffectBeacon = 920,

    
    CapturePoint = 922,

    
    MissionFactionBattleship = 924,

    
    InfrastructureHub = 925,

    
    MissionFactionIndustrials = 927,

    
    ZombieEntities = 934,

    /// <summary>Group for worldspaces</summary>
    
    [System.ComponentModel.DescriptionAttribute("Group for worldspaces")]
    WorldSpace = 935,

    
    Decorations = 937,

    /// <summary>Furniture</summary>
    
    [System.ComponentModel.DescriptionAttribute("Furniture")]
    Furniture = 940,

    
    IndustrialCommandShip = 941,

    
    GameTime = 943,

    
    CapitalIndustrialShipBlueprint = 944,

    
    IndustrialCommandShipBlueprint = 945,

    /// <summary>Containers that can be deployed in dungeons and accept items to be placed into them. Can have triggers that check if specific item is placed in it (for mission completion for instance).</summary>
    
    [System.ComponentModel.DescriptionAttribute("Containers that can be deployed in dungeons and accept items to be placed into th" +
        "em. Can have triggers that check if specific item is placed in it (for mission c" +
        "ompletion for instance).")]
    MissionContainer = 952,

    
    DefensiveSystems = 954,

    
    ElectronicSystems = 955,

    
    OffensiveSystems = 956,

    
    PropulsionSystems = 957,

    
    EngineeringSystems = 958,

    /// <summary>Sleeper large NPCs for the Apocrypha expansion encountered in the most difficult wormhole systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sleeper large NPCs for the Apocrypha expansion encountered in the most difficult " +
        "wormhole systems.")]
    DeadspaceSleeperSleeplessSentinel = 959,

    /// <summary>Sleeper medium NPCs for the Apocrypha expansion encountered in the most difficutly wormhole systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sleeper medium NPCs for the Apocrypha expansion encountered in the most difficutl" +
        "y wormhole systems.")]
    DeadspaceSleeperAwakenedSentinel = 960,

    /// <summary>Sleeper small NPCs for the Apocrypha expansion encountered in the most difficult wormhole systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sleeper small NPCs for the Apocrypha expansion encountered in the most difficult " +
        "wormhole systems.")]
    DeadspaceSleeperEmergentSentinel = 961,

    
    StrategicCruiser = 963,

    /// <summary>Components used to build tech III hulls and subsystems</summary>
    
    [System.ComponentModel.DescriptionAttribute("Components used to build tech III hulls and subsystems")]
    HybridTechComponents = 964,

    
    HybridComponentBlueprints = 965,

    
    AncientSalvage = 966,

    
    WormholeMinerals = 967,

    
    SleeperPropulsionRelics = 971,

    /// <summary>This is a holding group for probes that we're not using under the revised mechanics</summary>
    
    [System.ComponentModel.DescriptionAttribute("This is a holding group for probes that we\'re not using under the revised mechani" +
        "cs")]
    ObsoleteProbes = 972,

    
    SubsystemBlueprints = 973,

    
    HybridPolymers = 974,

    /// <summary>Melted Snowballs</summary>
    
    [System.ComponentModel.DescriptionAttribute("Melted Snowballs")]
    MeltedSnowballs = 976,

    
    HybridReactions = 977,

    
    DecryptorsHybrid = 979,

    /// <summary>Sleeper large NPCs for the Apocrypha expansion encountered in the medium difficutly wormhole systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sleeper large NPCs for the Apocrypha expansion encountered in the medium difficut" +
        "ly wormhole systems.")]
    DeadspaceSleeperSleeplessDefender = 982,

    /// <summary>Sleeper large NPCs for the Apocrypha expansion encountered in the easiest difficulty wormhole systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sleeper large NPCs for the Apocrypha expansion encountered in the easiest difficu" +
        "lty wormhole systems.")]
    DeadspaceSleeperSleeplessPatroller = 983,

    /// <summary>Sleeper medium NPCs for the Apocrypha expansion encountered in the average difficutly wormhole systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sleeper medium NPCs for the Apocrypha expansion encountered in the average diffic" +
        "utly wormhole systems.")]
    DeadspaceSleeperAwakenedDefender = 984,

    /// <summary>Sleeper medium NPCs for the Apocrypha expansion encountered in the easiest difficutly wormhole systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sleeper medium NPCs for the Apocrypha expansion encountered in the easiest diffic" +
        "utly wormhole systems.")]
    DeadspaceSleeperAwakenedPatroller = 985,

    /// <summary>Sleeper small NPCs for the Apocrypha expansion encountered in the medium difficulty wormhole systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sleeper small NPCs for the Apocrypha expansion encountered in the medium difficul" +
        "ty wormhole systems.")]
    DeadspaceSleeperEmergentDefender = 986,

    /// <summary>Sleeper small NPCs for the Apocrypha expansion encountered in the easiest difficutly wormhole systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sleeper small NPCs for the Apocrypha expansion encountered in the easiest difficu" +
        "tly wormhole systems.")]
    DeadspaceSleeperEmergentPatroller = 987,

    /// <summary>This is a group for all the various Wormhole types</summary>
    
    [System.ComponentModel.DescriptionAttribute("This is a group for all the various Wormhole types")]
    Wormhole = 988,

    
    Subsystems = 989,

    
    SleeperElectronicsRelics = 990,

    
    SleeperOffensiveRelics = 991,

    
    SleeperEngineeringRelics = 992,

    
    SleeperDefensiveRelics = 993,

    /// <summary>Objects making up part of a multi-celestial grouping</summary>
    
    [System.ComponentModel.DescriptionAttribute("Objects making up part of a multi-celestial grouping")]
    SecondarySun = 995,

    
    StrategicCruiserBlueprints = 996,

    
    SleeperHullRelics = 997,

    /// <summary>Sovereignty Claim structure group, this group will display anywhere in the system.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sovereignty Claim structure group, this group will display anywhere in the system" +
        ".")]
    TerritorialClaimUnits = 1003,

    /// <summary>Structures that can be anchored once sovereignty is claimed.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Structures that can be anchored once sovereignty is claimed.")]
    DefenseBunkers = 1004,

    /// <summary>Disruptor generators, these will be globally visible in the solar system. </summary>
    
    [System.ComponentModel.DescriptionAttribute("Disruptor generators, these will be globally visible in the solar system. ")]
    SovereigntyBlockadeUnits = 1005,

    
    MissionFactionCruiser = 1006,

    
    MissionFactionFrigate = 1007,

    /// <summary>Citadel torpedoes for fighter-bombers</summary>
    
    [System.ComponentModel.DescriptionAttribute("Citadel torpedoes for fighter-bombers")]
    CompactCitadelTorpedo = 1010,

    
    InfrastructureHubs = 1012,

    
    SupercarrierBlueprints = 1013,

    /// <summary>Upgrades enhancing the mobility and/or transportation capacity.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Upgrades enhancing the mobility and/or transportation capacity.")]
    StrategicUpgrades = 1016,

    
    CitadelCruise = 1019,

    
    IndustrialUpgrades = 1020,

    
    MilitaryUpgrades = 1021,

    
    PrototypeExplorationShip = 1022,

    
    FighterBomber = 1023,

    
    OrbitalInfrastructure = 1025,

    
    Extractors = 1026,

    
    CommandCenters = 1027,

    
    Processors = 1028,

    
    StorageFacilities = 1029,

    
    Spaceports = 1030,

    
    PlanetaryResources = 1031,

    /// <summary>These metallic resources include precious metals like gold and silver. </summary>
    
    [System.ComponentModel.DescriptionAttribute("These metallic resources include precious metals like gold and silver. ")]
    PlanetSolid = 1032,

    /// <summary>These gasses can be extracted from planets. </summary>
    
    [System.ComponentModel.DescriptionAttribute("These gasses can be extracted from planets. ")]
    PlanetLiquidGas = 1033,

    /// <summary>This is a placeholder group for commodities. </summary>
    
    [System.ComponentModel.DescriptionAttribute("This is a placeholder group for commodities. ")]
    RefinedCommodities = 1034,

    /// <summary>This group contains living things that can be harvested or collected from a planet. </summary>
    
    [System.ComponentModel.DescriptionAttribute("This group contains living things that can be harvested or collected from a plane" +
        "t. ")]
    PlanetOrganic = 1035,

    
    PlanetaryLinks = 1036,

    /// <summary>Specialized commodities</summary>
    
    [System.ComponentModel.DescriptionAttribute("Specialized commodities")]
    SpecializedCommodities = 1040,

    /// <summary>Final Commodities</summary>
    
    [System.ComponentModel.DescriptionAttribute("Final Commodities")]
    AdvancedCommodities = 1041,

    
    BasicCommodities = 1042,

    
    PlanetManagement = 1044,

    
    SovereigntyStructureBlueprint = 1045,

    
    NaniteRepairPasteBlueprint = 1046,

    
    StructureBlueprint = 1048,

    /// <summary>Sansha's Nation industrial NPCs encountered in the Invasion feature.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sansha\'s Nation industrial NPCs encountered in the Invasion feature.")]
    IncursionSanshasNationIndustrial = 1051,

    /// <summary>Sansha's Nation frigate NPCs encountered in the Invasion feature (winter 2010) in Headquarters systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sansha\'s Nation frigate NPCs encountered in the Invasion feature (winter 2010) in" +
        " Headquarters systems.")]
    IncursionSanshasNationCapital = 1052,

    /// <summary>Sansha's Nation frigate NPCs encountered in the Invasion feature (winter 2010) in Assault systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sansha\'s Nation frigate NPCs encountered in the Invasion feature (winter 2010) in" +
        " Assault systems.")]
    IncursionSanshasNationFrigate = 1053,

    /// <summary>Sansha's Nation frigate NPCs encountered in the Invasion feature (winter 2010) in Vanguard systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sansha\'s Nation frigate NPCs encountered in the Invasion feature (winter 2010) in" +
        " Vanguard systems.")]
    IncursionSanshasNationCruiser = 1054,

    /// <summary>Sansha's Nation cruiser NPCs encountered in the Invasion feature (winter 2010) in Assault systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Sansha\'s Nation cruiser NPCs encountered in the Invasion feature (winter 2010) in" +
        " Assault systems.")]
    IncursionSanshasNationBattleship = 1056,

    
    ExtractorControlUnits = 1063,

    /// <summary>An area of a wall that can have its textures change to deliver different wall patterns and bounced color into the room.</summary>
    
    [System.ComponentModel.DescriptionAttribute("An area of a wall that can have its textures change to deliver different wall pat" +
        "terns and bounced color into the room.")]
    MaterialZone = 1067,

    /// <summary>This is the art you see in the customizable for that chunk of wall and may be swapped out with other chunks of wall that change the look of the space but NOT the function in terms of collision, pathing, and the Target Mesh.</summary>
    
    [System.ComponentModel.DescriptionAttribute("This is the art you see in the customizable for that chunk of wall and may be swa" +
        "pped out with other chunks of wall that change the look of the space but NOT the" +
        " function in terms of collision, pathing, and the Target Mesh.")]
    DetailMesh = 1068,

    /// <summary>Points of conflict on a planet.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Points of conflict on a planet.")]
    Flashpoint = 1071,

    /// <summary>These are test objects, not meant for public release.</summary>
    
    [System.ComponentModel.DescriptionAttribute("These are test objects, not meant for public release.")]
    TestOrbitals = 1073,

    
    Generic = 1079,

    /// <summary>DUST ground structures - FOBs, etc.</summary>
    
    [System.ComponentModel.DescriptionAttribute("DUST ground structures - FOBs, etc.")]
    MercenaryBases = 1081,

    /// <summary>EVE Ground objectives - SCCs, Shield Generators, etc.</summary>
    
    [System.ComponentModel.DescriptionAttribute("EVE Ground objectives - SCCs, Shield Generators, etc.")]
    CapsuleerBases = 1082,

    /// <summary>Eyewear</summary>
    
    [System.ComponentModel.DescriptionAttribute("Eyewear")]
    Eyewear = 1083,

    /// <summary>The tattoos that can be placed on a avatar.</summary>
    
    [System.ComponentModel.DescriptionAttribute("The tattoos that can be placed on a avatar.")]
    Tattoos = 1084,

    /// <summary>These are those spiky bits that get shoved in peoples heads.... </summary>
    
    [System.ComponentModel.DescriptionAttribute("These are those spiky bits that get shoved in peoples heads.... ")]
    Piercings = 1085,

    /// <summary>these are scars that are non free form placement. </summary>
    
    [System.ComponentModel.DescriptionAttribute("these are scars that are non free form placement. ")]
    Scars = 1086,

    /// <summary>The clothing that goes into the mid layer.</summary>
    
    [System.ComponentModel.DescriptionAttribute("The clothing that goes into the mid layer.")]
    MidLayer = 1087,

    /// <summary>These are the outer layer clothing options. </summary>
    
    [System.ComponentModel.DescriptionAttribute("These are the outer layer clothing options. ")]
    Outer = 1088,

    /// <summary>The top layer clothing</summary>
    
    [System.ComponentModel.DescriptionAttribute("The top layer clothing")]
    Tops = 1089,

    /// <summary>The pants options. </summary>
    
    [System.ComponentModel.DescriptionAttribute("The pants options. ")]
    Bottoms = 1090,

    /// <summary>Footwear</summary>
    
    [System.ComponentModel.DescriptionAttribute("Footwear")]
    Footwear = 1091,

    /// <summary>the hair styles that are itemized</summary>
    
    [System.ComponentModel.DescriptionAttribute("the hair styles that are itemized")]
    HairStyles = 1092,

    /// <summary>the make up that players can buy.</summary>
    
    [System.ComponentModel.DescriptionAttribute("the make up that players can buy.")]
    Makeup = 1093,

    
    LensFlares = 1105,

    /// <summary>These objects are used to build other space objects near planets.</summary>
    
    [System.ComponentModel.DescriptionAttribute("These objects are used to build other space objects near planets.")]
    OrbitalConstructionPlatform = 1106,

    
    ParticleSystems = 1107,

    
    AnimatedLights = 1108,

    /// <summary>Audio</summary>
    
    [System.ComponentModel.DescriptionAttribute("Audio")]
    Audio = 1109,

    
    PointLights = 1110,

    
    BoxLights = 1111,

    
    SpotLights = 1112,

    /// <summary>These mechanically self assembling structures are used to erect surface constructions.</summary>
    
    [System.ComponentModel.DescriptionAttribute("These mechanically self assembling structures are used to erect surface construct" +
        "ions.")]
    SurfaceInfrastructurePrefabUnits = 1118,

    
    PerceptionPoints = 1121,

    
    Salvager = 1122,

    
    SalvagerBlueprint = 1123,

    
    PhysicalPortals = 1126,

    /// <summary>Pre-packed blocks of fuel for self-sustaining structures.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Pre-packed blocks of fuel for self-sustaining structures.")]
    FuelBlock = 1136,

    
    FuelBlockBlueprint = 1137,

    
    MiningLaserUpgradeBlueprint = 1139,

    /// <summary>Test text. </summary>
    
    [System.ComponentModel.DescriptionAttribute("Test text. ")]
    ResearchData = 1141,

    
    CapDrainDroneBlueprint = 1142,

    
    ElectronicWarfareDroneBlueprint = 1143,

    
    LogisticDroneBlueprint = 1144,

    
    FighterBomberBlueprint = 1145,

    
    FighterDroneBlueprint = 1146,

    
    StasisWebifyingDroneBlueprint = 1147,

    
    MobileJumpDisruptor = 1149,

    
    ArmorResistanceShiftHardener = 1150,

    
    ArmorResistanceShiftHardenerBlueprint = 1151,

    
    DroneDamageModuleBlueprint = 1152,

    
    ShieldBoosterScript = 1153,

    /// <summary>Chance of breaking target lock of those targeting you, chance increases the more are targeting you.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Chance of breaking target lock of those targeting you, chance increases the more " +
        "are targeting you.")]
    TargetBreaker = 1154,

    
    TargetBreakerBlueprint = 1155,

    
    FueledShieldBooster = 1156,

    
    FueledShieldBoosterBlueprint = 1157,

    
    HeavyDefenderMissile = 1158,

    
    SalvageDrone = 1159,

    
    Catma = 350001,
  }
}
