// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve {


  /// <summary>Contains the ID values associated with the MarketGroup class.</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Eve.Meta", "1.76.447.1674")]
  [System.ComponentModel.DescriptionAttribute("Contains the ID values associated with the MarketGroup class.")]
  public enum MarketGroupId : int {

 
    [System.ComponentModel.DescriptionAttribute("Serpentis identification tags.")]
    TradeGoods_CriminalDogTags_Serpentis = 747,

    /// <summary>Shadow Serpentis identification tags.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Shadow Serpentis identification tags.")]
    TradeGoods_CriminalDogTags_ShadowSerpentis = 748,

    /// <summary>True Sansha identification tags.</summary>
    
    [System.ComponentModel.DescriptionAttribute("True Sansha identification tags.")]
    TradeGoods_CriminalDogTags_TrueSansha = 749,

    /// <summary>Proof positive of a bounty hunter's job well done.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Proof positive of a bounty hunter\'s job well done.")]
    TradeGoods_CriminalEvidence = 614,

    /// <summary>Physical proof of a dastardly villain's demise.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Physical proof of a dastardly villain\'s demise.")]
    TradeGoods_CriminalEvidence_CriminalDnaPatterns = 752,

    /// <summary>Proof that there's one less evil bastard in the world.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Proof that there\'s one less evil bastard in the world.")]
    TradeGoods_CriminalEvidence_OverseersPersonalEffects = 751,

    /// <summary>Various products used in a variety of industries.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Various products used in a variety of industries.")]
    TradeGoods_IndustrialGoods = 20,

    /// <summary>DNA-imprinted personal insignias.</summary>
    
    [System.ComponentModel.DescriptionAttribute("DNA-imprinted personal insignias.")]
    TradeGoods_Insignias = 616,

    /// <summary>Officially sanctioned Amarr Navy insignias.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Officially sanctioned Amarr Navy insignias.")]
    TradeGoods_Insignias_AmarrNavy = 730,

    /// <summary>Officially sanctioned Ammatar Navy insignias.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Officially sanctioned Ammatar Navy insignias.")]
    TradeGoods_Insignias_AmmatarNavy = 731,

    /// <summary>Officially sanctioned CONCORD insignias.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Officially sanctioned CONCORD insignias.")]
    TradeGoods_Insignias_Concord = 733,

    /// <summary>Officially sanctioned Caldari Navy insignias.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Officially sanctioned Caldari Navy insignias.")]
    TradeGoods_Insignias_CaldariNavy = 732,

    /// <summary>Officially sanctioned Gallente Navy insignias.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Officially sanctioned Gallente Navy insignias.")]
    TradeGoods_Insignias_GallenteNavy = 734,

    /// <summary>Individual identification tags.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Individual identification tags.")]
    TradeGoods_Insignias_Individuals = 737,

    /// <summary>Officially sanctioned Khanid Navy insignias.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Officially sanctioned Khanid Navy insignias.")]
    TradeGoods_Insignias_KhanidNavy = 735,

    /// <summary>Officially sanctioned Minmatar Fleet insignias.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Officially sanctioned Minmatar Fleet insignias.")]
    TradeGoods_Insignias_MinmatarFleet = 736,

    /// <summary>Substances that tinker with brain chemistry and induce altered states.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Substances that tinker with brain chemistry and induce altered states.")]
    TradeGoods_Narcotics = 491,

    /// <summary>For storage of artificial intelligence systems.</summary>
    
    [System.ComponentModel.DescriptionAttribute("For storage of artificial intelligence systems.")]
    TradeGoods_NexusChips = 738,

    /// <summary>Living, breathing cargo.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Living, breathing cargo.")]
    TradeGoods_Passengers = 23,

    /// <summary>Special ISK-priced capsuleering licenses offered as an alternative to regular piloting contracts.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Special ISK-priced capsuleering licenses offered as an alternative to regular pil" +
        "oting contracts.")]
    TradeGoods_PilotsLicenseExtensionsPlex = 1108,

    /// <summary>Political propaganda & those that engage in it.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Political propaganda & those that engage in it.")]
    TradeGoods_PoliticalParaphernalia = 754,

    /// <summary>Chemicals and waste, dripping with radiation. Handle with caution.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Chemicals and waste, dripping with radiation. Handle with caution.")]
    TradeGoods_RadioactiveGoods = 22,

    /// <summary>Mysterious pieces of technology of Sleeper origin.</summary>
    
    [System.ComponentModel.DescriptionAttribute("Mysterious pieces of technology of Sleeper origin.")]
    TradeGoods_SleeperComponents = 1109,

    /// <summary>The required licences to operate starbases within the borders of the empires.</summary>
    
    [System.ComponentModel.DescriptionAttribute("The required licences to operate starbases within the borders of the empires.")]
    TradeGoods_StarbaseCharters = 940,
  }
}
