// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve {
  using System.CodeDom.Compiler;
  using System.ComponentModel;


  /// <summary>Contains the ID values associated with the MetaGroup class.</summary>
  [GeneratedCode("Eve", "1.76.447.22983")]
  [Description("Contains the ID values associated with the MetaGroup class.")]
  public enum MetaGroupId : short {

    /// <summary>Tech I</summary>
    
    TechI = 1,

    /// <summary>Tech II</summary>
    
    TechII = 2,

    /// <summary>Storyline</summary>
    
    Storyline = 3,

    /// <summary>Faction</summary>
    
    Faction = 4,

    /// <summary>Officer</summary>
    
    Officer = 5,

    /// <summary>Modules found in deadspace.</summary>
    [Description("Modules found in deadspace.")]
    
    Deadspace = 6,

    /// <summary>Frigates</summary>
    
    Frigates = 7,

    /// <summary>Elite Frigates</summary>
    
    EliteFrigates = 8,

    /// <summary>Commander Frigates</summary>
    
    CommanderFrigates = 9,

    /// <summary>Destroyer</summary>
    
    Destroyer = 10,

    /// <summary>Cruiser</summary>
    
    Cruiser = 11,

    /// <summary>Elite Cruiser</summary>
    
    EliteCruiser = 12,

    /// <summary>Commander Cruiser</summary>
    
    CommanderCruiser = 13,

    /// <summary>Tech III</summary>
    
    TechIII = 14,
  }
}
