// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the MetaGroup class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the MetaGroup class.")]
  public enum MetaGroupId : short
  {

    /// <summary>Tech I</summary>
    [Description("Tech I")]
    TechI = 1,

    /// <summary>Tech II</summary>
    [Description("Tech II")]
    TechII = 2,

    /// <summary>Storyline</summary>
    [Description("Storyline")]
    Storyline = 3,

    /// <summary>Faction</summary>
    [Description("Faction")]
    Faction = 4,

    /// <summary>Officer</summary>
    [Description("Officer")]
    Officer = 5,

    /// <summary>Modules found in deadspace.</summary>
    [Description("Deadspace")]
    [LongDescription("Modules found in deadspace.")]
    Deadspace = 6,

    /// <summary>Frigates</summary>
    [Description("Frigates")]
    Frigates = 7,

    /// <summary>Elite Frigates</summary>
    [Description("Elite Frigates")]
    EliteFrigates = 8,

    /// <summary>Commander Frigates</summary>
    [Description("Commander Frigates")]
    CommanderFrigates = 9,

    /// <summary>Destroyer</summary>
    [Description("Destroyer")]
    Destroyer = 10,

    /// <summary>Cruiser</summary>
    [Description("Cruiser")]
    Cruiser = 11,

    /// <summary>Elite Cruiser</summary>
    [Description("Elite Cruiser")]
    EliteCruiser = 12,

    /// <summary>Commander Cruiser</summary>
    [Description("Commander Cruiser")]
    CommanderCruiser = 13,

    /// <summary>Tech III</summary>
    [Description("Tech III")]
    TechIII = 14,
  }
}
