// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the Unit class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the Unit class.")]
  public enum UnitId : byte
  {

    /// <summary>Meter</summary>
    [Description("Length")]
    [LongDescription("Meter")]
    Length = 1,

    /// <summary>Kilogram</summary>
    [Description("Mass")]
    [LongDescription("Kilogram")]
    Mass = 2,

    /// <summary>Second</summary>
    [Description("Time")]
    [LongDescription("Second")]
    Time = 3,

    /// <summary>Ampere</summary>
    [Description("Electric Current")]
    [LongDescription("Ampere")]
    ElectricCurrent = 4,

    /// <summary>Kelvin</summary>
    [Description("Temperature")]
    [LongDescription("Kelvin")]
    Temperature = 5,

    /// <summary>Mole</summary>
    [Description("Amount Of Substance")]
    [LongDescription("Mole")]
    AmountOfSubstance = 6,

    /// <summary>Candela</summary>
    [Description("Luminous Intensity")]
    [LongDescription("Candela")]
    LuminousIntensity = 7,

    /// <summary>Square meter</summary>
    [Description("Area")]
    [LongDescription("Square meter")]
    Area = 8,

    /// <summary>Cubic meter</summary>
    [Description("Volume")]
    [LongDescription("Cubic meter")]
    Volume = 9,

    /// <summary>Meter per second</summary>
    [Description("Speed")]
    [LongDescription("Meter per second")]
    Speed = 10,

    /// <summary>Meter per second squared</summary>
    [Description("Acceleration")]
    [LongDescription("Meter per second squared")]
    Acceleration = 11,

    /// <summary>Reciprocal meter</summary>
    [Description("Wave Number")]
    [LongDescription("Reciprocal meter")]
    WaveNumber = 12,

    /// <summary>Kilogram per cubic meter</summary>
    [Description("Mass Density")]
    [LongDescription("Kilogram per cubic meter")]
    MassDensity = 13,

    /// <summary>Cubic meter per kilogram</summary>
    [Description("Specific Volume")]
    [LongDescription("Cubic meter per kilogram")]
    SpecificVolume = 14,

    /// <summary>Ampere per square meter</summary>
    [Description("Current Density")]
    [LongDescription("Ampere per square meter")]
    CurrentDensity = 15,

    /// <summary>Ampere per meter</summary>
    [Description("Magnetic Field Strength")]
    [LongDescription("Ampere per meter")]
    MagneticFieldStrength = 16,

    /// <summary>Mole per cubic meter</summary>
    [Description("Amount-Of-Substance Concentration")]
    [LongDescription("Mole per cubic meter")]
    AmountOfSubstanceConcentration = 17,

    /// <summary>Candela per square meter</summary>
    [Description("Luminance")]
    [LongDescription("Candela per square meter")]
    Luminance = 18,

    /// <summary>Kilogram per kilogram, which may be represented by the number 1</summary>
    [Description("Mass Fraction")]
    [LongDescription("Kilogram per kilogram, which may be represented by the number 1")]
    MassFraction = 19,

    /// <summary>Milliseconds</summary>
    [Description("Milliseconds")]
    Milliseconds = 101,

    /// <summary>Millimeters</summary>
    [Description("Millimeters")]
    Millimeters = 102,

    /// <summary>MegaPascals</summary>
    [Description("MegaPascals")]
    MegaPascals = 103,

    /// <summary>Indicates that the unit is a multiplier.</summary>
    [Description("Multiplier")]
    [LongDescription("Indicates that the unit is a multiplier.")]
    Multiplier = 104,

    /// <summary>Percentage</summary>
    [Description("Percentage")]
    Percentage = 105,

    /// <summary>Teraflops</summary>
    [Description("Teraflops")]
    Teraflops = 106,

    /// <summary>MegaWatts</summary>
    [Description("MegaWatts")]
    MegaWatts = 107,

    /// <summary>Used for resistance.
    ///0.0 = 100% 1.0 = 0%
    ///</summary>
    [Description("Inverse Absolute Percent")]
    [LongDescription("Used for resistance.\r\n0.0 = 100% 1.0 = 0%\r\n")]
    InverseAbsolutePercent = 108,

    /// <summary>Used for multipliers displayed as %
    ///1.1 = +10%
    ///0.9 = -10%</summary>
    [Description("Modifier Percent")]
    [LongDescription("Used for multipliers displayed as %\r\n1.1 = +10%\r\n0.9 = -10%")]
    ModifierPercent = 109,

    /// <summary>Used to modify damage resistance. Damage resistance bonus.
    ///0.1 = 90%
    ///0.9 = 10%</summary>
    [Description("Inversed Modifier Percent")]
    [LongDescription("Used to modify damage resistance. Damage resistance bonus.\r\n0.1 = 90%\r\n0.9 = 10%")]
    InversedModifierPercent = 111,

    /// <summary>Rotation speed.</summary>
    [Description("Radians/Second")]
    [LongDescription("Rotation speed.")]
    RadiansSecond = 112,

    /// <summary>Hitpoints</summary>
    [Description("Hitpoints")]
    Hitpoints = 113,

    /// <summary>Giga Joule</summary>
    [Description("capacitor units")]
    [LongDescription("Giga Joule")]
    CapacitorUnits = 114,

    /// <summary>groupID</summary>
    [Description("groupID")]
    GroupId = 115,

    /// <summary>typeID</summary>
    [Description("typeID")]
    TypeId = 116,

    /// <summary>Sizeclass</summary>
    [Description("Sizeclass")]
    Sizeclass = 117,

    /// <summary>Ore units</summary>
    [Description("Ore units")]
    OreUnits = 118,

    /// <summary>attributeID</summary>
    [Description("attributeID")]
    AttributeId = 119,

    /// <summary>attributePoints</summary>
    [Description("attributePoints")]
    AttributePoints = 120,

    /// <summary>Used for real percentages, i.e. the number 5 is 5%</summary>
    [Description("realPercent")]
    [LongDescription("Used for real percentages, i.e. the number 5 is 5%")]
    RealPercent = 121,

    /// <summary>Fitting slots</summary>
    [Description("Fitting slots")]
    FittingSlots = 122,

    /// <summary>Shows seconds directly</summary>
    [Description("trueTime")]
    [LongDescription("Shows seconds directly")]
    TrueTime = 123,

    /// <summary>Used for relative percentages displayed as %</summary>
    [Description("Modifier Relative Percent")]
    [LongDescription("Used for relative percentages displayed as %")]
    ModifierRelativePercent = 124,

    /// <summary>Newton</summary>
    [Description("Newton")]
    Newton = 125,

    /// <summary>Light Year</summary>
    [Description("Light Year")]
    LightYear = 126,

    /// <summary>0.0 = 0% 1.0 = 100%</summary>
    [Description("Absolute Percent")]
    [LongDescription("0.0 = 0% 1.0 = 100%")]
    AbsolutePercent = 127,

    /// <summary>Mega bits per second</summary>
    [Description("Drone bandwidth")]
    [LongDescription("Mega bits per second")]
    DroneBandwidth = 128,

    /// <summary>Hours</summary>
    [Description("Hours")]
    [LongDescription("Hours")]
    Hours = 129,

    /// <summary>ISK</summary>
    [Description("Money")]
    [LongDescription("ISK")]
    Money = 133,

    /// <summary>Bandwidth for PI</summary>
    [Description("Logistical Capacity")]
    [LongDescription("Bandwidth for PI")]
    LogisticalCapacity = 134,

    /// <summary>Used to denote distance, 1AU = The distance from the Earth to the Sun.</summary>
    [Description("Astronomical Unit")]
    [LongDescription("Used to denote distance, 1AU = The distance from the Earth to the Sun.")]
    AstronomicalUnit = 135,

    /// <summary>Slot number prefix for various purposes</summary>
    [Description("Slot")]
    [LongDescription("Slot number prefix for various purposes")]
    Slot = 136,

    /// <summary>For displaying boolean flags</summary>
    [Description("Boolean")]
    [LongDescription("For displaying boolean flags")]
    Boolean = 137,

    /// <summary>Units of something, for example fuel</summary>
    [Description("Units")]
    [LongDescription("Units of something, for example fuel")]
    Units = 138,

    /// <summary>Forces a plus sign for positive values</summary>
    [Description("Bonus")]
    [LongDescription("Forces a plus sign for positive values")]
    Bonus = 139,

    /// <summary>For anything which is divided by levels</summary>
    [Description("Level")]
    [LongDescription("For anything which is divided by levels")]
    Level = 140,

    /// <summary>For various counts to do with turret, launcher and rig hardpoints</summary>
    [Description("Hardpoints")]
    [LongDescription("For various counts to do with turret, launcher and rig hardpoints")]
    Hardpoints = 141,

    /// <summary>Sex</summary>
    [Description("Sex")]
    Sex = 142,
  }
}
