// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe {


  /// <summary>Contains the ID values associated with the AgentType class.</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Eve.Meta", "1.76.447.37160")]
  [System.ComponentModel.DescriptionAttribute("Contains the ID values associated with the AgentType class.")]
  public enum AgentTypeId : int {

    [FreeNet.Globalization.LocalizedLabelAttribute("NonAgent", "Eve.Universe.AgentTypeID_NonAgent")]
    NonAgent = 1,

    [FreeNet.Globalization.LocalizedLabelAttribute("BasicAgent", "Eve.Universe.AgentTypeID_BasicAgent")]
    BasicAgent = 2,

    [FreeNet.Globalization.LocalizedLabelAttribute("TutorialAgent", "Eve.Universe.AgentTypeID_TutorialAgent")]
    TutorialAgent = 3,

    [FreeNet.Globalization.LocalizedLabelAttribute("ResearchAgent", "Eve.Universe.AgentTypeID_ResearchAgent")]
    ResearchAgent = 4,

    [FreeNet.Globalization.LocalizedLabelAttribute("CONCORDAgent", "Eve.Universe.AgentTypeID_ConcordAgent")]
    ConcordAgent = 5,

    [FreeNet.Globalization.LocalizedLabelAttribute("GenericStorylineMissionAgent", "Eve.Universe.AgentTypeID_GenericStorylineMissionAgent")]
    GenericStorylineMissionAgent = 6,

    [FreeNet.Globalization.LocalizedLabelAttribute("StorylineMissionAgent", "Eve.Universe.AgentTypeID_StorylineMissionAgent")]
    StorylineMissionAgent = 7,

    [FreeNet.Globalization.LocalizedLabelAttribute("EventMissionAgent", "Eve.Universe.AgentTypeID_EventMissionAgent")]
    EventMissionAgent = 8,

    [FreeNet.Globalization.LocalizedLabelAttribute("FactionalWarfareAgent", "Eve.Universe.AgentTypeID_FactionalWarfareAgent")]
    FactionalWarfareAgent = 9,

    [FreeNet.Globalization.LocalizedLabelAttribute("EpicArcAgent", "Eve.Universe.AgentTypeID_EpicArcAgent")]
    EpicArcAgent = 10,

    [FreeNet.Globalization.LocalizedLabelAttribute("AuraAgent", "Eve.Universe.AgentTypeID_AuraAgent")]
    AuraAgent = 11,

    [FreeNet.Globalization.LocalizedLabelAttribute("CareerAgent", "Eve.Universe.AgentTypeID_CareerAgent")]
    CareerAgent = 12,
  }
}
