//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eve.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category cannot be null..
        /// </summary>
        public static string AttributeType_CategoryCannotBeNull {
            get {
                return ResourceManager.GetString("AttributeType_CategoryCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value must be a finite numeric value..
        /// </summary>
        public static string AttributeType_DefaultValueMustBeNumeric {
            get {
                return ResourceManager.GetString("AttributeType_DefaultValueMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute type cannot be null..
        /// </summary>
        public static string AttributeValue_AttributeTypeCannotBeNull {
            get {
                return ResourceManager.GetString("AttributeValue_AttributeTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item type cannot be null..
        /// </summary>
        public static string AttributeValue_ItemTypeCannotBeNull {
            get {
                return ResourceManager.GetString("AttributeValue_ItemTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a finite numeric value..
        /// </summary>
        public static string AttributeValue_ValueMustBeNumeric {
            get {
                return ResourceManager.GetString("AttributeValue_ValueMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description cannot be null..
        /// </summary>
        public static string BaseValue_DescriptionCannotBeNull {
            get {
                return ResourceManager.GetString("BaseValue_DescriptionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID cannot be null..
        /// </summary>
        public static string BaseValue_IdCannotBeNull {
            get {
                return ResourceManager.GetString("BaseValue_IdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be null or empty..
        /// </summary>
        public static string BaseValue_NameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("BaseValue_NameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID value cannot be null..
        /// </summary>
        public static string BaseValueCache_IdCannotBeNull {
            get {
                return ResourceManager.GetString("BaseValueCache_IdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item cannot be null..
        /// </summary>
        public static string BaseValueCache_ItemCannotBeNull {
            get {
                return ResourceManager.GetString("BaseValueCache_ItemCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item type cannot be null..
        /// </summary>
        public static string BaseValueCache_ItemTypeCannotBeNull {
            get {
                return ResourceManager.GetString("BaseValueCache_ItemTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The region cannot be null..
        /// </summary>
        public static string BaseValueCache_RegionCannotBeNull {
            get {
                return ResourceManager.GetString("BaseValueCache_RegionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null..
        /// </summary>
        public static string BaseValueCache_ValueCannotBeNull {
            get {
                return ResourceManager.GetString("BaseValueCache_ValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity cannot be null..
        /// </summary>
        public static string EntityAdapter_EntityCannotBeNull {
            get {
                return ResourceManager.GetString("EntityAdapter_EntityCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache cannot be null..
        /// </summary>
        public static string EveCache_CacheCannotBeNull {
            get {
                return ResourceManager.GetString("EveCache_CacheCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache size cannot be less than zero..
        /// </summary>
        public static string EveCache_CacheSizeCannotBeNegative {
            get {
                return ResourceManager.GetString("EveCache_CacheSizeCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the generated value must match the provided ID..
        /// </summary>
        public static string EveCache_GeneratedValueHasInvalidId {
            get {
                return ResourceManager.GetString("EveCache_GeneratedValueHasInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID cannot be null..
        /// </summary>
        public static string EveCache_IdCannotBeNull {
            get {
                return ResourceManager.GetString("EveCache_IdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to add cannot be null..
        /// </summary>
        public static string EveCache_ValueCannotBeNull {
            get {
                return ResourceManager.GetString("EveCache_ValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method to generate a value to add cannot be null..
        /// </summary>
        public static string EveCache_ValueFactoryCannotBeNull {
            get {
                return ResourceManager.GetString("EveCache_ValueFactoryCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache cannot be null..
        /// </summary>
        public static string General_CacheCannotBeNull {
            get {
                return ResourceManager.GetString("General_CacheCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EVE data source cannot be null..
        /// </summary>
        public static string General_DataSourceCannotBeNull {
            get {
                return ResourceManager.GetString("General_DataSourceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings manager cannot be null..
        /// </summary>
        public static string General_SettingsCannotBeNull {
            get {
                return ResourceManager.GetString("General_SettingsCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category cannot be null..
        /// </summary>
        public static string Group_CategoryCannotBeNull {
            get {
                return ResourceManager.GetString("Group_CategoryCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon file cannot be null..
        /// </summary>
        public static string Icon_IconFileCannotBeNull {
            get {
                return ResourceManager.GetString("Icon_IconFileCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache cannot be null..
        /// </summary>
        public static string IEveDataSource_CacheCannotBeNull {
            get {
                return ResourceManager.GetString("IEveDataSource_CacheCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter cannot be null..
        /// </summary>
        public static string IEveDataSource_FilterCannotBeNull {
            get {
                return ResourceManager.GetString("IEveDataSource_FilterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID value cannot be null..
        /// </summary>
        public static string IEveDataSource_IdCannotBeNull {
            get {
                return ResourceManager.GetString("IEveDataSource_IdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query modifier cannot be null..
        /// </summary>
        public static string IEveDataSource_QueryModifierCannotBeNull {
            get {
                return ResourceManager.GetString("IEveDataSource_QueryModifierCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capacity must be a finite numeric value..
        /// </summary>
        public static string ItemType_CapacityMustBeNumeric {
            get {
                return ResourceManager.GetString("ItemType_CapacityMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chance of duplicating must be a finite numeric value..
        /// </summary>
        public static string ItemType_ChanceOfDuplicatingMustBeNumeric {
            get {
                return ResourceManager.GetString("ItemType_ChanceOfDuplicatingMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group cannot be null..
        /// </summary>
        public static string ItemType_GroupCannotBeNull {
            get {
                return ResourceManager.GetString("ItemType_GroupCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mass must be a finite numeric value..
        /// </summary>
        public static string ItemType_MassMustBeNumeric {
            get {
                return ResourceManager.GetString("ItemType_MassMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume must be a finite numeric value..
        /// </summary>
        public static string ItemType_VolumeMustBeNumeric {
            get {
                return ResourceManager.GetString("ItemType_VolumeMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numeric portion cannot be null..
        /// </summary>
        public static string Unit_NumericPortionCannotBeNull {
            get {
                return ResourceManager.GetString("Unit_NumericPortionCannotBeNull", resourceCulture);
            }
        }
    }
}
