// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Character
{
  using System;
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the Ancestry class.</summary>
  [GeneratedCode("Eve.Meta", "1.0.0.0")]
  [Description("Contains the ID values associated with the Ancestry class.")]
  public enum AncestryId : byte
  {

    /// <summary>Liberal Holders</summary>
    [Description("Liberal Holders")]
    LiberalHolders = 1,

    /// <summary>Wealthy Commoners</summary>
    [Description("Wealthy Commoners")]
    WealthyCommoners = 2,

    /// <summary>Religious Reclaimers</summary>
    [Description("Religious Reclaimers")]
    ReligiousReclaimers = 3,

    /// <summary>Free Merchants</summary>
    [Description("Free Merchants")]
    FreeMerchants = 4,

    /// <summary>Border Runners</summary>
    [Description("Border Runners")]
    BorderRunners = 5,

    /// <summary>Navy Veterans</summary>
    [Description("Navy Veterans")]
    NavyVeterans = 6,

    /// <summary>Entrepreneurs</summary>
    [Description("Entrepreneurs")]
    Entrepreneurs = 7,

    /// <summary>Mercs</summary>
    [Description("Mercs")]
    Mercs = 8,

    /// <summary>Dissenters</summary>
    [Description("Dissenters")]
    Dissenters = 9,

    /// <summary>Merchandisers</summary>
    [Description("Merchandisers")]
    Merchandisers = 10,

    /// <summary>Scientists</summary>
    [Description("Scientists")]
    Scientists = 11,

    /// <summary>Tube Child</summary>
    [Description("Tube Child")]
    TubeChild = 12,

    /// <summary>Activists</summary>
    [Description("Activists")]
    Activists = 13,

    /// <summary>Miners</summary>
    [Description("Miners")]
    Miners = 14,

    /// <summary>Immigrants</summary>
    [Description("Immigrants")]
    Immigrants = 15,

    /// <summary>Artists</summary>
    [Description("Artists")]
    Artists = 16,

    /// <summary>Diplomats</summary>
    [Description("Diplomats")]
    Diplomats = 17,

    /// <summary>Reborn</summary>
    [Description("Reborn")]
    Reborn = 18,

    /// <summary>Tinkerers</summary>
    [Description("Tinkerers")]
    Tinkerers = 19,

    /// <summary>Traders</summary>
    [Description("Traders")]
    Traders = 20,

    /// <summary>Rebels</summary>
    [Description("Rebels")]
    Rebels = 21,

    /// <summary>Workers</summary>
    [Description("Workers")]
    Workers = 22,

    /// <summary>Tribal Traditionalists</summary>
    [Description("Tribal Traditionalists")]
    TribalTraditionalists = 23,

    /// <summary>Slave Child</summary>
    [Description("Slave Child")]
    SlaveChild = 24,

    /// <summary>Elders</summary>
    [Description("Elders")]
    Elders = 25,

    /// <summary>Unsullied</summary>
    [Description("Unsullied")]
    Unsullied = 26,

    /// <summary>Stasis People</summary>
    [Description("Stasis People")]
    StasisPeople = 27,

    /// <summary>Existentialists</summary>
    [Description("Existentialists")]
    Existentialists = 28,

    /// <summary>Puritan</summary>
    [Description("Puritan")]
    Puritan = 29,

    /// <summary>Lab Rat</summary>
    [Description("Lab Rat")]
    LabRat = 30,

    /// <summary>Inventors</summary>
    [Description("Inventors")]
    Inventors = 31,

    /// <summary>Monks</summary>
    [Description("Monks")]
    Monks = 32,

    /// <summary>Stargazers</summary>
    [Description("Stargazers")]
    Stargazers = 33,

    /// <summary>Sang Do Caste</summary>
    [Description("Sang Do Caste")]
    SangDoCaste = 34,

    /// <summary>Saan Go Caste</summary>
    [Description("Saan Go Caste")]
    SaanGoCaste = 35,

    /// <summary>Jing Ko Caste</summary>
    [Description("Jing Ko Caste")]
    JingKoCaste = 36,

    /// <summary>Cyber Knights</summary>
    [Description("Cyber Knights")]
    CyberKnights = 37,

    /// <summary>Unionists</summary>
    [Description("Unionists")]
    Unionists = 38,

    /// <summary>Zealots</summary>
    [Description("Zealots")]
    Zealots = 39,

    /// <summary>Drifters</summary>
    [Description("Drifters")]
    Drifters = 40,

    /// <summary>Mystics</summary>
    [Description("Mystics")]
    Mystics = 41,

    /// <summary>Retailers</summary>
    [Description("Retailers")]
    Retailers = 42,
  }
}
