// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Character
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the Bloodline class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the Bloodline class.")]
  public enum BloodlineId : byte
  {

    /// <summary>Deteis</summary>
    [Description("Deteis")]
    Deteis = 1,

    /// <summary>Civire</summary>
    [Description("Civire")]
    Civire = 2,

    /// <summary>Sebiestor</summary>
    [Description("Sebiestor")]
    Sebiestor = 3,

    /// <summary>Brutor</summary>
    [Description("Brutor")]
    Brutor = 4,

    /// <summary>Amarr</summary>
    [Description("Amarr")]
    Amarr = 5,

    /// <summary>Ni-Kunni</summary>
    [Description("Ni-Kunni")]
    NiKunni = 6,

    /// <summary>Gallente</summary>
    [Description("Gallente")]
    Gallente = 7,

    /// <summary>Intaki</summary>
    [Description("Intaki")]
    Intaki = 8,

    /// <summary>Static</summary>
    [Description("Static")]
    Static = 9,

    /// <summary>Modifier</summary>
    [Description("Modifier")]
    Modifier = 10,

    /// <summary>Achura</summary>
    [Description("Achura")]
    Achura = 11,

    /// <summary>Jin-Mei</summary>
    [Description("Jin-Mei")]
    JinMei = 12,

    /// <summary>Khanid</summary>
    [Description("Khanid")]
    Khanid = 13,

    /// <summary>Vherokior</summary>
    [Description("Vherokior")]
    Vherokior = 14,
  }
}
