// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Character {
  using System.CodeDom.Compiler;
  using System.ComponentModel;


  /// <summary>Contains the ID values associated with the Bloodline class.</summary>
  [GeneratedCode("Eve", "1.76.447.37901")]
  [Description("Contains the ID values associated with the Bloodline class.")]
  public enum BloodlineId : byte {

    /// <summary>Deteis</summary>
    Deteis = 1,

    /// <summary>Civire</summary>
    Civire = 2,

    /// <summary>Sebiestor</summary>
    Sebiestor = 3,

    /// <summary>Brutor</summary>
    Brutor = 4,

    /// <summary>Amarr</summary>
    Amarr = 5,

    /// <summary>Ni-Kunni</summary>
    NiKunni = 6,

    /// <summary>Gallente</summary>
    Gallente = 7,

    /// <summary>Intaki</summary>
    Intaki = 8,

    /// <summary>Static</summary>
    Static = 9,

    /// <summary>Modifier</summary>
    Modifier = 10,

    /// <summary>Achura</summary>
    Achura = 11,

    /// <summary>Jin-Mei</summary>
    JinMei = 12,

    /// <summary>Khanid</summary>
    Khanid = 13,

    /// <summary>Vherokior</summary>
    Vherokior = 14,
  }
}
