// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Character
{
  using System;
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the CertificateCategory class.</summary>
  [GeneratedCode("Eve.Meta", "1.0.0.0")]
  [Description("Contains the ID values associated with the CertificateCategory class.")]
  public enum CertificateCategoryId : byte
  {

    /// <summary>Core Certificates</summary>
    [Description("Core")]
    [LongDescription("Core Certificates")]
    Core = 3,

    /// <summary>Starter Professions</summary>
    [Description("Starter Professions")]
    [LongDescription("Starter Professions")]
    StarterProfessions = 4,

    /// <summary>Defense</summary>
    [Description("Defense")]
    [LongDescription("Defense")]
    Defense = 5,

    /// <summary>Gunnery</summary>
    [Description("Gunnery")]
    [LongDescription("Gunnery")]
    Gunnery = 6,

    /// <summary>Missiles</summary>
    [Description("Missiles")]
    [LongDescription("Missiles")]
    Missiles = 7,

    /// <summary>Drones</summary>
    [Description("Drones")]
    [LongDescription("Drones")]
    Drones = 8,

    /// <summary>Electronic Warfare</summary>
    [Description("Electronic Warfare")]
    [LongDescription("Electronic Warfare")]
    ElectronicWarfare = 9,

    /// <summary>Navigation</summary>
    [Description("Navigation")]
    [LongDescription("Navigation")]
    Navigation = 10,

    /// <summary>Leadership</summary>
    [Description("Leadership")]
    [LongDescription("Leadership")]
    Leadership = 11,

    /// <summary>Harvesting</summary>
    [Description("Harvesting")]
    [LongDescription("Harvesting")]
    Harvesting = 12,

    /// <summary>Business and Industry</summary>
    [Description("Business and Industry")]
    [LongDescription("Business and Industry")]
    BusinessAndIndustry = 13,

    /// <summary>Colony Management</summary>
    [Description("Planetary Interaction")]
    [LongDescription("Colony Management")]
    PlanetaryInteraction = 18,
  }
}
