// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Character
{
  using System;
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the CertificateClass class.</summary>
  [GeneratedCode("Eve.Meta", "1.0.0.0")]
  [Description("Contains the ID values associated with the CertificateClass class.")]
  public enum CertificateClassId : int
  {

    /// <summary>Core Fitting</summary>
    [Description("Core Fitting")]
    [LongDescription("Core Fitting")]
    CoreFitting = 2,

    /// <summary>Core Capacitor</summary>
    [Description("Core Capacitor")]
    [LongDescription("Core Capacitor")]
    CoreCapacitor = 3,

    /// <summary>Core Targeting</summary>
    [Description("Core Targeting")]
    [LongDescription("Core Targeting")]
    CoreTargeting = 4,

    /// <summary>Core Navigation</summary>
    [Description("Core Navigation")]
    [LongDescription("Core Navigation")]
    CoreNavigation = 5,

    /// <summary>Core Competency</summary>
    [Description("Core Competency")]
    [LongDescription("Core Competency")]
    CoreCompetency = 6,

    /// <summary>Core Integrity</summary>
    [Description("Core Integrity")]
    [LongDescription("Core Integrity")]
    CoreIntegrity = 7,

    /// <summary>Amarr Military - Soldier</summary>
    [Description("Amarr Military - Soldier")]
    [LongDescription("Amarr Military - Soldier")]
    AmarrMilitarySoldier = 8,

    /// <summary>Amarr Military - Special Forces</summary>
    [Description("Amarr Military - Special Forces")]
    [LongDescription("Amarr Military - Special Forces")]
    AmarrMilitarySpecialForces = 9,

    /// <summary>Amarr Industry - Engineer</summary>
    [Description("Amarr Industry - Engineer")]
    [LongDescription("Amarr Industry - Engineer")]
    AmarrIndustryEngineer = 10,

    /// <summary>Amarr Industry - Prospector</summary>
    [Description("Amarr Industry - Prospector")]
    [LongDescription("Amarr Industry - Prospector")]
    AmarrIndustryProspector = 11,

    /// <summary>Amarr Business - Entrepreneur</summary>
    [Description("Amarr Business - Entrepreneur")]
    [LongDescription("Amarr Business - Entrepreneur")]
    AmarrBusinessEntrepreneur = 12,

    /// <summary>Amarr Business - Executive Commander</summary>
    [Description("Amarr Business - Executive Commander")]
    [LongDescription("Amarr Business - Executive Commander")]
    AmarrBusinessExecutiveCommander = 13,

    /// <summary>Caldari Military - Soldier</summary>
    [Description("Caldari Military - Soldier")]
    [LongDescription("Caldari Military - Soldier")]
    CaldariMilitarySoldier = 14,

    /// <summary>Caldari Military - Special Forces</summary>
    [Description("Caldari Military - Special Forces")]
    [LongDescription("Caldari Military - Special Forces")]
    CaldariMilitarySpecialForces = 15,

    /// <summary>Caldari Industry - Engineer</summary>
    [Description("Caldari Industry - Engineer")]
    [LongDescription("Caldari Industry - Engineer")]
    CaldariIndustryEngineer = 16,

    /// <summary>Caldari Industry - Prospector</summary>
    [Description("Caldari Industry - Prospector")]
    [LongDescription("Caldari Industry - Prospector")]
    CaldariIndustryProspector = 17,

    /// <summary>Caldari Business - Entrepreneur</summary>
    [Description("Caldari Business - Entrepreneur")]
    [LongDescription("Caldari Business - Entrepreneur")]
    CaldariBusinessEntrepreneur = 18,

    /// <summary>Caldari Business - Executive Commander</summary>
    [Description("Caldari Business - Executive Commander")]
    [LongDescription("Caldari Business - Executive Commander")]
    CaldariBusinessExecutiveCommander = 19,

    /// <summary>Gallente Military - Soldier</summary>
    [Description("Gallente Military - Soldier")]
    [LongDescription("Gallente Military - Soldier")]
    GallenteMilitarySoldier = 20,

    /// <summary>Gallente Military - Special Forces</summary>
    [Description("Gallente Military - Special Forces")]
    [LongDescription("Gallente Military - Special Forces")]
    GallenteMilitarySpecialForces = 21,

    /// <summary>Gallente Industry - Engineer</summary>
    [Description("Gallente Industry - Engineer")]
    [LongDescription("Gallente Industry - Engineer")]
    GallenteIndustryEngineer = 22,

    /// <summary>Gallente Industry - Prospector</summary>
    [Description("Gallente Industry - Prospector")]
    [LongDescription("Gallente Industry - Prospector")]
    GallenteIndustryProspector = 23,

    /// <summary>Gallente Business - Entrepreneur</summary>
    [Description("Gallente Business - Entrepreneur")]
    [LongDescription("Gallente Business - Entrepreneur")]
    GallenteBusinessEntrepreneur = 24,

    /// <summary>Gallente Business - Executive Commander</summary>
    [Description("Gallente Business - Executive Commander")]
    [LongDescription("Gallente Business - Executive Commander")]
    GallenteBusinessExecutiveCommander = 25,

    /// <summary>Minmatar Military - Soldier</summary>
    [Description("Minmatar Military - Soldier")]
    [LongDescription("Minmatar Military - Soldier")]
    MinmatarMilitarySoldier = 26,

    /// <summary>Minmatar Military - Special Forces</summary>
    [Description("Minmatar Military - Special Forces")]
    [LongDescription("Minmatar Military - Special Forces")]
    MinmatarMilitarySpecialForces = 27,

    /// <summary>Minmatar Industry - Engineer</summary>
    [Description("Minmatar Industry - Engineer")]
    [LongDescription("Minmatar Industry - Engineer")]
    MinmatarIndustryEngineer = 28,

    /// <summary>Minmatar Industry - Prospector</summary>
    [Description("Minmatar Industry - Prospector")]
    [LongDescription("Minmatar Industry - Prospector")]
    MinmatarIndustryProspector = 29,

    /// <summary>Minmatar Business - Entrepreneur</summary>
    [Description("Minmatar Business - Entrepreneur")]
    [LongDescription("Minmatar Business - Entrepreneur")]
    MinmatarBusinessEntrepreneur = 30,

    /// <summary>Minmatar Business - Executive Commander</summary>
    [Description("Minmatar Business - Executive Commander")]
    [LongDescription("Minmatar Business - Executive Commander")]
    MinmatarBusinessExecutiveCommander = 31,

    /// <summary>Armor Tanking</summary>
    [Description("Armor Tanking")]
    [LongDescription("Armor Tanking")]
    ArmorTanking = 32,

    /// <summary>Armor Reinforcement</summary>
    [Description("Armor Reinforcement")]
    [LongDescription("Armor Reinforcement")]
    ArmorReinforcement = 33,

    /// <summary>Active Shield Tanking</summary>
    [Description("Active Shield Tanking")]
    [LongDescription("Active Shield Tanking")]
    ActiveShieldTanking = 34,

    /// <summary>Passive Shield Tanking</summary>
    [Description("Passive Shield Tanking")]
    [LongDescription("Passive Shield Tanking")]
    PassiveShieldTanking = 35,

    /// <summary>Shield Reinforcement</summary>
    [Description("Shield Reinforcement")]
    [LongDescription("Shield Reinforcement")]
    ShieldReinforcement = 36,

    /// <summary>Hull Tanking</summary>
    [Description("Hull Tanking")]
    [LongDescription("Hull Tanking")]
    HullTanking = 37,

    /// <summary>Logistics Chief</summary>
    [Description("Logistics Chief")]
    [LongDescription("Logistics Chief")]
    LogisticsChief = 38,

    /// <summary>Turret Control</summary>
    [Description("Turret Control")]
    [LongDescription("Turret Control")]
    TurretControl = 39,

    /// <summary>Frigate Energy Turrets</summary>
    [Description("Frigate Energy Turrets")]
    [LongDescription("Frigate Energy Turrets")]
    FrigateEnergyTurrets = 40,

    /// <summary>Frigate Advanced Pulse Turrets</summary>
    [Description("Frigate Advanced Pulse Turrets")]
    [LongDescription("Frigate Advanced Pulse Turrets")]
    FrigateAdvancedPulseTurrets = 41,

    /// <summary>Frigate Advanced Beam Turrets</summary>
    [Description("Frigate Advanced Beam Turrets")]
    [LongDescription("Frigate Advanced Beam Turrets")]
    FrigateAdvancedBeamTurrets = 42,

    /// <summary>Cruiser Energy Turrets</summary>
    [Description("Cruiser Energy Turrets")]
    [LongDescription("Cruiser Energy Turrets")]
    CruiserEnergyTurrets = 43,

    /// <summary>Cruiser Advanced Pulse Turrets</summary>
    [Description("Cruiser Advanced Pulse Turrets")]
    [LongDescription("Cruiser Advanced Pulse Turrets")]
    CruiserAdvancedPulseTurrets = 44,

    /// <summary>Cruiser Advanced Beam Turrets</summary>
    [Description("Cruiser Advanced Beam Turrets")]
    [LongDescription("Cruiser Advanced Beam Turrets")]
    CruiserAdvancedBeamTurrets = 45,

    /// <summary>Battleship Energy Turrets</summary>
    [Description("Battleship Energy Turrets")]
    [LongDescription("Battleship Energy Turrets")]
    BattleshipEnergyTurrets = 46,

    /// <summary>Battleship Advanced Pulse Turrets</summary>
    [Description("Battleship Advanced Pulse Turrets")]
    [LongDescription("Battleship Advanced Pulse Turrets")]
    BattleshipAdvancedPulseTurrets = 47,

    /// <summary>Battleship Advanced Beam Turrets</summary>
    [Description("Battleship Advanced Beam Turrets")]
    [LongDescription("Battleship Advanced Beam Turrets")]
    BattleshipAdvancedBeamTurrets = 48,

    /// <summary>Frigate Hybrid Turrets</summary>
    [Description("Frigate Hybrid Turrets")]
    [LongDescription("Frigate Hybrid Turrets")]
    FrigateHybridTurrets = 49,

    /// <summary>Frigate Advanced Blaster Turrets</summary>
    [Description("Frigate Advanced Blaster Turrets")]
    [LongDescription("Frigate Advanced Blaster Turrets")]
    FrigateAdvancedBlasterTurrets = 50,

    /// <summary>Frigate Advanced Rail Turrets</summary>
    [Description("Frigate Advanced Rail Turrets")]
    [LongDescription("Frigate Advanced Rail Turrets")]
    FrigateAdvancedRailTurrets = 51,

    /// <summary>Cruiser Hybrid Turrets</summary>
    [Description("Cruiser Hybrid Turrets")]
    [LongDescription("Cruiser Hybrid Turrets")]
    CruiserHybridTurrets = 52,

    /// <summary>Cruiser Advanced Blaster Turrets</summary>
    [Description("Cruiser Advanced Blaster Turrets")]
    [LongDescription("Cruiser Advanced Blaster Turrets")]
    CruiserAdvancedBlasterTurrets = 53,

    /// <summary>Cruiser Advanced Rail Turrets</summary>
    [Description("Cruiser Advanced Rail Turrets")]
    [LongDescription("Cruiser Advanced Rail Turrets")]
    CruiserAdvancedRailTurrets = 54,

    /// <summary>Battleship Hybrid Turrets</summary>
    [Description("Battleship Hybrid Turrets")]
    [LongDescription("Battleship Hybrid Turrets")]
    BattleshipHybridTurrets = 55,

    /// <summary>Battleship Advanced Blaster Turrets</summary>
    [Description("Battleship Advanced Blaster Turrets")]
    [LongDescription("Battleship Advanced Blaster Turrets")]
    BattleshipAdvancedBlasterTurrets = 56,

    /// <summary>Battleship Advanced Rail Turrets</summary>
    [Description("Battleship Advanced Rail Turrets")]
    [LongDescription("Battleship Advanced Rail Turrets")]
    BattleshipAdvancedRailTurrets = 57,

    /// <summary>Frigate Projectile Turrets</summary>
    [Description("Frigate Projectile Turrets")]
    [LongDescription("Frigate Projectile Turrets")]
    FrigateProjectileTurrets = 58,

    /// <summary>Frigate Advanced Autocannon Turrets</summary>
    [Description("Frigate Advanced Autocannon Turrets")]
    [LongDescription("Frigate Advanced Autocannon Turrets")]
    FrigateAdvancedAutocannonTurrets = 59,

    /// <summary>Frigate Advanced Artillery Turrets</summary>
    [Description("Frigate Advanced Artillery Turrets")]
    [LongDescription("Frigate Advanced Artillery Turrets")]
    FrigateAdvancedArtilleryTurrets = 60,

    /// <summary>Cruiser Projectile Turrets</summary>
    [Description("Cruiser Projectile Turrets")]
    [LongDescription("Cruiser Projectile Turrets")]
    CruiserProjectileTurrets = 61,

    /// <summary>Cruiser Advanced Autocannon Turrets</summary>
    [Description("Cruiser Advanced Autocannon Turrets")]
    [LongDescription("Cruiser Advanced Autocannon Turrets")]
    CruiserAdvancedAutocannonTurrets = 62,

    /// <summary>Cruiser Advanced Artillery Turrets</summary>
    [Description("Cruiser Advanced Artillery Turrets")]
    [LongDescription("Cruiser Advanced Artillery Turrets")]
    CruiserAdvancedArtilleryTurrets = 63,

    /// <summary>Battleship Projectile Turrets</summary>
    [Description("Battleship Projectile Turrets")]
    [LongDescription("Battleship Projectile Turrets")]
    BattleshipProjectileTurrets = 64,

    /// <summary>Battleship Advanced Autocannon Turrets</summary>
    [Description("Battleship Advanced Autocannon Turrets")]
    [LongDescription("Battleship Advanced Autocannon Turrets")]
    BattleshipAdvancedAutocannonTurrets = 65,

    /// <summary>Battleship Advanced Artillery Turrets</summary>
    [Description("Battleship Advanced Artillery Turrets")]
    [LongDescription("Battleship Advanced Artillery Turrets")]
    BattleshipAdvancedArtilleryTurrets = 66,

    /// <summary>Missile Control</summary>
    [Description("Missile Control")]
    [LongDescription("Missile Control")]
    MissileControl = 67,

    /// <summary>Frigate Launcher Control</summary>
    [Description("Frigate Launcher Control")]
    [LongDescription("Frigate Launcher Control")]
    FrigateLauncherControl = 68,

    /// <summary>Frigate Advanced Standard Launchers</summary>
    [Description("Frigate Advanced Standard Launchers")]
    [LongDescription("Frigate Advanced Standard Launchers")]
    FrigateAdvancedStandardLaunchers = 69,

    /// <summary>Frigate Advanced Rocket Launchers</summary>
    [Description("Frigate Advanced Rocket Launchers")]
    [LongDescription("Frigate Advanced Rocket Launchers")]
    FrigateAdvancedRocketLaunchers = 70,

    /// <summary>Cruiser Launcher Control</summary>
    [Description("Cruiser Launcher Control")]
    [LongDescription("Cruiser Launcher Control")]
    CruiserLauncherControl = 71,

    /// <summary>Cruiser Advanced Heavy Launchers</summary>
    [Description("Cruiser Advanced Heavy Launchers")]
    [LongDescription("Cruiser Advanced Heavy Launchers")]
    CruiserAdvancedHeavyLaunchers = 72,

    /// <summary>Cruiser Advanced Heavy Assault Launchers</summary>
    [Description("Cruiser Advanced Heavy Assault Launchers")]
    [LongDescription("Cruiser Advanced Heavy Assault Launchers")]
    CruiserAdvancedHeavyAssaultLaunchers = 73,

    /// <summary>Battleship Launcher Control</summary>
    [Description("Battleship Launcher Control")]
    [LongDescription("Battleship Launcher Control")]
    BattleshipLauncherControl = 74,

    /// <summary>Battleship Advanced Cruise Launchers</summary>
    [Description("Battleship Advanced Cruise Launchers")]
    [LongDescription("Battleship Advanced Cruise Launchers")]
    BattleshipAdvancedCruiseLaunchers = 75,

    /// <summary>Battleship Advanced Siege Launchers</summary>
    [Description("Battleship Advanced Siege Launchers")]
    [LongDescription("Battleship Advanced Siege Launchers")]
    BattleshipAdvancedSiegeLaunchers = 76,

    /// <summary>Drone Control</summary>
    [Description("Drone Control")]
    [LongDescription("Drone Control")]
    DroneControl = 77,

    /// <summary>Combat Drone Control</summary>
    [Description("Combat Drone Control")]
    [LongDescription("Combat Drone Control")]
    CombatDroneControl = 78,

    /// <summary>Heavy Drone Control</summary>
    [Description("Heavy Drone Control")]
    [LongDescription("Heavy Drone Control")]
    HeavyDroneControl = 79,

    /// <summary>Specialist Drone Operator</summary>
    [Description("Specialist Drone Operator")]
    [LongDescription("Specialist Drone Operator")]
    SpecialistDroneOperator = 80,

    /// <summary>Elite Drone Operator</summary>
    [Description("Elite Drone Operator")]
    [LongDescription("Elite Drone Operator")]
    EliteDroneOperator = 81,

    /// <summary>EWAR Operator</summary>
    [Description("EWAR Operator")]
    [LongDescription("EWAR Operator")]
    EwarOperator = 82,

    /// <summary>Cloak Operator</summary>
    [Description("Cloak Operator")]
    [LongDescription("Cloak Operator")]
    CloakOperator = 83,

    /// <summary>Target Painter Operator</summary>
    [Description("Target Painter Operator")]
    [LongDescription("Target Painter Operator")]
    TargetPainterOperator = 84,

    /// <summary>ECM Operator</summary>
    [Description("ECM Operator")]
    [LongDescription("ECM Operator")]
    EcmOperator = 85,

    /// <summary>Sensor Dampener Operator</summary>
    [Description("Sensor Dampener Operator")]
    [LongDescription("Sensor Dampener Operator")]
    SensorDampenerOperator = 86,

    /// <summary>Tracking Disruptor Operator</summary>
    [Description("Tracking Disruptor Operator")]
    [LongDescription("Tracking Disruptor Operator")]
    TrackingDisruptorOperator = 87,

    /// <summary>Propulsion Jammer Operator</summary>
    [Description("Propulsion Jammer Operator")]
    [LongDescription("Propulsion Jammer Operator")]
    PropulsionJammerOperator = 88,

    /// <summary>Interdiction Maneuvers</summary>
    [Description("Interdiction Maneuvers")]
    [LongDescription("Interdiction Maneuvers")]
    InterdictionManeuvers = 89,

    /// <summary>High-Velocity Helmsman</summary>
    [Description("High-Velocity Helmsman")]
    [LongDescription("High-Velocity Helmsman")]
    HighVelocityHelmsman = 90,

    /// <summary>Cartographer</summary>
    [Description("Cartographer")]
    [LongDescription("Cartographer")]
    Cartographer = 91,

    /// <summary>Wormhole Generation</summary>
    [Description("Wormhole Generation")]
    [LongDescription("Wormhole Generation")]
    WormholeGeneration = 92,

    /// <summary>Unit Leader</summary>
    [Description("Unit Leader")]
    [LongDescription("Unit Leader")]
    UnitLeader = 93,

    /// <summary>Tactical Commander</summary>
    [Description("Tactical Commander")]
    [LongDescription("Tactical Commander")]
    TacticalCommander = 94,

    /// <summary>Battlespace Technician</summary>
    [Description("Battlespace Technician")]
    [LongDescription("Battlespace Technician")]
    BattlespaceTechnician = 95,

    /// <summary>Armored Warfare Chief</summary>
    [Description("Armored Warfare Chief")]
    [LongDescription("Armored Warfare Chief")]
    ArmoredWarfareChief = 96,

    /// <summary>Information Warfare Chief</summary>
    [Description("Information Warfare Chief")]
    [LongDescription("Information Warfare Chief")]
    InformationWarfareChief = 97,

    /// <summary>Siege Warfare Chief</summary>
    [Description("Siege Warfare Chief")]
    [LongDescription("Siege Warfare Chief")]
    SiegeWarfareChief = 98,

    /// <summary>Skirmish Warfare Chief</summary>
    [Description("Skirmish Warfare Chief")]
    [LongDescription("Skirmish Warfare Chief")]
    SkirmishWarfareChief = 99,

    /// <summary>Fleet Co-Ordinator</summary>
    [Description("Fleet Co-Ordinator")]
    [LongDescription("Fleet Co-Ordinator")]
    FleetCoOrdinator = 100,

    /// <summary>Harvesting Comptroller</summary>
    [Description("Harvesting Comptroller")]
    [LongDescription("Harvesting Comptroller")]
    HarvestingComptroller = 101,

    /// <summary>Resource Harvester</summary>
    [Description("Resource Harvester")]
    [LongDescription("Resource Harvester")]
    ResourceHarvester = 102,

    /// <summary>Mercoxit Specialist</summary>
    [Description("Mercoxit Specialist")]
    [LongDescription("Mercoxit Specialist")]
    MercoxitSpecialist = 103,

    /// <summary>Industrial Harvesting</summary>
    [Description("Industrial Harvesting")]
    [LongDescription("Industrial Harvesting")]
    IndustrialHarvesting = 104,

    /// <summary>Ice Specialist</summary>
    [Description("Ice Specialist")]
    [LongDescription("Ice Specialist")]
    IceSpecialist = 105,

    /// <summary>Automated Mining</summary>
    [Description("Automated Mining")]
    [LongDescription("Automated Mining")]
    AutomatedMining = 106,

    /// <summary>Refinery Foreman</summary>
    [Description("Refinery Foreman")]
    [LongDescription("Refinery Foreman")]
    RefineryForeman = 108,

    /// <summary>Common Ore Refiner</summary>
    [Description("Common Ore Refiner")]
    [LongDescription("Common Ore Refiner")]
    CommonOreRefiner = 109,

    /// <summary>Rare Ore Refiner</summary>
    [Description("Rare Ore Refiner")]
    [LongDescription("Rare Ore Refiner")]
    RareOreRefiner = 110,

    /// <summary>Production Intern</summary>
    [Description("Production Intern")]
    [LongDescription("Production Intern")]
    ProductionIntern = 111,

    /// <summary>Production Manager</summary>
    [Description("Production Manager")]
    [LongDescription("Production Manager")]
    ProductionManager = 112,

    /// <summary>Research Manager</summary>
    [Description("Research Manager")]
    [LongDescription("Research Manager")]
    ResearchManager = 113,

    /// <summary>Field Technician</summary>
    [Description("Field Technician")]
    [LongDescription("Field Technician")]
    FieldTechnician = 114,

    /// <summary>Business Mogul</summary>
    [Description("Business Mogul")]
    [LongDescription("Business Mogul")]
    BusinessMogul = 115,

    /// <summary>Business Tycoon</summary>
    [Description("Business Tycoon")]
    [LongDescription("Business Tycoon")]
    BusinessTycoon = 116,

    /// <summary>Remote Demolitions</summary>
    [Description("Remote Demolitions")]
    [LongDescription("Remote Demolitions")]
    RemoteDemolitions = 117,

    /// <summary>Colony Management</summary>
    [Description("Colony Management")]
    [LongDescription("Colony Management")]
    ColonyManagement = 140,

    /// <summary>Planetology</summary>
    [Description("Planetology")]
    [LongDescription("Planetology")]
    Planetology = 141,
  }
}
