// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Character {
  using System.CodeDom.Compiler;
  using System.ComponentModel;


  /// <summary>Contains the ID values associated with the CharacterAttribute class.</summary>
  [GeneratedCode("Eve", "1.76.447.16191")]
  [Description("Contains the ID values associated with the CharacterAttribute class.")]
  public enum CharacterAttributeId : byte {

    /// <summary>&lt;b&gt;Intelligence is a measure of a pilot's capacity for learning, reasoning, and understanding.&lt;/b&gt; It is also an aptitude indicator for cognitive abilities such as logical reasoning and abstract thinking. In the EVE universe, pilots with a high intelligence score possess an innate mastery of core academic disciplines such as mathematics and physics.
    ///
    ///&lt;b&gt;Skill categories&lt;/b&gt; such as &lt;b&gt;Electronics, Engineering, Navigation, and Science all require direct application of these disciplines&lt;/b&gt; and build extensively on them throughout the pilot's skill advancement, irrespective of career choice. Additionally, advanced starship technologies such as &lt;b&gt;Electronic Warfare, Shield Operation, and Cloaking&lt;/b&gt; will require a high Intelligence score to master quickly.
    ///
    ///This attribute is secondary for numerous &lt;b&gt;social and industrial skills&lt;/b&gt; as well. </summary>
    [Description(@"<b>Intelligence is a measure of a pilot's capacity for learning, reasoning, and understanding.</b> It is also an aptitude indicator for cognitive abilities such as logical reasoning and abstract thinking. In the EVE universe, pilots with a high intelligence score possess an innate mastery of core academic disciplines such as mathematics and physics.

<b>Skill categories</b> such as <b>Electronics, Engineering, Navigation, and Science all require direct application of these disciplines</b> and build extensively on them throughout the pilot's skill advancement, irrespective of career choice. Additionally, advanced starship technologies such as <b>Electronic Warfare, Shield Operation, and Cloaking</b> will require a high Intelligence score to master quickly.

This attribute is secondary for numerous <b>social and industrial skills</b> as well. ")]
    
    Intelligence = 1,

    /// <summary>&lt;b&gt;Charisma is personal attractiveness or magnetism that promotes individual influence on others&lt;/b&gt;. Great leaders across the ages who were able to motivate and inspire great numbers of people are said to have had high charisma attributes. The power of persuasion and the ability to lead are invaluable resources for engaging in social interactions, regardless of career path. In the universe of EVE, this attribute is &lt;b&gt;essential for maintaining positive standings with political entities&lt;/b&gt; such as factions, corporations and police forces.
    ///
    ///Although it influences fewer skills than any other attribute, Charisma is essential for aspiring CEOs, fleet commanders and business tycoons. &lt;b&gt;Skills that require Charisma&lt;/b&gt; as a primary attribute &lt;b&gt;include Leadership, Social and Trade&lt;/b&gt;.
    ///
    ///The main &lt;b&gt;secondary attribute skill is Investor Management&lt;/b&gt;.</summary>
    [Description(@"<b>Charisma is personal attractiveness or magnetism that promotes individual influence on others</b>. Great leaders across the ages who were able to motivate and inspire great numbers of people are said to have had high charisma attributes. The power of persuasion and the ability to lead are invaluable resources for engaging in social interactions, regardless of career path. In the universe of EVE, this attribute is <b>essential for maintaining positive standings with political entities</b> such as factions, corporations and police forces.

Although it influences fewer skills than any other attribute, Charisma is essential for aspiring CEOs, fleet commanders and business tycoons. <b>Skills that require Charisma</b> as a primary attribute <b>include Leadership, Social and Trade</b>.

The main <b>secondary attribute skill is Investor Management</b>.")]
    
    Charisma = 2,

    /// <summary>&lt;b&gt;Perception measures a pilot's ability to assimilate sensory information from the surrounding environment and formulate effective actions in response&lt;/b&gt;. Intuitively determining the orientation of objects in three-dimensional space relative to fixed or moving reference points, and measuring object motion characteristics such as vector, speed, and trajectory within this space; both of these are functions of Perception. Assessing the temporo-spatial relationship between two or more objects is a critical component of battlefield tactical awareness, and the speed with which this data can be processed thus determines overall reaction time and effectiveness in combat.
    ///
    ///&lt;b&gt;Perception is the primary attribute in the training of Gunnery, Missile Launcher Operation, and Spaceship Command skills&lt;/b&gt;.
    ///
    ///It is also a secondary attribute for &lt;b&gt;Spaceship Command, Drones, and Navigation skills&lt;/b&gt;.</summary>
    [Description(@"<b>Perception measures a pilot's ability to assimilate sensory information from the surrounding environment and formulate effective actions in response</b>. Intuitively determining the orientation of objects in three-dimensional space relative to fixed or moving reference points, and measuring object motion characteristics such as vector, speed, and trajectory within this space; both of these are functions of Perception. Assessing the temporo-spatial relationship between two or more objects is a critical component of battlefield tactical awareness, and the speed with which this data can be processed thus determines overall reaction time and effectiveness in combat.

<b>Perception is the primary attribute in the training of Gunnery, Missile Launcher Operation, and Spaceship Command skills</b>.

It is also a secondary attribute for <b>Spaceship Command, Drones, and Navigation skills</b>.")]
    
    Perception = 3,

    /// <summary>&lt;b&gt;Memory is the mental capacity to retain and recall facts derived from prior learning experiences and apply them during situational circumstances&lt;/b&gt;. The speed with which a pilot can recall and apply data while subject to duress is a critical component&lt;/b&gt; of effective reflex development in combat training. In EVE, the memory attribute is a composite measure of both long and short-term memory variants, both of which apply to a broad set of abilities ranging from industrial and scientific disciplines to battlefield tactical awareness.
    ///
    ///&lt;b&gt;Memory is a primary attribute for skills such as Investor Management and Drones&lt;/b&gt;.
    ///
    ///It is also a &lt;b&gt;secondary attribute for&lt;/b&gt; numerous others, including &lt;b&gt;Engineering, Mechanic, Electronics, and Trade.&lt;/b&gt;</summary>
    [Description(@"<b>Memory is the mental capacity to retain and recall facts derived from prior learning experiences and apply them during situational circumstances</b>. The speed with which a pilot can recall and apply data while subject to duress is a critical component</b> of effective reflex development in combat training. In EVE, the memory attribute is a composite measure of both long and short-term memory variants, both of which apply to a broad set of abilities ranging from industrial and scientific disciplines to battlefield tactical awareness.

<b>Memory is a primary attribute for skills such as Investor Management and Drones</b>.

It is also a <b>secondary attribute for</b> numerous others, including <b>Engineering, Mechanic, Electronics, and Trade.</b>")]
    
    Memory = 4,

    /// <summary>&lt;b&gt;Willpower is resolute control over one's own actions, impulses, and behavior.&lt;/b&gt; It embodies the capability of focusing on the achievement of personal goals, irrespective of setbacks or adversity. In combat, the ability to concentrate on dynamic battlefield conditions and exercise patience when determining the timing of active defenses or attacks is also a function of willpower. This attribute is the consummate survival gauge: The higher the score, the more likely the pilot will be able to persevere in difficult circumstances.
    ///
    ///A crucial component for success in all forms of command, &lt;b&gt;Willpower is a primary attribute for Trade, Leadership, and Advanced Spaceship skills&lt;/b&gt;.
    ///
    ///It is also a key &lt;b&gt;secondary attribute for&lt;/b&gt; many combat skills, such as &lt;b&gt;Gunnery, Spaceship Command, and Missile Launcher Operation&lt;/b&gt;.</summary>
    [Description(@"<b>Willpower is resolute control over one's own actions, impulses, and behavior.</b> It embodies the capability of focusing on the achievement of personal goals, irrespective of setbacks or adversity. In combat, the ability to concentrate on dynamic battlefield conditions and exercise patience when determining the timing of active defenses or attacks is also a function of willpower. This attribute is the consummate survival gauge: The higher the score, the more likely the pilot will be able to persevere in difficult circumstances.

A crucial component for success in all forms of command, <b>Willpower is a primary attribute for Trade, Leadership, and Advanced Spaceship skills</b>.

It is also a key <b>secondary attribute for</b> many combat skills, such as <b>Gunnery, Spaceship Command, and Missile Launcher Operation</b>.")]
    
    Willpower = 5,
  }
}
