// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe {


  /// <summary>Contains the ID values associated with the AgentType class.</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Eve.Meta", "1.76.447.38458")]
  [System.ComponentModel.DescriptionAttribute("Contains the ID values associated with the AgentType class.")]
  public enum AgentTypeId : int {

    /// <summary>NonAgent</summary>
    
    NonAgent = 1,

    /// <summary>BasicAgent</summary>
    
    BasicAgent = 2,

    /// <summary>TutorialAgent</summary>
    
    TutorialAgent = 3,

    /// <summary>ResearchAgent</summary>
    
    ResearchAgent = 4,

    /// <summary>CONCORDAgent</summary>
    
    ConcordAgent = 5,

    /// <summary>GenericStorylineMissionAgent</summary>
    
    GenericStorylineMissionAgent = 6,

    /// <summary>StorylineMissionAgent</summary>
    
    StorylineMissionAgent = 7,

    /// <summary>EventMissionAgent</summary>
    
    EventMissionAgent = 8,

    /// <summary>FactionalWarfareAgent</summary>
    
    FactionalWarfareAgent = 9,

    /// <summary>EpicArcAgent</summary>
    
    EpicArcAgent = 10,

    /// <summary>AuraAgent</summary>
    
    AuraAgent = 11,

    /// <summary>CareerAgent</summary>
    
    CareerAgent = 12,
  }
}
