// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the AgentType class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the AgentType class.")]
  public enum AgentTypeId : int
  {

    /// <summary>NonAgent</summary>
    [Description("NonAgent")]
    NonAgent = 1,

    /// <summary>BasicAgent</summary>
    [Description("BasicAgent")]
    BasicAgent = 2,

    /// <summary>TutorialAgent</summary>
    [Description("TutorialAgent")]
    TutorialAgent = 3,

    /// <summary>ResearchAgent</summary>
    [Description("ResearchAgent")]
    ResearchAgent = 4,

    /// <summary>CONCORDAgent</summary>
    [Description("CONCORDAgent")]
    ConcordAgent = 5,

    /// <summary>GenericStorylineMissionAgent</summary>
    [Description("GenericStorylineMissionAgent")]
    GenericStorylineMissionAgent = 6,

    /// <summary>StorylineMissionAgent</summary>
    [Description("StorylineMissionAgent")]
    StorylineMissionAgent = 7,

    /// <summary>EventMissionAgent</summary>
    [Description("EventMissionAgent")]
    EventMissionAgent = 8,

    /// <summary>FactionalWarfareAgent</summary>
    [Description("FactionalWarfareAgent")]
    FactionalWarfareAgent = 9,

    /// <summary>EpicArcAgent</summary>
    [Description("EpicArcAgent")]
    EpicArcAgent = 10,

    /// <summary>AuraAgent</summary>
    [Description("AuraAgent")]
    AuraAgent = 11,

    /// <summary>CareerAgent</summary>
    [Description("CareerAgent")]
    CareerAgent = 12,
  }
}
