// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe {


  /// <summary>Contains the ID values associated with the AgentType class.</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Eve.Meta", "1.76.447.38458")]
  [System.ComponentModel.DescriptionAttribute("Contains the ID values associated with the AgentType class.")]
  public enum AgentTypeId : int {

    /// <summary>NonAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("NonAgent", "Eve.Universe.AgentTypeId_NonAgent")]
    NonAgent = 1,

    /// <summary>BasicAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("BasicAgent", "Eve.Universe.AgentTypeId_BasicAgent")]
    BasicAgent = 2,

    /// <summary>TutorialAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("TutorialAgent", "Eve.Universe.AgentTypeId_TutorialAgent")]
    TutorialAgent = 3,

    /// <summary>ResearchAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("ResearchAgent", "Eve.Universe.AgentTypeId_ResearchAgent")]
    ResearchAgent = 4,

    /// <summary>CONCORDAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("CONCORDAgent", "Eve.Universe.AgentTypeId_ConcordAgent")]
    ConcordAgent = 5,

    /// <summary>GenericStorylineMissionAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("GenericStorylineMissionAgent", "Eve.Universe.AgentTypeId_GenericStorylineMissionAgent")]
    GenericStorylineMissionAgent = 6,

    /// <summary>StorylineMissionAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("StorylineMissionAgent", "Eve.Universe.AgentTypeId_StorylineMissionAgent")]
    StorylineMissionAgent = 7,

    /// <summary>EventMissionAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("EventMissionAgent", "Eve.Universe.AgentTypeId_EventMissionAgent")]
    EventMissionAgent = 8,

    /// <summary>FactionalWarfareAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("FactionalWarfareAgent", "Eve.Universe.AgentTypeId_FactionalWarfareAgent")]
    FactionalWarfareAgent = 9,

    /// <summary>EpicArcAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("EpicArcAgent", "Eve.Universe.AgentTypeId_EpicArcAgent")]
    EpicArcAgent = 10,

    /// <summary>AuraAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("AuraAgent", "Eve.Universe.AgentTypeId_AuraAgent")]
    AuraAgent = 11,

    /// <summary>CareerAgent</summary>
    [FreeNet.Globalization.LocalizedLabelAttribute("CareerAgent", "Eve.Universe.AgentTypeId_CareerAgent")]
    CareerAgent = 12,
  }
}
