// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;


  /// <summary>Contains the purpose of a control tower resource.</summary>
  [GeneratedCode("Eve.Meta", "1.0.0.0")]
  [Description("Contains the purpose of a control tower resource.")]
  public enum ControlTowerResourcePurpose : byte
  {

    /// <summary>Online</summary>
    [Description("Online")]
    Online = 1,

    /// <summary>Power</summary>
    [Description("Power")]
    Power = 2,

    /// <summary>CPU</summary>
    [Description("CPU")]
    Cpu = 3,

    /// <summary>Reinforce</summary>
    [Description("Reinforce")]
    Reinforce = 4,
  }
}
