// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe {
  using System.CodeDom.Compiler;
  using System.ComponentModel;


  /// <summary>Contains the ID values associated with the CorporateActivity class.</summary>
  [GeneratedCode("Eve", "1.76.447.25341")]
  [Description("Contains the ID values associated with the CorporateActivity class.")]
  public enum CorporateActivityId : byte {

    /// <summary>Agriculture</summary>
    
    Agriculture = 1,

    /// <summary>Construction</summary>
    
    Construction = 2,

    /// <summary>Mining</summary>
    
    Mining = 3,

    /// <summary>Chemical</summary>
    
    Chemical = 4,

    /// <summary>Military</summary>
    
    Military = 5,

    /// <summary>Biotech</summary>
    
    Biotech = 6,

    /// <summary>Hi-Tech</summary>
    
    HiTech = 7,

    /// <summary>Entertainment</summary>
    
    Entertainment = 8,

    /// <summary>Shipyard</summary>
    
    Shipyard = 9,

    /// <summary>Warehouse</summary>
    
    Warehouse = 10,

    /// <summary>Retail</summary>
    
    Retail = 11,

    /// <summary>Trading</summary>
    
    Trading = 12,

    /// <summary>Bureaucratic</summary>
    
    Bureaucratic = 13,

    /// <summary>Political</summary>
    
    Political = 14,

    /// <summary>Legal</summary>
    
    Legal = 15,

    /// <summary>Security</summary>
    
    Security = 16,

    /// <summary>Financial</summary>
    
    Financial = 17,

    /// <summary>Education</summary>
    
    Education = 18,

    /// <summary>Manufacture</summary>
    
    Manufacture = 19,

    /// <summary>Disputed</summary>
    
    Disputed = 20,
  }
}
