// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the CorporateActivity class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the CorporateActivity class.")]
  public enum CorporateActivityId : byte
  {

    /// <summary>Agriculture</summary>
    [Description("Agriculture")]
    Agriculture = 1,

    /// <summary>Construction</summary>
    [Description("Construction")]
    Construction = 2,

    /// <summary>Mining</summary>
    [Description("Mining")]
    Mining = 3,

    /// <summary>Chemical</summary>
    [Description("Chemical")]
    Chemical = 4,

    /// <summary>Military</summary>
    [Description("Military")]
    Military = 5,

    /// <summary>Biotech</summary>
    [Description("Biotech")]
    Biotech = 6,

    /// <summary>Hi-Tech</summary>
    [Description("Hi-Tech")]
    HiTech = 7,

    /// <summary>Entertainment</summary>
    [Description("Entertainment")]
    Entertainment = 8,

    /// <summary>Shipyard</summary>
    [Description("Shipyard")]
    Shipyard = 9,

    /// <summary>Warehouse</summary>
    [Description("Warehouse")]
    Warehouse = 10,

    /// <summary>Retail</summary>
    [Description("Retail")]
    Retail = 11,

    /// <summary>Trading</summary>
    [Description("Trading")]
    Trading = 12,

    /// <summary>Bureaucratic</summary>
    [Description("Bureaucratic")]
    Bureaucratic = 13,

    /// <summary>Political</summary>
    [Description("Political")]
    Political = 14,

    /// <summary>Legal</summary>
    [Description("Legal")]
    Legal = 15,

    /// <summary>Security</summary>
    [Description("Security")]
    Security = 16,

    /// <summary>Financial</summary>
    [Description("Financial")]
    Financial = 17,

    /// <summary>Education</summary>
    [Description("Education")]
    Education = 18,

    /// <summary>Manufacture</summary>
    [Description("Manufacture")]
    Manufacture = 19,

    /// <summary>Disputed</summary>
    [Description("Disputed")]
    Disputed = 20,
  }
}
