// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe {
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    
    
    /// <summary>Contains the ID values associated with the Division class.</summary>
    [GeneratedCode("Eve", "1.76.447.39824")]
    [Description("Contains the ID values associated with the Division class.")]
    public enum DivisionId : byte {
        
        /// <summary>Accounting</summary>
        
        Accounting = 1,
        
        /// <summary>Administration</summary>
        
        Administration = 2,
        
        /// <summary>Advisory</summary>
        
        Advisory = 3,
        
        /// <summary>Archives</summary>
        
        Archives = 4,
        
        /// <summary>Astrosurveying</summary>
        
        Astrosurveying = 5,
        
        /// <summary>Command</summary>
        
        Command = 6,
        
        /// <summary>Distribution</summary>
        
        Distribution = 7,
        
        /// <summary>Financial</summary>
        
        Financial = 8,
        
        /// <summary>Intelligence</summary>
        
        Intelligence = 9,
        
        /// <summary>Internal Security</summary>
        
        InternalSecurity = 10,
        
        /// <summary>Legal</summary>
        
        Legal = 11,
        
        /// <summary>Manufacturing</summary>
        
        Manufacturing = 12,
        
        /// <summary>Marketing</summary>
        
        Marketing = 13,
        
        /// <summary>Mining</summary>
        
        Mining = 14,
        
        /// <summary>Personnel</summary>
        
        Personnel = 15,
        
        /// <summary>Production</summary>
        
        Production = 16,
        
        /// <summary>Public Relations</summary>
        
        PublicRelations = 17,
        
        /// <summary>R&D</summary>
        
        RAndD = 18,
        
        /// <summary>Security</summary>
        
        Security = 19,
        
        /// <summary>Storage</summary>
        
        Storage = 20,
        
        /// <summary>Surveillance</summary>
        
        Surveillance = 21,
        
        /// <summary>New distribution division</summary>
        [Description("New distribution division")]
        
        Distribution1 = 22,
        
        /// <summary>New mining division</summary>
        [Description("New mining division")]
        
        Mining1 = 23,
        
        /// <summary>New security division</summary>
        [Description("New security division")]
        
        Security1 = 24,
        
        /// <summary>Business career</summary>
        [Description("Business career")]
        
        Business = 25,
        
        /// <summary>Exploration career</summary>
        [Description("Exploration career")]
        
        Exploration = 26,
        
        /// <summary>Industry career</summary>
        [Description("Industry career")]
        
        Industry = 27,
        
        /// <summary>Military career</summary>
        [Description("Military career")]
        
        Military = 28,
        
        /// <summary>Advanced Military career</summary>
        [Description("Advanced Military career")]
        
        AdvancedMilitary = 29,
    }
}
