// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the Division class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the Division class.")]
  public enum DivisionId : byte
  {

    /// <summary>Accounting</summary>
    [Description("Accounting")]
    Accounting = 1,

    /// <summary>Administration</summary>
    [Description("Administration")]
    Administration = 2,

    /// <summary>Advisory</summary>
    [Description("Advisory")]
    Advisory = 3,

    /// <summary>Archives</summary>
    [Description("Archives")]
    Archives = 4,

    /// <summary>Astrosurveying</summary>
    [Description("Astrosurveying")]
    Astrosurveying = 5,

    /// <summary>Command</summary>
    [Description("Command")]
    Command = 6,

    /// <summary>Distribution</summary>
    [Description("Distribution")]
    Distribution = 7,

    /// <summary>Financial</summary>
    [Description("Financial")]
    Financial = 8,

    /// <summary>Intelligence</summary>
    [Description("Intelligence")]
    Intelligence = 9,

    /// <summary>Internal Security</summary>
    [Description("Internal Security")]
    InternalSecurity = 10,

    /// <summary>Legal</summary>
    [Description("Legal")]
    Legal = 11,

    /// <summary>Manufacturing</summary>
    [Description("Manufacturing")]
    Manufacturing = 12,

    /// <summary>Marketing</summary>
    [Description("Marketing")]
    Marketing = 13,

    /// <summary>Mining</summary>
    [Description("Mining")]
    Mining = 14,

    /// <summary>Personnel</summary>
    [Description("Personnel")]
    Personnel = 15,

    /// <summary>Production</summary>
    [Description("Production")]
    Production = 16,

    /// <summary>Public Relations</summary>
    [Description("Public Relations")]
    PublicRelations = 17,

    /// <summary>R&D</summary>
    [Description("R&D")]
    RAndD = 18,

    /// <summary>Security</summary>
    [Description("Security")]
    Security = 19,

    /// <summary>Storage</summary>
    [Description("Storage")]
    Storage = 20,

    /// <summary>Surveillance</summary>
    [Description("Surveillance")]
    Surveillance = 21,

    /// <summary>New distribution division</summary>
    [Description("Distribution")]
    [LongDescription("New distribution division")]
    Distribution1 = 22,

    /// <summary>New mining division</summary>
    [Description("Mining")]
    [LongDescription("New mining division")]
    Mining1 = 23,

    /// <summary>New security division</summary>
    [Description("Security")]
    [LongDescription("New security division")]
    Security1 = 24,

    /// <summary>Business career</summary>
    [Description("Business")]
    [LongDescription("Business career")]
    Business = 25,

    /// <summary>Exploration career</summary>
    [Description("Exploration")]
    [LongDescription("Exploration career")]
    Exploration = 26,

    /// <summary>Industry career</summary>
    [Description("Industry")]
    [LongDescription("Industry career")]
    Industry = 27,

    /// <summary>Military career</summary>
    [Description("Military")]
    [LongDescription("Military career")]
    Military = 28,

    /// <summary>Advanced Military career</summary>
    [Description("Advanced Military")]
    [LongDescription("Advanced Military career")]
    AdvancedMilitary = 29,
  }
}
