// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe {
  using System.CodeDom.Compiler;
  using System.ComponentModel;


  /// <summary>Contains the ID values associated with the StationOperation class.</summary>
  [GeneratedCode("Eve", "1.76.447.25710")]
  [Description("Contains the ID values associated with the StationOperation class.")]
  public enum StationOperationId : byte {

    /// <summary>Makes livestock and grain that is shipped to food processing units.</summary>
    [Description("Makes livestock and grain that is shipped to food processing units.")]
    
    Plantation = 1,

    /// <summary>Makes food that is shipped to warehouses.</summary>
    [Description("Makes food that is shipped to warehouses.")]
    
    FoodPackaging = 2,

    /// <summary>Stores products and shifts goods to external retailers or production corporations.</summary>
    [Description("Stores products and shifts goods to external retailers or production corporations" +
        ".")]
    
    Warehouse = 3,

    /// <summary>Mines minerals from asteroid belts/clouds.</summary>
    [Description("Mines minerals from asteroid belts/clouds.")]
    
    Foundry = 4,

    /// <summary>Molds finished construction pieces.</summary>
    [Description("Molds finished construction pieces.")]
    
    ProductionPlant = 5,

    /// <summary>Stores product and freights goods to production corps.</summary>
    [Description("Stores product and freights goods to production corps.")]
    
    Warehouse1 = 6,

    /// <summary>Mines minerals from asteroid belts/clouds.</summary>
    [Description("Mines minerals from asteroid belts/clouds.")]
    
    MiningOutpost = 7,

    /// <summary>Refines the minerals, making purified ingots and rock materials.</summary>
    [Description("Refines the minerals, making purified ingots and rock materials.")]
    
    Refinery = 8,

    /// <summary>Stores product and freights goods to production corps.</summary>
    [Description("Stores product and freights goods to production corps.")]
    
    MineralReserve = 9,

    /// <summary>Extracts chemicals from asteroid belts/clouds.</summary>
    [Description("Extracts chemicals from asteroid belts/clouds.")]
    
    ReprocessingFacility = 10,

    /// <summary>Refines the harvested chemicals, making bottled products.</summary>
    [Description("Refines the harvested chemicals, making bottled products.")]
    
    ChemicalRefinery = 11,

    /// <summary>Stores products and shifts goods to production corporations.</summary>
    [Description("Stores products and shifts goods to production corporations.")]
    
    ChemicalStorage = 12,

    /// <summary>Makes plans and blueprints that are shipped to Assembly Plant.</summary>
    [Description("Makes plans and blueprints that are shipped to Assembly Plant.")]
    
    TestingFacilities = 13,

    /// <summary>Produces weapons and ammunition that are shipped for storage.</summary>
    [Description("Produces weapons and ammunition that are shipped for storage.")]
    
    AssemblyPlant = 14,

    /// <summary>Stores product and freights goods to external retailers.</summary>
    [Description("Stores product and freights goods to external retailers.")]
    
    LogisticSupport = 15,

    /// <summary>Harvests resources from a planet.</summary>
    [Description("Harvests resources from a planet.")]
    
    BiotechResearchCenter = 16,

    /// <summary>Produces Biotech products.</summary>
    [Description("Produces Biotech products.")]
    
    BiotechProduction = 17,

    /// <summary>Stores and recycles materials classified as biohazards.</summary>
    [Description("Stores and recycles materials classified as biohazards.")]
    
    BiohazardContainmentFacility = 18,

    /// <summary>Makes plans and blueprints that are shipped to Factory.</summary>
    [Description("Makes plans and blueprints that are shipped to Factory.")]
    
    ResearchCenter = 19,

    /// <summary>Produces finished hi-tech products.</summary>
    [Description("Produces finished hi-tech products.")]
    
    Factory = 20,

    /// <summary>Stores product and freights goods to external retailers.</summary>
    [Description("Stores product and freights goods to external retailers.")]
    
    Warehouse2 = 21,

    /// <summary>Produces entertainment material that is shipped to Publisher.</summary>
    [Description("Produces entertainment material that is shipped to Publisher.")]
    
    DevelopmentStudio = 22,

    /// <summary>Stores and multiplies the entertainment material and ships it to retailers.</summary>
    [Description("Stores and multiplies the entertainment material and ships it to retailers.")]
    
    Publisher = 23,

    /// <summary>Produces starships that are shipped for storage in Storage Bay.</summary>
    [Description("Produces starships that are shipped for storage in Storage Bay.")]
    
    Shipyard = 24,

    /// <summary>Stores ships before freighting them to retailers.</summary>
    [Description("Stores ships before freighting them to retailers.")]
    
    StorageBay = 25,

    /// <summary>Stores cargo for other corps before shipping it to retailers.</summary>
    [Description("Stores cargo for other corps before shipping it to retailers.")]
    
    Storage = 26,

    /// <summary>Stores products and freights goods to retail center.</summary>
    [Description("Stores products and freights goods to retail center.")]
    
    Warehouse3 = 27,

    /// <summary>Sells goods from warehouses to consumers, and to service stations.</summary>
    [Description("Sells goods from warehouses to consumers, and to service stations.")]
    
    RetailCenter = 28,

    /// <summary>Stores products and freights goods to Trading Post.</summary>
    [Description("Stores products and freights goods to Trading Post.")]
    
    Warehouse4 = 29,

    /// <summary>Sells wares received from production corps.</summary>
    [Description("Sells wares received from production corps.")]
    
    TradingPost = 30,

    /// <summary>Delivers reports and provides information concerning the Bureau's field.</summary>
    [Description("Delivers reports and provides information concerning the Bureau\'s field.")]
    
    BureauOffices = 31,

    /// <summary>Studies issues within the administration system and produces personnel.</summary>
    [Description("Studies issues within the administration system and produces personnel.")]
    
    Academy = 32,

    /// <summary>Delivers reports and publishes rules and manifestos concerning the Bureau's field.</summary>
    [Description("Delivers reports and publishes rules and manifestos concerning the Bureau\'s field" +
        ".")]
    
    Bureau = 33,

    /// <summary>Stores data and kredit sheets for the Bureau to work with.</summary>
    [Description("Stores data and kredit sheets for the Bureau to work with.")]
    
    Treasury = 34,

    /// <summary>Works as a bank.</summary>
    [Description("Works as a bank.")]
    
    Depository = 35,

    /// <summary>Stores data and kredit sheets for the Bank to work with.</summary>
    [Description("Stores data and kredit sheets for the Bank to work with.")]
    
    Vault = 36,

    /// <summary>Produces personnel and sells skill packages.</summary>
    [Description("Produces personnel and sells skill packages.")]
    
    School = 37,

    /// <summary>Factory</summary>
    
    Factory1 = 38,

    /// <summary>Warehouse</summary>
    
    Warehouse5 = 39,

    /// <summary>Courts where judicial matters are judged</summary>
    [Description("Courts where judicial matters are judged")]
    
    Tribunal = 40,

    /// <summary>Accounting and audit firms</summary>
    [Description("Accounting and audit firms")]
    
    Accounting = 41,

    /// <summary>Law School</summary>
    
    LawSchool = 42,

    /// <summary>Stores administrative documents and data.</summary>
    [Description("Stores administrative documents and data.")]
    
    Archives = 43,

    /// <summary>Distributes administrative information to the public.</summary>
    [Description("Distributes administrative information to the public.")]
    
    InformationCenter = 44,

    /// <summary>Manufacturing</summary>
    
    Manufacturing = 45,

    /// <summary>Refining</summary>
    
    Refining = 46,

    /// <summary>Cloning</summary>
    
    Cloning = 47,

    /// <summary>Caldari Research Outpost</summary>
    
    CaldariResearchOutpost = 48,

    /// <summary>Amarr Factory Outpost</summary>
    
    AmarrFactoryOutpost = 49,

    /// <summary>Gallente Administrative Outpost</summary>
    
    GallenteAdministrativeOutpost = 50,

    /// <summary>Minmatar Service Outpost</summary>
    
    MinmatarServiceOutpost = 51,
  }
}
