// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using FreeNet;


  /// <summary>Contains the ID values associated with the StationService class.</summary>
  [GeneratedCode("Eve", "1.76.447.20946")]
  [Description("Contains the ID values associated with the StationService class.")]
  [Flags()]
  public enum StationServiceId : int
  {

    /// <summary>Bounty Missions</summary>
    [Description("Bounty Missions")]
    BountyMissions = 1,

    /// <summary>Assassination Missions</summary>
    [Description("Assassination Missions")]
    AssassinationMissions = 2,

    /// <summary>Courier Missions</summary>
    [Description("Courier Missions")]
    CourierMissions = 4,

    /// <summary>Interbus</summary>
    [Description("Interbus")]
    Interbus = 8,

    /// <summary>Reprocessing Plant</summary>
    [Description("Reprocessing Plant")]
    ReprocessingPlant = 16,

    /// <summary>Refinery</summary>
    [Description("Refinery")]
    Refinery = 32,

    /// <summary>Market</summary>
    [Description("Market")]
    Market = 64,

    /// <summary>Black Market</summary>
    [Description("Black Market")]
    BlackMarket = 128,

    /// <summary>Stock Exchange</summary>
    [Description("Stock Exchange")]
    StockExchange = 256,

    /// <summary>Cloning</summary>
    [Description("Cloning")]
    Cloning = 512,

    /// <summary>Surgery</summary>
    [Description("Surgery")]
    Surgery = 1024,

    /// <summary>DNA Therapy</summary>
    [Description("DNA Therapy")]
    DnaTherapy = 2048,

    /// <summary>Repair Facilities</summary>
    [Description("Repair Facilities")]
    RepairFacilities = 4096,

    /// <summary>Factory</summary>
    [Description("Factory")]
    Factory = 8192,

    /// <summary>Laboratory</summary>
    [Description("Laboratory")]
    Laboratory = 16384,

    /// <summary>Gambling</summary>
    [Description("Gambling")]
    Gambling = 32768,

    /// <summary>Fitting</summary>
    [Description("Fitting")]
    Fitting = 65536,

    /// <summary>Paintshop</summary>
    [Description("Paintshop")]
    Paintshop = 131072,

    /// <summary>News</summary>
    [Description("News")]
    News = 262144,

    /// <summary>Storage</summary>
    [Description("Storage")]
    Storage = 524288,

    /// <summary>Used to buy insurance for ships.</summary>
    [Description("Insurance")]
    [LongDescription("Used to buy insurance for ships.")]
    Insurance = 1048576,

    /// <summary>Docking</summary>
    [Description("Docking")]
    Docking = 2097152,

    /// <summary>Office Rental</summary>
    [Description("Office Rental")]
    OfficeRental = 4194304,

    /// <summary>Jump Clone Facility</summary>
    [Description("Jump Clone Facility")]
    JumpCloneFacility = 8388608,

    /// <summary>Loyalty Point Store</summary>
    [Description("Loyalty Point Store")]
    LoyaltyPointStore = 16777216,

    /// <summary>Navy Offices</summary>
    [Description("Navy Offices")]
    NavyOffices = 33554432,
  }
}
