// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Universe {
  using System;
  using System.CodeDom.Compiler;
  using System.ComponentModel;

  /// <summary>Contains the ID values associated with the StationService class.</summary>
  [GeneratedCode("Eve", "1.76.447.24696")]
  [Description("Contains the ID values associated with the StationService class.")]
  [Flags]
  public enum StationServiceId : int {

    /// <summary>Bounty Missions</summary>
    
    BountyMissions = 1,

    /// <summary>Assassination Missions</summary>
    
    AssassinationMissions = 2,

    /// <summary>Courier Missions</summary>
    
    CourierMissions = 4,

    /// <summary>Interbus</summary>
    
    Interbus = 8,

    /// <summary>Reprocessing Plant</summary>
    
    ReprocessingPlant = 16,

    /// <summary>Refinery</summary>
    
    Refinery = 32,

    /// <summary>Market</summary>
    
    Market = 64,

    /// <summary>Black Market</summary>
    
    BlackMarket = 128,

    /// <summary>Stock Exchange</summary>
    
    StockExchange = 256,

    /// <summary>Cloning</summary>
    
    Cloning = 512,

    /// <summary>Surgery</summary>
    
    Surgery = 1024,

    /// <summary>DNA Therapy</summary>
    
    DnaTherapy = 2048,

    /// <summary>Repair Facilities</summary>
    
    RepairFacilities = 4096,

    /// <summary>Factory</summary>
    
    Factory = 8192,

    /// <summary>Laboratory</summary>
    
    Laboratory = 16384,

    /// <summary>Gambling</summary>
    
    Gambling = 32768,

    /// <summary>Fitting</summary>
    
    Fitting = 65536,

    /// <summary>Paintshop</summary>
    
    Paintshop = 131072,

    /// <summary>News</summary>
    
    News = 262144,

    /// <summary>Storage</summary>
    
    Storage = 524288,

    /// <summary>Used to buy insurance for ships.</summary>
    [Description("Used to buy insurance for ships.")]
    
    Insurance = 1048576,

    /// <summary>Docking</summary>
    
    Docking = 2097152,

    /// <summary>Office Rental</summary>
    
    OfficeRental = 4194304,

    /// <summary>Jump Clone Facility</summary>
    
    JumpCloneFacility = 8388608,

    /// <summary>Loyalty Point Store</summary>
    
    LoyaltyPointStore = 16777216,

    /// <summary>Navy Offices</summary>
    
    NavyOffices = 33554432,
  }
}
