// <auto-generated />
// NOTE: This file was auto-generated by a tool.  Do not edit this file manually.
// Any changes you make may be overwritten the next time the contents are generated.
namespace Eve.Industry
{
  using System.CodeDom.Compiler;
  using System.ComponentModel;

  /// <summary>Contains the ID values associated with the Activity class.</summary>
  [GeneratedCode("Eve.Meta", "1.0.0.0")]
  [Description("Contains the ID values associated with the Activity class.")]
  public enum ActivityId : byte
  {

    /// <summary>None</summary>
    [Description("None")]
    None = 0,

    /// <summary>Manufacturing</summary>
    [Description("Manufacturing")]
    Manufacturing = 1,

    /// <summary>Researching Technology</summary>
    [Description("Researching Technology")]
    ResearchingTechnology = 2,

    /// <summary>Researching Time Productivity</summary>
    [Description("Researching Time Productivity")]
    ResearchingTimeProductivity = 3,

    /// <summary>Researching Material Productivity</summary>
    [Description("Researching Material Productivity")]
    ResearchingMaterialProductivity = 4,

    /// <summary>Copying</summary>
    [Description("Copying")]
    Copying = 5,

    /// <summary>Duplicating</summary>
    [Description("Duplicating")]
    Duplicating = 6,

    /// <summary>Reverse Engineering</summary>
    [Description("Reverse Engineering")]
    ReverseEngineering = 7,

    /// <summary>Invention</summary>
    [Description("Invention")]
    Invention = 8,
  }
}
